"use client";
import Link from "next/link";
import {useState} from "react";
import {Button,Card,Input,Notice,Pill} from "../bdhub/ui";
import type {PreparationStatus} from "../../server/batch-preparation/bridge";
export default function BatchPreparationPanel(){
 const [target,setTarget]=useState("3000"),[busy,setBusy]=useState(false),[result,setResult]=useState<PreparationStatus|null>(null),[error,setError]=useState("");
 async function check(){setBusy(true);setError("");setResult(null);try{const r=await fetch("/api/batch-preparation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target:Number(target)})});const data=await r.json();if(!r.ok)throw new Error(data.error==="numeric_target_required"?"请输入有效的整数目标。":"暂时无法读取准备条件，请稍后重试。");setResult(data);}catch(e){setError(e instanceof Error?e.message:"暂时无法读取");}finally{setBusy(false);}}
 return <Card title="全量批次准备" subtitle="先检查正式名单、候补与商品材料的缺口。当前预检读取意大利真实数据。"><div className="space-y-5 p-5"><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void check();}}><label className="block"><span className="mb-2 block text-sm text-gray-600 dark:text-gray-300">目标达人数量</span><Input type="number" min={1} max={100000} step={1} value={target} onChange={e=>{setTarget(e.target.value);setResult(null);}} aria-label="批次目标达人数量" className="!w-48"/></label><Button type="submit" disabled={busy||!target}>{busy?"正在检查…":"检查准备条件"}</Button><span className="pb-2 text-xs text-gray-500">候补按目标的 10% 计算</span></form>
 {error&&<Notice tone="warning">{error}</Notice>}
 {result&&<>{result.globalSource?.available&&<p className="text-sm text-gray-500">主力全托来源已采集 {result.globalSource.products.toLocaleString()} 个商品，列表显示未选 {result.globalSource.listedUnselectedProducts.toLocaleString()} 个；{result.globalSource.published?"本查询已采完":"本查询仍未采完"}。<Link href="/catalog" className="ml-2 text-brand-500">查看货盘 →</Link></p>}<div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{[["正式＋候补",`${result.target} ＋ ${result.reserve}`],["本地候选达人",result.identityCandidates.toLocaleString()],["已定位名称与卡片",result.localMaterialsComplete.toLocaleString()],["候选名单缺口",result.candidateGap.toLocaleString()]].map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-xl font-semibold text-gray-800 dark:text-gray-100">{value}</p></div>)}</div>
 <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-medium">TapLink 准备已纳入检查</h3><Pill tone="warning">尚未放行发送</Pill></div><p className="mt-2 text-sm leading-6 text-gray-500">候选涉及 {result.productGroups} 个商品方案；{result.namesNeeded} 个需准备短名，{result.taplinksToCheckOrCreate} 个尚需核验或创建 TapLink。同一方案可供多位达人使用。</p></div>
 {result.products.length>0&&<details><summary className="cursor-pointer text-sm text-brand-500">查看商品方案与 TapLink 准备明细</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-gray-200 text-xs text-gray-500 dark:border-gray-700"><tr>{["商品","候选人数","达人佣金","TapLink"].map(h=><th key={h} className="px-2 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{result.products.map(p=><tr key={p.offerKey} className="border-b border-gray-100 dark:border-gray-800"><td className="px-2 py-3"><p>{p.shortName||"待准备商品短名"}</p><p className="mt-1 text-xs text-gray-400">{p.pid}</p></td><td className="px-2 py-3">{p.people}</td><td className="px-2 py-3">{p.creatorPercent}%</td><td className="px-2 py-3"><Pill tone={p.cardLocated?"success":"warning"}>{p.cardLocated?"已有核验记录":"待核验／创建"}</Pill></td></tr>)}</tbody></table><p className="mt-2 text-xs text-gray-400">最多展示 20 个商品方案。</p></div></details>}
 <Notice>这是本地准备容量预检，尚未创建发送任务。已有卡片记录不等于当前可发送，仍需完成全量名单、平台动态校验与指定全托来源接入。</Notice></>}
 {!result&&!busy&&<p className="text-sm leading-6 text-gray-500">按明确数量准备整批，TapLink 缺失或结果未知都会阻塞放行。检查不会发消息，也不会创建链接。</p>}
 </div></Card>;
}
