"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button,Card,Dialog,EmptyState,Field,Input,Notice,Pill,Select,TextArea} from "../bdhub/ui";
type Spec={institution:string;market:string;target:number;reserve:number;startDate:string;startTime:string;endTime:string;timezone:string;productScope:{kind:string;values:string[]};replyAfterSending:boolean};
type Prep={state:string;target:number;reserve:number;required:number;candidates:number;candidateGap:number;formal:number;reserves:number;named:number;cardsLocated:number;verifiedReady:number;eligiblePids:number;blockers:string[];stages?:{key:string;label:string;done:number;required:number}[];products?:{pid:string;shortName:string|null;cardLocated:boolean;nameReady:boolean}[]};
type Task={sourcePreparation?:{pids:number;pages:number;edges:number;states:Record<string,number>;errors:string[]}|null;id:string;spec:Spec;state:string;priority:number;revision:number;created:number;checkedAt:number|null;preparation:Prep|null;events:{kind:string;at:number}[]};
type Listing={tasks:Task[];worker:{running:boolean;heartbeat:number|null}};
type Preview={token:string;spec:Spec;policy:{version:string;templateVersion:number}};
const errors:Record<string,string>={invalid_send_window:"请填写不同的开始与截止时间。",numeric_target_required:"请填写 1–100000 的整数目标。",invalid_product_scope:"请检查商品范围，PID 应为 19 位数字。",start_date_required:"请选择开始日期。",invalid_start_date:"开始日期格式不正确。",revision_conflict:"任务已有更新，请刷新后再操作。",scope_adapter_unavailable:"当前仅意大利已接通本地准备。",task_card_stale:"规则版本已更新，请重新生成任务卡。",task_request_conflict:"此次确认内容已变化，请重新生成任务卡。"};
const blockers:Record<string,string>={pid_creator_supply_needed:"正在按本任务范围补充 PID 线索并解析身份，名单备齐后统一准备素材。",product_names_needed:"部分商品仍需生成短名，同商品只生成一次。",task_taplink_adapter_pending:"整批名单备齐后，自动准备短名并核验或创建商品卡。",task_materials_pending:"正在按商品方案准备短名和 TapLink。",product_name_preparation_unresolved:"商品短名生成尚未确认，将核对已有任务结果。",task_offer_changed:"部分商品佣金或有效性已变化，等待更新方案。",commission_rule_changed:"分佣规则已变化，需要重新核对任务方案。",task_card_read_unresolved:"部分商品卡未能完成核验，稍后重试。",task_card_creation_unresolved:"商品卡创建结果待核验，系统不会重复建卡。",local_source_unavailable:"暂时无法读取本地数据，将自动重试。"};
function time(at:number|null){return at?new Date(at*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"尚未检查";}
async function command(body:unknown){const r=await fetch("/api/batch-tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(errors[d.error]||"暂时无法完成操作，请稍后重试。");return d;}
export default function BatchTasksPanel(){
 const [data,setData]=useState<Listing|null>(null),[selected,setSelected]=useState<string|null>(null),[open,setOpen]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [target,setTarget]=useState(""),[date,setDate]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[scope,setScope]=useState("all_eligible"),[values,setValues]=useState("");
 const key=useRef("");
 const refresh=useCallback(async()=>{const r=await fetch("/api/batch-tasks",{cache:"no-store"});if(!r.ok)throw new Error("暂时无法读取任务列表。");setData(await r.json());},[]);
 useEffect(()=>{let live=true;const run=()=>{if(live)void refresh().catch(e=>{if(live)setError(e.message);});};run();const timer=setInterval(run,10000);return()=>{live=false;clearInterval(timer);};},[refresh]);
 const task=data?.tasks.find(t=>t.id===selected)||data?.tasks[0];
 async function review(){setBusy(true);setError("");try{const p=await command({action:"preview",spec:{institution:"bjn-local-research",market:"it",target:Number(target),startDate:date,startTime:start,endTime:end,productScope:{kind:scope,values:scope==="all_eligible"?[]:values.split(/[\s,，]+/).filter(Boolean)},replyAfterSending:false}});key.current=crypto.randomUUID();setPreview(p);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirm(){if(!preview)return;setBusy(true);setError("");try{const t=await command({action:"confirm",token:preview.token,requestKey:key.current,authorizationScope:"full_preparation_no_messages"});setSelected(t.id);setOpen(false);setPreview(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function control(action:string,priority?:number){if(!task)return;setBusy(true);setError("");try{await command({action,id:task.id,revision:task.revision,...(priority===undefined?{}:{priority})});await refresh();}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{setBusy(false);}}
 return <Card title="二发任务" subtitle="明确目标数量，整批准备正式名单与候补。" action={<Button onClick={()=>{setPreview(null);setError("");setOpen(true);}}>创建任务</Button>}>
 <div className="space-y-4 p-5">
 <Notice>已接入整批 PID 采集、身份补全、商品短名与已选／活动商品的 TapLink 准备。未选全托商品的自动选入、新任务发送仍在接入；AI 回复保持暂停。</Notice>
 {error&&!open&&<Notice tone="warning">{error}</Notice>}
 {data?.tasks.length===0?<EmptyState title="还没有指定数量的任务" description="填写数量、商品范围和北京时间时段，核对任务卡后确认。"/>:!data?<p className="py-6 text-sm text-gray-500">正在读取任务…</p>:<div className="grid gap-5 xl:grid-cols-[260px_minmax(0,1fr)]">
 <nav aria-label="二发任务列表" className="space-y-2">{data.tasks.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} aria-current={task?.id===t.id?"true":undefined} className={`w-full rounded-xl border p-4 text-left ${task?.id===t.id?"border-brand-300 bg-brand-50 dark:bg-brand-500/10":"border-gray-200 dark:border-gray-700"}`}><div className="flex items-center justify-between"><span className="font-semibold">意大利 · {t.spec.target.toLocaleString()} 人</span><Pill tone={t.state==="paused"?"neutral":"brand"}>{t.state==="paused"?"已暂停":t.state==="ready"?"已备齐":"准备中"}</Pill></div><p className="mt-2 text-xs text-gray-500">{t.spec.startDate} 起 · {t.spec.startTime}–{t.spec.endTime}</p><p className="mt-2 text-xs text-gray-500">候选 {t.preparation?.candidates??0} / {t.spec.target+t.spec.reserve} · 优先级 {t.priority}</p></button>)}</nav>
 {task&&<div className="min-w-0 space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">整批准备进度</h3><p className="mt-1 text-xs text-gray-500">北京时间 · {task.spec.startTime}–{task.spec.endTime}{task.spec.startTime>task.spec.endTime?"（跨午夜）":""} · {task.spec.productScope.kind==="all_eligible"?"全部合格货盘":"限定商品范围"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy||task.state==="ready"} onClick={()=>void control("priority",task.priority===0?10:0)}>{task.priority===0?"优先准备":"恢复普通优先级"}</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void control(task.state==="paused"?"resume":"pause")}>{task.state==="paused"?"继续准备":"暂停准备"}</Button></div></div>
 <div className="grid grid-cols-2 gap-3 2xl:grid-cols-4">{[["正式目标",task.spec.target],["候补目标",task.spec.reserve],["本地候选",task.preparation?.candidates??0],["任务核验就绪",task.preparation?.verifiedReady??0]].map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-xl font-semibold">{Number(value).toLocaleString()}</p></div>)}</div>
 {task.preparation?.stages?.map(stage=><div key={stage.key}><div className="mb-2 flex justify-between text-sm"><span>{stage.label}</span><span className="text-gray-500">{stage.done.toLocaleString()} / {stage.required.toLocaleString()}</span></div><div role="progressbar" aria-label={stage.label} aria-valuenow={stage.done} aria-valuemin={0} aria-valuemax={stage.required} className="h-2 overflow-hidden rounded-full bg-gray-100 dark:bg-gray-800"><div className="h-full rounded-full bg-brand-500" style={{width:`${Math.min(100,stage.done/stage.required*100)}%`}}/></div></div>)}
 <p className="text-xs text-gray-500">{task.state==="paused"?"准备已暂停":task.state==="ready"?"整批已备齐，发送器尚未开放":data.worker.running?"准备进程运行中":"准备进程尚未运行"} · 最近检查：{time(task.checkedAt)}</p>
 {task.preparation?<div className="space-y-2 rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><h4 className="text-sm font-medium">{task.state==="ready"?"准备完成":"尚需完成"}</h4>{task.preparation.blockers.map(b=><p key={b} className="text-sm leading-6 text-gray-500">{blockers[b]||b}</p>)}<p className="text-xs text-gray-500">已有卡片记录 {task.preparation.cardsLocated??0} 人；记录复用须完成本任务核验后才计入就绪。整批不足时保持等待。</p></div>:<p className="text-sm text-gray-500">任务已保存，等待首次准备检查。</p>}
 {task.sourcePreparation&&<div className="rounded-xl border border-gray-200 p-4 text-sm dark:border-gray-700"><h4 className="font-medium">本任务采集进度</h4><p className="mt-2 text-gray-500">已规划 {task.sourcePreparation.pids} 个 PID · 已保存 {task.sourcePreparation.pages} 页 · 已取得 {task.sourcePreparation.edges} 条商品—达人线索</p><p className="mt-1 text-xs text-gray-500">待采集 {task.sourcePreparation.states.queued??0} · 待身份结果 {task.sourcePreparation.states.awaiting_identity??0} · 已完成 {task.sourcePreparation.states.completed??0} · 异常 {task.sourcePreparation.states.blocked??0}</p>{task.sourcePreparation.errors.includes("kalodata_auth_required")&&<p className="mt-2 text-warning-600">Kalodata 登录失效，请更新登录后暂停再继续准备。</p>}</div>}
 <details><summary className="cursor-pointer text-sm text-brand-500">查看商品范围与准备记录</summary><div className="mt-3 space-y-2 text-xs text-gray-500"><p className="break-all">{task.spec.productScope.kind==="all_eligible"?"全部合格货盘":task.spec.productScope.values.join("、")}</p><p>全托商品不要求库存数；普通商品保留库存门槛。</p>{task.events.map((e,i)=><p key={i}>{time(e.at)} · {({task_confirmed:"任务已确认",preparation_observed:"准备状态已更新",pause:"人工暂停",resume:"继续准备",priority:"调整优先级"} as Record<string,string>)[e.kind]||e.kind}</p>)}</div></details>
 </div>}
 </div>}
 </div>
 <Dialog open={open} onClose={()=>{if(!busy)setOpen(false);}} title={preview?"确认二发任务卡":"创建二发任务"} description={preview?"核对以下内容，确认后自动采集线索、补全身份并准备商品材料。":"当前可用范围：BJN · 意大利。墨西哥和巴西准备接口继续接入。"} wide>
 {error&&<div className="mb-4"><Notice tone="warning">{error}</Notice></div>}
 {preview?<div className="space-y-5"><div className="grid grid-cols-2 gap-4 rounded-xl bg-gray-50 p-5 text-sm dark:bg-gray-800"><p>机构 / 市场：BJN / 意大利</p><p>目标：<strong>{preview.spec.target.toLocaleString()} 人</strong></p><p>候补：{preview.spec.reserve.toLocaleString()} 人</p><p>总准备：{(preview.spec.target+preview.spec.reserve).toLocaleString()} 人</p><p>开始日期：{preview.spec.startDate}</p><p>北京时间：{preview.spec.startTime}–{preview.spec.endTime}</p><p className="col-span-2 break-all">商品范围：{preview.spec.productScope.kind==="all_eligible"?"全部合格货盘":preview.spec.productScope.values.join("、")}</p></div><p className="text-sm leading-7 text-gray-600 dark:text-gray-300">同一达人本任务只选一款商品，完整卡文回查成功计 1 人。正式与候补整批备齐后才进入发送；不足保持等待。二发复用固定模板 v{preview.policy.templateVersion}，商品名按商品缓存。全托商品不要求库存数。</p><Notice>确认后会查询 Kalodata 和达人身份、按商品生成短名，并核验或创建已选／活动商品的 TapLink。本任务尚不发送消息；AI 回复继续暂停。</Notice><div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={()=>setPreview(null)}>返回修改</Button><Button disabled={busy} onClick={()=>void confirm()}>{busy?"正在保存…":"确认任务并开始准备"}</Button></div></div>:<form className="space-y-5" onSubmit={e=>{e.preventDefault();void review();}}><div className="grid gap-4 sm:grid-cols-2"><Field label="目标达人数量"><Input required type="number" min={1} max={100000} step={1} value={target} onChange={e=>setTarget(e.target.value)} placeholder="填写本次明确目标"/></Field><Field label="开始日期（北京时间）"><Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="每日开始时间"><Input required type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="每日截止时间" hint="可跨午夜；未完成目标保留至后续窗口。"><Input required type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Field label="商品范围"><Select value={scope} onChange={e=>setScope(e.target.value)}><option value="all_eligible">全部合格货盘</option><option value="pids">指定 PID</option><option value="categories">指定类目 ID</option><option value="campaigns">指定 Campaign ID</option></Select></Field>{scope!=="all_eligible"&&<Field label="范围列表" hint="用逗号或换行分隔；线索不足时不会自动扩大范围。"><TextArea required value={values} onChange={e=>setValues(e.target.value)}/></Field>}<div className="flex justify-end"><Button type="submit" disabled={busy}>{busy?"正在生成…":"生成任务卡"}</Button></div></form>}
 </Dialog>
 </Card>;
}
