"use client";
import {useEffect,useState} from "react";
import {Button,Card,Field,Icon,Select} from "../bdhub/ui";
import type {SecondTemplate,SecondTemplateBatch} from "./contracts";
export default function BatchTemplates({count,disabled,busy,result,onPrepare}:{count:number;disabled:boolean;busy:boolean;result:SecondTemplateBatch|null;onPrepare:(templateId:string)=>void}){
  const [templates,setTemplates]=useState<SecondTemplate[]>([]),[chosen,setChosen]=useState(""),[error,setError]=useState(false);
  useEffect(()=>{const controller=new AbortController();void(async()=>{try{const response=await fetch("/api/second-outreach?view=templates",{cache:"no-store",credentials:"same-origin",signal:controller.signal});const body=await response.json();if(!response.ok||!Array.isArray(body.templates))throw Error();if(!controller.signal.aborted){setTemplates(body.templates);setChosen(body.templates[0]?.id||"");}}catch{if(!controller.signal.aborted)setError(true);}})();return()=>controller.abort();},[]);
  return <Card className="mb-5" title="批量准备二发" subtitle="选一个固定模板，批量填入本页达人的称呼与商品；不调用模型、不发送。"><div className="space-y-3 p-5"><div className="flex flex-wrap items-end gap-3"><div className="min-w-56 flex-1"><Field label="本批使用模板"><Select value={chosen} disabled={disabled||busy||!templates.length} onChange={event=>setChosen(event.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.version}</option>)}</Select></Field></div><Button disabled={disabled||busy||!chosen||count===0} onClick={()=>onPrepare(chosen)}><Icon name="file" className="size-4"/>{busy?"正在准备…":`准备本页 ${count} 位`}</Button></div>{error&&<p className="text-xs text-gray-500">暂时无法读取模板，请刷新页面。</p>}{result&&<div role="status" className="rounded-xl bg-brand-25 p-3 text-xs leading-6 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300"><p>本批已准备 {result.prepared.length} 份 · 跳过 {result.skipped.length} 项 · 模型调用 0</p>{result.skipped.length>0&&<p>未准备项保留在原名单，原因包括暂停、身份待核验、收件人重复或商品推广理由尚未补齐。</p>}</div>}</div></Card>;
}
