"use client";
import {useEffect,useState} from "react";
import type {CycleStatus} from "../../server/second-cycle/bridge";
const labels:Record<string,string>={missing_stock:"缺库存",missing_creatorPercent:"缺达人佣金",missing_publicPercent:"缺公开佣金",missing_endAt:"缺活动有效期",missing_available:"缺可用状态",stock_not_over_100:"库存未超过100",expiry_not_over_45_days:"有效期未超过45天",no_creator_commission_advantage:"无达人佣金优势",unavailable:"商品不可用"};
export default function CycleSupplyPanel(){const [template,setTemplate]=useState("standard");const [data,setData]=useState<CycleStatus|null>(null),[error,setError]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch("/api/second-cycle",{signal:controller.signal,cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(v=>{if(!controller.signal.aborted)setData(v);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[]);
 return <section className="mb-5 rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900" aria-label="二发供给底座">
 <h2 className="text-base font-semibold text-gray-900 dark:text-white">二发供给 · 本地准备</h2>
 <p className="mt-1 text-sm text-gray-500">货盘与 Kalodata 持久采集已接入；当前为本地准备，旧试点控制与真实发送尚未接通。</p>
 {error?<p role="status" className="mt-3 text-sm">暂时无法读取供给状态，未启动任何操作。</p>:!data?<p role="status" className="mt-3 text-sm">正在读取供给状态…</p>:data.available===false?<p className="mt-3 text-sm">尚未导入本地供给资料。</p>:<>
 <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-gray-700 dark:text-gray-200"><span>货盘方案 <strong>{data.offerCount??data.offers?.length??0}</strong></span><span>条件合格方案 <strong>{data.eligibleOfferCount??0}</strong></span><span>稳定关系 <strong>{data.relationships}</strong></span><span>来源线索 <strong>{data.sourceEdges}</strong></span><span>达人×商品机会 <strong>{data.opportunities}</strong></span><span>条件齐全达人 <strong>{data.eligibleUniqueCreators}</strong></span></div>
 <div className="mt-3 text-sm text-gray-600 dark:text-gray-300">Kalodata 任务：排队 {data.jobs?.queued??0} · 处理中 {data.jobs?.running??0} · 已完成 {data.jobs?.completed??0} · 待处理异常 {data.jobs?.blocked??0}</div>
 <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">新采集线索身份：已关联 {data.identityResolvedEdges??0} / {data.identitySourceEdges??0} 条 · 未精确匹配 {data.identityUnmatchedEdges??0} 条（保留线索）。<a className="ml-2 text-brand-500" href="/creators?market=it">查看达人库</a></p>
 {data.sourceIssues?.map((issue,index)=><p key={index} role="status" className="mt-2 text-sm text-orange-700 dark:text-orange-300">{issue.code==="kalodata_auth_required"?"Kalodata 登录认证未通过，任务已停止；请通过原登录器更新会话。":"Kalodata 采集遇到异常，原任务与已有结果已保留。"} 查询窗口：{issue.window_start} — {issue.window_end}。</p>)}
 {data.reviewBatch&&<div className="mt-5 border-t border-gray-200 pt-4 dark:border-gray-800"><h3 className="text-sm font-semibold text-gray-900 dark:text-white">二发小批次 · 待核对</h3><p className="mt-1 text-xs text-gray-500">{data.reviewBatch.items.length} 位达人，各1张卡＋1条固定话术。{data.reviewBatch.expired?"此预览已过期，须重新核对。":"当前仅审阅，不发送。"}</p><p className="mt-2 text-sm text-orange-700 dark:text-orange-300">尚需接通 v4 执行校验，并核对消息余量与机构市场额度；平台权限字段不直接作为放行依据。</p><div className="mt-3 space-y-4">{data.reviewBatch.items.map(item=><article key={item.handle} className="border-l-2 border-gray-300 pl-3 dark:border-gray-700"><h4 className="text-sm font-medium text-gray-900 dark:text-white">@{item.handle} · {item.name.shortNameZh} · {item.offer.creatorPercent}%</h4><p className="mt-1 text-sm text-gray-700 dark:text-gray-200">{item.message.textIt}</p><details className="mt-2 text-xs text-gray-500"><summary className="cursor-pointer">关系与证据</summary><p>旧库记录：我方消息 {item.checks.legacy.localOutboundCount??"未知"} 条、达人回复 {item.checks.legacy.localReplyCount??"未知"} 条。无记录不代表平台无历史。</p><p>远端历史：{item.checks.remoteHistory?.status==="observed_summary"?`本次返回 ${item.checks.remoteHistory.history?.messageCount??0} 条记录，尚未据此计算消息余量`:item.checks.remoteHistory?.priorObservation?`此前读取到 ${item.checks.remoteHistory.priorObservation.history.messageCount} 条记录，当前待复核`:"尚未在有限查询范围定位，不能认定没有会话"}。</p>{item.checks.remoteHistory?.history?.senderCounts&&<p>本次平台记录分类：我方 {item.checks.remoteHistory.history.senderCounts.ourMessages} 条、达人回复 {item.checks.remoteHistory.history.senderCounts.creatorReplies} 条、加橱窗通知 {item.checks.remoteHistory.history.senderCounts.showcaseNotifications} 条、其他 {item.checks.remoteHistory.history.senderCounts.otherOrUnknown} 条。仅统计该会话返回页。</p>}{item.blockingReasons.some(reason=>["insufficient_locked_message_allowance","message_allowance_window_unverified"].includes(reason))&&<p className="font-medium text-orange-700 dark:text-orange-300">待核实本月消息额度：历史条数不是永久上限，平台额度会按月刷新；刷新起点尚未确认。{item.allowanceReview?.lastObservedOutboundAt&&` 此返回页最近一次我方消息：${item.allowanceReview.lastObservedOutboundAt.slice(0,10)}${item.allowanceReview.elapsedDaysSinceObservedOutbound!==null?`，已间隔 ${item.allowanceReview.elapsedDaysSinceObservedOutbound} 天`:""}。`}</p>}<p>旧库人工状态：{item.checks.legacy.manualState||"无记录"}。平台关系查询：{item.checks.platform.status==="observed"?"已取得信号，语义待核对":"未取得有效结果"}。</p><p>商品卡：{item.card.listId}；快照：{data.reviewBatch?.snapshotHash.slice(0,12)}。</p><p>{item.message.translationZh}</p></details></article>)}</div></div>}
 {Boolean(data.materials?.length)&&<div className="mt-5 border-t border-gray-200 pt-4 dark:border-gray-800"><h3 className="text-sm font-semibold text-gray-900 dark:text-white">商品准备 · v4 固定话术</h3><p className="mt-1 text-xs text-gray-500">短名称按商品缓存复用，名称模型已完成 {data.modelCalls??0} 次调用；达人话术直接填充。以下未发送，商品卡预检通过也需发送前再次核验。</p><label className="mt-3 block text-sm">预览模板 <select className="ml-2 rounded-lg border border-gray-300 bg-transparent p-2 dark:border-gray-700" value={template} onChange={e=>setTemplate(e.target.value)}><option value="standard">升佣复推</option><option value="brief">简短邀请</option><option value="video_live">视频与直播</option></select></label><div className="mt-3 space-y-4">{data.materials?.map(m=>{const draft=m.templates.find(t=>t.template===template);return <article key={m.pid} className="border-l-2 border-brand-500 pl-3"><h4 className="text-sm font-medium text-gray-900 dark:text-white">{m.name?.shortNameZh||"短名称待准备"} · {m.name?.shortNameIt||m.pid}</h4><p className="mt-1 text-xs text-gray-500">{m.card.state==="verified_read_only"?"已核验达人佣金":"拟给达人"} {m.creatorPercent}% · {m.card.state==="verified_read_only"?"商品卡预检通过":m.card.state==="needs_card_preparation"?"需准备匹配佣金的商品卡":m.card.state==="not_checked"?"商品卡待核验":"商品卡核验未完成"}{m.card.observedCreatorRates?.length?`（已见卡佣金 ${m.card.observedCreatorRates.join(" / ")}%）`:""}</p>{draft&&<><p className="mt-2 text-sm text-gray-700 dark:text-gray-200">{draft.textIt}</p><details className="mt-1 text-xs text-gray-500"><summary className="cursor-pointer">中文理解</summary>{draft.translationZh}</details></>}</article>})}</div></div>}
 <details className="mt-4 text-sm"><summary className="cursor-pointer text-brand-500">查看商品条件与待补信息</summary><ul className="mt-3 space-y-2 text-gray-600 dark:text-gray-300">{data.offers?.map((o,index)=><li key={`${o.offerKey||o.pid}-${index}`} className="break-words"><strong>{o.title||o.pid}</strong>（{o.catalogSource==="campaign"?"Campaign":o.catalogSource==="selected"?"已选商品":"历史源"}）：{o.assessment.eligible?"当前资料条件齐全，仍不代表可发送":o.assessment.reasons.map(r=>labels[r]||"资料需核对").join("、")}</li>)}</ul><p className="mt-3 text-xs text-gray-500">最多展示40条，优先已有线索商品。拟分配佣金不代表已建链；历史同品归属仍未核验。</p></details>
 </>}
 </section>;
}
