"use client";
import {useEffect,useState} from "react";
import type {ServiceCase,ServiceStatus} from "../../server/cycle-service/bridge";
const reasons:Record<string,string>={unsupported_input:"图片或暂不支持的输入",do_not_contact:"明确拒绝联系",link_issue:"链接问题",catalog_request:"更多商品目录",refund_sample:"退款或样品费用",multiple_requests:"多个诉求",unclassified:"需人工判断",boost_question:"Boost 问题"};
function Case({item,onChanged}:{item:ServiceCase;onChanged:()=>void}){const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const resolve=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/cycle-service",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"resolve",caseId:item.id,expectedRevision:item.assessment_revision,expectedControlRevision:item.control_revision,note})});if(!r.ok)throw Error();onChanged();}catch{setError("未确认处理结果，请刷新核对最新消息后重试。");}finally{setBusy(false);}};
 return <article className="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><h4 className="font-medium">{reasons[item.reason]||"待核对事项"}{item.overdue&&<span className="ml-2 text-orange-600">超过24小时</span>}</h4><p className="mt-1 text-xs text-gray-500">达人 {item.handle?`@${item.handle}`:item.creator_id.slice(-8)} · 确认句{item.ack_state==="confirmed"?"已确认送达":"等待发送或核验"}</p><div className="my-3 space-y-2">{item.messages.map(m=><p key={m.messageId} className="whitespace-pre-wrap break-words text-sm text-gray-700 dark:text-gray-200">{m.format==="text"?m.text:"[图片或附件：请在原会话查看]"}</p>)}</div><label className="block text-xs text-gray-500" htmlFor={item.id}>处理结果（必填）</label><textarea id={item.id} value={note} maxLength={4000} onChange={e=>setNote(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-transparent p-2 text-sm dark:border-gray-700" rows={2}/><button disabled={busy||!note.trim()} onClick={()=>void resolve()} className="mt-2 rounded-lg bg-brand-500 px-3 py-2 text-xs text-white disabled:opacity-40">{busy?"正在提交…":"已处理，交还自动处理"}</button>{error&&<p role="alert" className="mt-2 text-xs text-error-500">{error}</p>}</article>;
}
export default function CycleServicePanel(){const [data,setData]=useState<ServiceStatus|null>(null);const [error,setError]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;const poll=async()=>{try{const r=await fetch("/api/cycle-service",{cache:"no-store",signal:controller.signal});if(!r.ok)throw Error();const body=await r.json();if(!controller.signal.aborted){setData(body);setError(false);}}catch{if(!controller.signal.aborted)setError(true);}finally{if(!controller.signal.aborted)timer=setTimeout(poll,15000);}};void poll();return()=>{controller.abort();if(timer)clearTimeout(timer);};},[revision]);
 return <div className="mt-4 rounded-xl border border-gray-200 p-4 text-sm dark:border-gray-700"><h3 className="font-semibold text-gray-900 dark:text-white">达人咨询 · 人工接续</h3><p className="mt-1 text-xs text-gray-500">{data?.automaticReplies?"自动回复已启用：识别问题、核对事实后自动发送；历史补录不触发回复。":"自动回复已关闭，正文与待办仍保存在本机。"}</p>{error?<p className="mt-3 text-orange-600">暂时无法读取最新咨询状态。</p>:!data?<p className="mt-3 text-gray-500">正在读取…</p>:<><p className="mt-3 text-gray-600 dark:text-gray-300">已取得 {data.incomingContents??0} 条入站内容 · 已确认自动回复 {data.replyCounts?.confirmed??0} 条 · 待人工 {data.caseCount??0} 项</p>{data.pending?.needs_facts&&<p className="mt-2 text-orange-600">{data.pending.needs_facts} 位达人等待业务事实查询，尚未作答。</p>}{data.pending?.facts_ready_for_review&&<p className="mt-2 text-orange-600">{data.pending.facts_ready_for_review} 位达人的当前佣金事实已取得，等待后续处理。</p>}{data.pending?.policy_review&&<p className="mt-2 text-orange-600">{data.pending.policy_review} 位达人等待合作规则处理。</p>}<div className="mt-3 space-y-3">{data.cases.map(item=><Case key={`${item.id}-${item.assessment_revision}`} item={item} onChanged={()=>setRevision(r=>r+1)}/>)}</div>{data.cases.length===0&&<p className="mt-2 text-gray-500">当前没有未结人工事项。</p>}</>}</div>;
}
