"use client";
import {useEffect,useState} from "react";
import CycleServicePanel from "./CycleServicePanel";
import CycleSpeedPanel from "./CycleSpeedPanel";
import type {CycleStatus} from "../../server/second-cycle/bridge";
const stageNames:Record<string,string>={catalog_selected:"已选货盘刷新",catalog_campaign:"活动货盘刷新",kalodata:"Kalodata 线索补充",identity_reconcile:"身份回填",reply_facts:"咨询事实查询",materials_check:"商品素材与卡片准备"};
const labels:Record<string,string>={missing_stock:"缺库存",missing_creatorPercent:"缺达人佣金",missing_publicPercent:"缺公开佣金",missing_endAt:"缺活动有效期",missing_available:"缺可用状态",stock_not_over_100:"库存未超过100",expiry_not_over_45_days:"有效期未超过45天",no_creator_commission_advantage:"无达人佣金优势",unavailable:"商品不可用"};
export default function CycleSupplyPanel(){const [template,setTemplate]=useState("standard");const [data,setData]=useState<CycleStatus|null>(null),[error,setError]=useState(false);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;
 const poll=async()=>{try{const r=await fetch("/api/second-cycle",{signal:controller.signal,cache:"no-store"});if(!r.ok)throw new Error();const value=await r.json();if(!controller.signal.aborted){setData(value);setError(false);}}catch{if(!controller.signal.aborted)setError(true);}finally{if(!controller.signal.aborted)timer=setTimeout(poll,15000);}};
 void poll();return()=>{controller.abort();if(timer)clearTimeout(timer);};},[]);
 return <section className="mb-5 rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900" aria-label="二发供给底座">
 <h2 className="text-base font-semibold text-gray-900 dark:text-white">二发经营 · 运行状态</h2>
 <p className="mt-1 text-sm text-gray-500">查看当前实测批次、货盘供给和收信状态。</p>
 {error?<p role="status" className="mt-3 text-sm">暂时无法读取供给状态，未启动任何操作。</p>:!data?<p role="status" className="mt-3 text-sm">正在读取供给状态…</p>:data.available===false?<p className="mt-3 text-sm">尚未导入本地供给资料。</p>:<>
 <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-gray-700 dark:text-gray-200"><span>货盘方案 <strong>{data.offerCount??data.offers?.length??0}</strong></span><span>条件合格方案 <strong>{data.eligibleOfferCount??0}</strong></span><span>稳定关系 <strong>{data.relationships}</strong></span><span>来源线索 <strong>{data.sourceEdges}</strong></span><span>达人×商品机会 <strong>{data.opportunities}</strong></span><span>条件齐全达人 <strong>{data.eligibleUniqueCreators}</strong></span></div>
 <div className="mt-3 text-sm text-gray-600 dark:text-gray-300">Kalodata 任务：排队 {data.jobs?.queued??0} · 处理中 {data.jobs?.running??0} · 已完成 {data.jobs?.completed??0} · 待处理异常 {data.jobs?.blocked??0}</div>
 <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">新采集线索身份：已关联 {data.identityResolvedEdges??0} / {data.identitySourceEdges??0} 条 · 未精确匹配 {data.identityUnmatchedEdges??0} 条（保留线索）。<a className="ml-2 text-brand-500" href="/creators?market=it">查看达人库</a></p>
 {data.sourceIssues?.map((issue,index)=><p key={index} role="status" className="mt-2 text-sm text-orange-700 dark:text-orange-300">{issue.code==="kalodata_auth_required"?"Kalodata 登录认证未通过，任务已停止；请通过原登录器更新会话。":"Kalodata 采集遇到异常，原任务与已有结果已保留。"} 查询窗口：{issue.window_start} — {issue.window_end}。</p>)}
 {data.delivery?.bulk&&<div className="mt-4 rounded-xl bg-brand-50 p-4 dark:bg-brand-500/10"><h3 className="font-semibold text-brand-600 dark:text-brand-300">批量二发 · 本批目标 {data.delivery.bulk.target} 位</h3><div className="mt-3 flex flex-wrap gap-6 text-sm"><span>已确认 <strong>{data.delivery.bulk.counts.confirmed??0}</strong></span><span>发送中 <strong>{data.delivery.bulk.counts.sending??0}</strong></span><span>排队 <strong>{(data.delivery.bulk.counts.pending??0)+(data.delivery.bulk.counts.preparing??0)}</strong></span><span>需处理 <strong>{data.delivery.bulk.counts.needs_review??0}</strong></span></div><p className="mt-2 text-xs text-gray-500">{data.delivery.bulk.state==="waiting_supply"?"正在补充可发线索。 ":data.delivery.bulk.state==="waiting_reconciliation"?"正在等待回执核验。 ":data.delivery.bulk.state==="completed"?"本批已完成。 ":"正在逐项发送。 "}每人一张商品卡＋一条固定话术；已确认内容不重发。</p></div>}
 {data.speed&&<CycleSpeedPanel value={data.speed}/>}
 {data.delivery&&<div className="mt-4 rounded-xl border border-gray-200 p-4 text-sm dark:border-gray-700"><h3 className="font-semibold">二发执行进度</h3><p className="mt-1">待执行 {data.delivery.states.ready??0} 组 · 进行中 {data.delivery.states.running??0} 组 · 待核验 {data.delivery.states.unknown??0} 组 · 卡文全部确认 {data.delivery.states.confirmed??0} 组</p><p className="mt-1 text-xs text-gray-500">已确认组件 {data.delivery.confirmedParts} 条。待执行不代表已获发送确认；只有平台回查通过才计入完成。</p></div>}
 {Boolean(data.schedule?.length)&&<details className="mt-4 text-sm"><summary className="cursor-pointer font-medium">循环调度 · 供给维护</summary><ul className="mt-2 space-y-1 text-gray-600 dark:text-gray-300">{data.schedule?.map(s=><li key={s.stage}>{stageNames[s.stage]||s.stage}：{s.state==="running"?"执行中":s.state==="waiting"?"等待重试":"等待到期"}{s.finished?` · 上次处理 ${new Date(s.finished*1000).toLocaleString()}`:" · 尚未执行"}</li>)}</ul><p className="mt-2 text-xs text-gray-500">该调度器维护供给，不代表已开启批量发送；有效的待确认发送会暂缓供给刷新。</p></details>}
 {data.inbox&&<div className="mt-4 rounded-xl bg-gray-50 p-4 text-sm dark:bg-gray-800"><h3 className="font-semibold text-gray-900 dark:text-white">意大利收信 · 事件同步</h3><p className="mt-1 text-gray-600 dark:text-gray-300">已核验 {data.inbox.conversations} 个会话 · 已记录 {data.inbox.events} 条事件 · 历史补录 {data.inbox.historicalEvents} 条 · 待取内容 {data.inbox.pendingContent} 位达人</p><p className="mt-1 text-xs text-gray-500">仅轮询已索引且已关联二发关系的会话。旧消息不触发回复，新回复等待60秒合并；{data.inbox.automaticRepliesEnabled?"自动回复已开启。":"自动回复已关闭。"}</p>{data.inbox.gaps>0&&<p className="mt-1 text-orange-700">{data.inbox.gaps} 个会话存在历史缺口，需补回后处理。</p>}<p className="mt-1 text-xs text-gray-500">最近会话核验：{data.inbox.lastCheckedAt?new Date(data.inbox.lastCheckedAt*1000).toLocaleString():"尚未完成"}</p></div>}
 <CycleServicePanel/>
 {Boolean(data.materials?.length)&&<div className="mt-5 border-t border-gray-200 pt-4 dark:border-gray-800"><h3 className="text-sm font-semibold text-gray-900 dark:text-white">商品准备 · v4 固定话术</h3><p className="mt-1 text-xs text-gray-500">短名称按商品缓存复用，名称模型已完成 {data.modelCalls??0} 次调用；达人话术直接填充。以下未发送，商品卡预检通过也需发送前再次核验。</p><label className="mt-3 block text-sm">预览模板 <select className="ml-2 rounded-lg border border-gray-300 bg-transparent p-2 dark:border-gray-700" value={template} onChange={e=>setTemplate(e.target.value)}><option value="standard">升佣复推</option><option value="brief">简短邀请</option><option value="video_live">视频与直播</option></select></label><div className="mt-3 space-y-4">{data.materials?.map(m=>{const draft=m.templates.find(t=>t.template===template);return <article key={m.pid} className="border-l-2 border-brand-500 pl-3"><h4 className="text-sm font-medium text-gray-900 dark:text-white">{m.name?.shortNameZh||"短名称待准备"} · {m.name?.shortNameIt||m.pid}</h4><p className="mt-1 text-xs text-gray-500">{m.card.state==="verified_read_only"?"已核验达人佣金":"拟给达人"} {m.creatorPercent}% · {m.card.state==="verified_read_only"?"商品卡预检通过":m.card.state==="needs_card_preparation"?"需准备匹配佣金的商品卡":m.card.state==="not_checked"?"商品卡待核验":"商品卡核验未完成"}{m.card.observedCreatorRates?.length?`（已见卡佣金 ${m.card.observedCreatorRates.join(" / ")}%）`:""}</p>{draft&&<><p className="mt-2 text-sm text-gray-700 dark:text-gray-200">{draft.textIt}</p><details className="mt-1 text-xs text-gray-500"><summary className="cursor-pointer">中文理解</summary>{draft.translationZh}</details></>}</article>})}</div></div>}
 <details className="mt-4 text-sm"><summary className="cursor-pointer text-brand-500">查看商品条件与待补信息</summary><ul className="mt-3 space-y-2 text-gray-600 dark:text-gray-300">{data.offers?.map((o,index)=><li key={`${o.offerKey||o.pid}-${index}`} className="break-words"><strong>{o.title||o.pid}</strong>（{o.catalogSource==="campaign"?"Campaign":o.catalogSource==="selected"?"已选商品":"历史源"}）：{o.assessment.eligible?"当前资料条件齐全，仍不代表可发送":o.assessment.reasons.map(r=>labels[r]||"资料需核对").join("、")}</li>)}</ul><p className="mt-3 text-xs text-gray-500">最多展示40条，优先已有线索商品。拟分配佣金不代表已建链；历史同品归属仍未核验。</p></details>
 </>}
 </section>;
}
