import type {SpeedStatus} from "../../server/second-cycle/bridge";
const phases:Record<string,string>={planning:"选取线索",prepare:"核验材料",run:"发送与回查",waiting_supply:"补充线索中",cohort:"批次发送与回查"};
function SpeedCurve({value}:{value:SpeedStatus}) {
 const width=720,height=180,pad=32,series=value.buckets.map(b=>b.completed??b.contacts),top=Math.max(value.targetContactsPerMinute,...series,1);
 const x=(i:number)=>pad+i*(width-pad*2)/Math.max(1,series.length-1),y=(v:number)=>height-pad-v/top*(height-pad*2);
 const points=series.map((v,i)=>`${x(i)},${y(v)}`).join(" ");
 if(!series.length)return <p className="mt-4 text-sm text-gray-500">暂无速度样本</p>;
 const times=[0,Math.floor((series.length-1)/2),series.length-1].filter(i=>i>=0);
 return <div className="mt-4 rounded-lg bg-gray-50 p-2 dark:bg-gray-800"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="最近15分钟完整卡文确认速度曲线，虚线为每分钟20位目标" className="w-full">
 {[0,top/2,top].map(v=><g key={v}><line x1={pad} x2={width-pad} y1={y(v)} y2={y(v)} stroke="currentColor" className="text-gray-200 dark:text-gray-700"/><text x={pad-6} y={y(v)+4} textAnchor="end" fill="currentColor" className="text-gray-500" fontSize="10">{Number(v.toFixed(1))}</text></g>)}
 <line x1={pad} x2={width-pad} y1={y(value.targetContactsPerMinute)} y2={y(value.targetContactsPerMinute)} stroke="#9CA3AF" strokeDasharray="5 5"/>
 <polyline points={points} fill="none" stroke="#465FFF" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>
 {series.map((v,i)=><circle key={value.buckets[i].at} cx={x(i)} cy={y(v)} r="3" fill="#465FFF"><title>{new Date(value.buckets[i].at*1000).toLocaleTimeString("zh-CN",{timeZone:"Asia/Shanghai",hour:"2-digit",minute:"2-digit"})}：完整确认 {v} 位</title></circle>)}
 {times.map(i=><text key={i} x={x(i)} y={height-8} textAnchor="middle" fill="currentColor" className="text-gray-500" fontSize="10">{new Date(value.buckets[i].at*1000).toLocaleTimeString("zh-CN",{timeZone:"Asia/Shanghai",hour:"2-digit",minute:"2-digit"})}</text>)}
 </svg><p className="px-2 pb-1 text-xs text-gray-400">蓝线：每分钟完整确认人数 · 虚线：速度目标 · 北京时间，末点为当前未结束分钟</p></div>;
}
export default function CycleSpeedPanel({value}:{value:SpeedStatus}){return <div className="mt-4 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">发送速度监控</h3><span className="text-xs text-gray-500">{value.worker?.fresh?(phases[value.worker.phase]||"处理中"):"等待进程状态更新"}</span></div><p className="mt-2 text-sm text-gray-500">目标 {value.targetContactsPerMinute} 位/分钟 · 最近一分钟完整发送 {value.lastMinuteCompletedGroups} 位 · 卡片触达 {value.contactsPerMinute} 位/分钟</p><div className="mt-4 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["完整卡＋话术",`${value.completedGroupsPerMinute} 位/分钟`],["消息确认速度",`${value.messagesPerMinute} 条/分钟`],["速度目标达成",`${value.targetAttainmentPercent}%`],["未确认尝试",value.unconfirmedAttemptPercent===null?"暂无样本":`${value.unconfirmedAttemptPercent}%`]].map(([label,n])=><div key={label}><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-lg font-semibold text-gray-900 dark:text-white">{n}</p></div>)}</div><SpeedCurve value={value}/><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-gray-500"><span>设置的写入间隔：{value.policy?.send_interval??5} 秒</span><span>提速后卡→文字间隔：{value.optimizedCardToTextMedianSeconds===null?"采样中":`${value.optimizedCardToTextMedianSeconds} 秒中位数`}（{value.optimizedSamples} 组）</span>{value.stages.map(s=><span key={s.stage}>{s.stage.includes("prepare")?"材料准备":"发送执行"}成功平均 {s.averageSeconds??"暂无"} 秒（{s.failedOperations} 次操作未成功）</span>)}</div><p className="mt-2 text-xs text-gray-400">近15分钟平台明确拒绝 {value.nativeRejections} 次。完整发送速度按近5分钟卡＋话术全部回查成功计数；未确认尝试包括进行中与待核验，不等同失败。曲线按一分钟汇总。</p></div>;}
