export const REPLY_ACTIONS=["no_reply","sample_self_service","collaboration_ack","link_usage","human"] as const;
export type ReplyAction=typeof REPLY_ACTIONS[number];
export type ReplyDecision={action:ReplyAction;intentCode:string;evidenceMessageIds:string[];
 evidenceQuotes:string[];confidence:number;humanReason:string|null;templateKey:string|null;
 meaningZh:string;relatedEpisodeIds:string[];templateText:string|null;provider:string;model:string;
 policyVersion:string;automaticReply:false;executionAllowed:false};
export type ReplyReviewState={turn_id:string;revision:number;correct_action:ReplyAction;
 note:string;created_at:number};
export const initialReviewAction=(review:ReplyReviewState|null):ReplyAction|""=>review?.correct_action??"";
export type ReplyReviewItem={turnId:string;messageId:string;creatorId:string;format:string;text:string|null;
 historical:boolean;occurredMs:number|null;episodes:Array<{episode_id:string;pid:string;list_id:string;
 candidate_rank:number;confidence:string}>;classificationId:string|null;decision:ReplyDecision|null;
 review:ReplyReviewState|null;comparisons:Array<{classificationId:string;provider:string;model:string;
 action:ReplyAction;confidence:number;intentCode:string;decision:ReplyDecision}>;
 operational:{applicable:boolean;reason:string|null;controlRevision:number|null;pendingRevision:number|null;
  pendingState:string|null;application:{turnId:string;action:ReplyAction;reviewRevision:number;state:string;
   automaticReply:false;platformWrites:number;caseId?:string;candidateId?:string;templateKey?:string}|null}};
export type ReplyReviewStatus={schema:"bdhub.reply-review.v1";policyVersion:string;
 processingIntervalSeconds:number;automaticReplies:false;providers:{deepseek:{mode:string};jev:{mode:string}};
 templates:Partial<Record<ReplyAction,{key:string;text:string}>>;
 counts:{turns:number;episodes:number;linkedTurns:number;classified:number;reviewed:number};
 evaluation:{paired:number;agreements:number;disagreements:number;agreementRate:number|null;
  reviewedTurns:number;pendingReview:number;providers:Record<"deepseek"|"jev",{evaluated:number;
   correct:number;accuracy:number|null;falseAuto:number;falseHuman:number}>;
  disagreementSamples:Array<{turnId:string;deepseek:ReplyAction;jev:ReplyAction;agree:boolean}>};
 items:ReplyReviewItem[]};
