"use client";

import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import TrialPanel from "./TrialPanel";
import CycleSupplyPanel from "./CycleSupplyPanel";
import {Button,Card,EmptyState,Icon,Input,Notice,PageHeading,Pill,Select} from "../bdhub/ui";
import TemplatePanel from "./TemplatePanel";
import BatchTemplates from "./BatchTemplates";
import CreatorDraftHistory from "../outreach-drafts/CreatorDraftHistory";
import type {SecondOpportunity,SecondOutreachList,SecondOutreachStatus,SecondPreparedPacket,SecondProduct,SecondTemplateDraft,SecondTemplateBatch} from "./contracts";

const API="/api/second-outreach",PENDING_KEY="bdhub-second-outreach-pending-v1",PAGE_SIZE=10;
type Filter="all"|"identified"|"unresolved";
type SourceOpportunity=SecondOpportunity&{recipientStatus?:"verified"|"unresolved"|"ambiguous";omittedProducts?:number};
function recipientState(value:SecondOpportunity){return (value as SourceOpportunity).recipientStatus||(value.currentRecipient?"verified":"unresolved");}
type Command={type:"render_batch";opportunityIds:string[];templateId:string;expectedSourceFingerprint:string}|{type:"render_template";opportunityId:string;expectedRevision:number;templateId:string}|{type:"refresh"}|{type:"prepare";opportunityId:string;expectedRevision:number}|{type:"control";opportunityId:string;expectedRevision:number;control:"active"|"paused"};
type Request={requestId:string;command:Command};
type Result=SecondOutreachStatus|SecondOpportunity|SecondPreparedPacket|SecondTemplateDraft|SecondTemplateBatch;
function templateBatch(value:unknown):value is SecondTemplateBatch {return object(value)&&typeof value.batchId==="string"&&Array.isArray(value.prepared)&&value.prepared.every(templateDraft)&&Array.isArray(value.skipped)&&value.modelCalls===0;}
function templateDraft(value:unknown):value is SecondTemplateDraft {return object(value)&&typeof value.draftId==="string"&&typeof value.opportunityId==="string"&&typeof value.textIt==="string"&&value.executionBlocked===true;}
type ActionError={message:string;code:string};
const transportReasons:Record<string,string>={account_not_startable:"当前账号暂不可用于意大利消息传输。",account_unavailable:"当前账号暂不可用。",authentication_required:"账号需要完成登录鉴权。",auth_expired:"账号的登录状态已过期。",session_expired:"账号的登录状态已过期。",unsupported_market:"意大利消息能力尚未完成核对。",verification_required:"平台验证尚未完成。",request_timeout:"本次鉴权请求超时。",network_error:"本次鉴权连接未完成。",not_configured:"传输账号尚未完成配置。",account_busy:"传输账号正在使用中。",send_not_authorized:"本次真实发送范围尚未确认。"};
function handle(value:string){return `@${value.replace(/^@+/,"")}`;}
function date(value:string|null){if(!value)return "尚无记录";const time=Date.parse(value);return Number.isFinite(time)?new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Shanghai"}).format(time):"时间未记录";}
function day(value:number){return Number.isFinite(value)&&value>0?new Date(value).toISOString().slice(0,10):"未记录";}
function object(value:unknown):value is Record<string,unknown>{return Boolean(value&&typeof value==="object"&&!Array.isArray(value));}
function opportunity(value:unknown):value is SecondOpportunity {
  if(!object(value))return false;const row=value as unknown as SecondOpportunity;
  return typeof row.id==="string"&&typeof row.sourceHandle==="string"&&row.sourceNamespace==="kalodata"&&Number.isSafeInteger(row.revision)&&row.revision>0&&typeof row.fingerprint==="string"&&["active","paused"].includes(row.control)&&row.historicalOwnership==="unverified"&&Array.isArray(row.products)&&row.products.every(product=>typeof product.id==="string"&&typeof product.title==="string"&&Number.isFinite(product.units))&&(row.currentRecipient===null||Boolean(row.currentRecipient&&typeof row.currentRecipient.creatorId==="string"&&typeof row.currentRecipient.oecId==="string"&&(row.currentRecipient.handle===null||typeof row.currentRecipient.handle==="string")));
}
function status(value:unknown):value is SecondOutreachStatus {if(!object(value))return false;const row=value as unknown as SecondOutreachStatus;return row.market==="it"&&[row.opportunities,row.identified,row.unresolved,row.products,row.edges,row.paused,row.realSends,row.resultUnknown].every(value=>Number.isSafeInteger(value)&&value>=0)&&Boolean(row.transport&&["not_tested","auth_verified","blocked"].includes(row.transport.state)&&row.transport.sendEnabled===false);}
function packet(value:unknown):value is SecondPreparedPacket {if(!object(value))return false;const row=value as unknown as SecondPreparedPacket;return typeof row.packetId==="string"&&row.packetId.startsWith("second-packet-")&&typeof row.opportunityId==="string"&&typeof row.sourceFingerprint==="string"&&typeof row.createdAt==="string"&&row.executionBlocked===true;}
function pendingRequest(value:unknown):value is Request {if(!object(value)||typeof value.requestId!=="string"||!object(value.command))return false;const command=value.command;return command.type==="refresh"||command.type==="render_batch"&&Array.isArray(command.opportunityIds)&&command.opportunityIds.every(id=>typeof id==="string")&&typeof command.templateId==="string"&&typeof command.expectedSourceFingerprint==="string"||["prepare","control","render_template"].includes(String(command.type))&&typeof command.opportunityId==="string"&&Number.isSafeInteger(command.expectedRevision)&&Number(command.expectedRevision)>0&&(command.type!=="control"||["active","paused"].includes(String(command.control)))&&(command.type!=="render_template"||typeof command.templateId==="string");}
function errorMessage(value:unknown,fallback:string){return object(value)&&object(value.error)&&typeof value.error.message==="string"?value.error.message:fallback;}

function useCommands(onConfirmed:(value:Result,request:Request)=>void,onReload:()=>void){
  const [busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState<ActionError|null>(null),[pending,setPending]=useState<Request|null>(null),[storageError,setStorageError]=useState(false);
  const mounted=useRef(false),writing=useRef(false),pendingRef=useRef<Request|null>(null),callback=useRef(onConfirmed),reload=useRef(onReload),controller=useRef<AbortController|null>(null);callback.current=onConfirmed;reload.current=onReload;
  useEffect(()=>{mounted.current=true;try{const raw=sessionStorage.getItem(PENDING_KEY);if(raw){const saved:unknown=JSON.parse(raw);if(!pendingRequest(saved))throw new Error();pendingRef.current=saved;setPending(saved);setError({code:"request_unconfirmed",message:"上次操作结果尚未确认，请恢复原请求。"});}setReady(true);}catch{setStorageError(true);setError({code:"storage_unavailable",message:"无法恢复请求编号，请检查浏览器会话存储后刷新。"});}return()=>{mounted.current=false;controller.current?.abort();};},[]);
  const execute=useCallback(async(input:Request)=>{
    if(writing.current||(pendingRef.current&&pendingRef.current.requestId!==input.requestId))return;
    try{sessionStorage.setItem(PENDING_KEY,JSON.stringify(input));}catch{setStorageError(true);setError({code:"storage_unavailable",message:"无法保存请求编号，本次未提交。"});return;}
    writing.current=true;pendingRef.current=input;setPending(input);setBusy(true);setError(null);const current=new AbortController();controller.current=current;const timer=window.setTimeout(()=>current.abort(),20000);
    const clear=()=>{try{sessionStorage.removeItem(PENDING_KEY);}catch{}pendingRef.current=null;setPending(null);};
    try{
      const response=await fetch(API,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(input),signal:current.signal});const body:unknown=await response.json();if(!mounted.current)return;
      if(!response.ok){const definitive=[400,403,404,409,413,415,422].includes(response.status);if(definitive){clear();reload.current();}setError({code:object(body)&&object(body.error)&&typeof body.error.code==="string"?body.error.code:"request_unconfirmed",message:errorMessage(body,"操作结果尚未确认，请恢复原请求。")});return;}
      const valid=input.command.type==="render_batch"?templateBatch(body):input.command.type==="refresh"?status(body):input.command.type==="render_template"?templateDraft(body)&&body.opportunityId===input.command.opportunityId:input.command.type==="prepare"?packet(body)&&body.opportunityId===input.command.opportunityId:opportunity(body)&&body.id===input.command.opportunityId;
      if(!valid)throw new Error("unconfirmed");clear();callback.current(body as Result,input);
    }catch{if(mounted.current)setError({code:"request_unconfirmed",message:"连接中断，操作结果尚未确认。恢复会沿用原请求编号。"});}
    finally{window.clearTimeout(timer);writing.current=false;if(mounted.current)setBusy(false);}
  },[]);
  return {busy,error,pending,blocked:!ready||busy||Boolean(pending)||storageError,submit:(command:Command)=>{if(ready&&!storageError&&!writing.current&&!pendingRef.current)void execute({requestId:crypto.randomUUID(),command});},retry:()=>{if(pendingRef.current)void execute(pendingRef.current);},dismiss:()=>{if(!pendingRef.current&&!storageError)setError(null);}};
}

function TransportStatus({value}:{value:SecondOutreachStatus|null}){
  const transport=value?.transport,verified=transport?.state==="auth_verified";
  const explanation=transport?.reason?transportReasons[transport.reason]||(/[\u4e00-\u9fff]/.test(transport.reason)?transport.reason:"本次鉴权尚未完成，可展开检查记录查看原因。"):verified?"当前账号已通过传输鉴权检查，实际发送尚未开放。":transport?.state==="blocked"?"当前传输鉴权尚未通过。":"尚未完成意大利消息传输鉴权检查。";
  return <section id="second-outreach-status" className="mb-6 scroll-mt-24 rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.025] sm:p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-gray-100 text-gray-500 dark:bg-gray-800"><Icon name="chat"/></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold text-gray-800 dark:text-gray-200">TikTok IM · 意大利</h2><Pill tone={verified?"brand":transport?.state==="blocked"?"warning":"neutral"}>{verified?"鉴权已核验":transport?.state==="blocked"?"鉴权待处理":"鉴权待核验"}</Pill></div><p className="mt-2 max-w-2xl text-xs leading-5 text-gray-500">{explanation}</p><details className="mt-2 text-xs text-gray-400"><summary className="cursor-pointer py-1">查看检查与交付记录</summary><p className="mt-1 leading-5">检查于 {date(transport?.observedAt||null)}（北京时间）</p>{transport?.reason&&<p className="break-all leading-5">原因：{transport.reason}</p>}<p className="leading-5">真实发送 {value?.realSends??"—"} · 结果未知 {value?.resultUnknown??"—"}</p></details></div></div><div className="flex flex-col items-start gap-2 sm:items-end"><Button size="sm" variant="outline" disabled><Icon name="lock" className="size-4"/>真实发送未开放</Button><span className="text-[11px] text-gray-400">鉴权记录与发送权限分别核对</span></div></div></section>;
}
function ProductEvidence({product}:{product:SecondProduct}){
  return <article className="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><h3 className="text-sm font-medium leading-6 text-gray-800 dark:text-gray-200">{product.title}</h3><p lang="it" className="mt-1 text-xs leading-5 text-gray-500">{product.nameIt}</p></div><span className="rounded-lg bg-gray-50 px-3 py-2 text-right dark:bg-gray-800/50"><span className="block text-[10px] text-gray-400">来源销量</span><span className="mt-1 block text-sm font-semibold text-gray-700 dark:text-gray-200">{product.units.toLocaleString("zh-CN")} 件</span></span></div><p className="mt-3 text-xs text-gray-500">{day(product.windowStart)} — {day(product.windowEnd)} · 来源统计窗口</p><details className="mt-2 text-xs text-gray-400"><summary className="cursor-pointer py-1">查看商品与来源</summary><p className="mt-1 break-all leading-5">PID {product.pid}</p><p className="break-all leading-5">{product.sourceRef}</p></details></article>;
}

export default function SecondOutreachWorkspace(){
  const router=useRouter(),params=useSearchParams();
  const [selectedId,setSelectedId]=useState(params.get("opportunityId")||""),[detail,setDetail]=useState<SecondOpportunity|null>(null),[page,setPage]=useState<{key:string;value:SecondOutreachList}|null>(null),[summary,setSummary]=useState<SecondOutreachStatus|null>(null),[filter,setFilter]=useState<Filter>("all"),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true),[readError,setReadError]=useState(""),[notice,setNotice]=useState(""),[batchResult,setBatchResult]=useState<SecondTemplateBatch|null>(null);
  const sequence=useRef(0),selectedRef=useRef(selectedId),searchRef=useRef(search),draftRef=useRef<HTMLElement|null>(null);selectedRef.current=selectedId;searchRef.current=search;
  const listKey=`${filter}|${query}|${offset}`;
  const reload=useCallback(()=>setRefresh(value=>value+1),[]);
  const confirm=useCallback((value:Result,input:Request)=>{if(input.command.type==="render_batch"&&templateBatch(value)){setBatchResult(value);setNotice(`本批准备 ${value.prepared.length} 份模板稿，未调用模型，未发送。`);}else if(input.command.type==="refresh"&&status(value)){setSummary(value);setNotice("本机线索已同步，当前名单与来源版本已更新。");}else if(input.command.type==="render_template"&&templateDraft(value)){setNotice("固定模板稿已保存，未调用模型，也未发送消息。");}else if(input.command.type==="control"&&opportunity(value)){if(selectedRef.current===value.id)setDetail(value);setNotice(value.control==="paused"?"当前机会已暂停。":"当前机会已恢复，按最新资料继续处理。");}setRefresh(version=>version+1);},[]);
  const commands=useCommands(confirm,reload);
  const choose=useCallback((id:string)=>{setSelectedId(id);setNotice("");const url=new URL(window.location.href);if((url.searchParams.get("opportunityId")||"")===id)return;url.searchParams.set("mode","second-live");if(id)url.searchParams.set("opportunityId",id);else url.searchParams.delete("opportunityId");router.replace(`${url.pathname}${url.search}`,{scroll:false});},[router]);
  useEffect(()=>{const fromUrl=params.get("opportunityId")||"";setSelectedId(fromUrl);},[params]);
  useEffect(()=>{const timer=window.setTimeout(()=>setQuery(search.trim()),250);return()=>window.clearTimeout(timer);},[search]);
  useEffect(()=>{
    const controller=new AbortController(),generation=++sequence.current;let reading=false;setLoading(true);
    const get=async(url:string)=>{const response=await fetch(url,{credentials:"same-origin",cache:"no-store",signal:controller.signal});let value:unknown;try{value=await response.json();}catch{throw new Error("二发服务暂未返回资料，请重新读取。");}if(!response.ok)throw new Error(errorMessage(value,"暂时无法读取二发资料。"));return value;};
    const read=async()=>{if(reading||document.visibilityState!=="visible")return;reading=true;try{
      const [statusResult,listResult,detailResult]=await Promise.allSettled([get(`${API}?view=status`),get(`${API}?view=list&offset=${offset}&limit=${PAGE_SIZE}&filter=${filter}&q=${encodeURIComponent(query)}`),selectedId?get(`${API}?view=opportunity&id=${encodeURIComponent(selectedId)}`):Promise.resolve(null)]);
      if(controller.signal.aborted||generation!==sequence.current)return;
      const errors:string[]=[];
      if(statusResult.status==="fulfilled"&&status(statusResult.value))setSummary(statusResult.value);else errors.push(statusResult.status==="rejected"&&statusResult.reason instanceof Error?statusResult.reason.message:"二发状态响应不完整。");
      const list=listResult.status==="fulfilled"?listResult.value as SecondOutreachList:null;
      if(list&&Array.isArray(list.items)&&list.items.every(opportunity)&&typeof list.total==="number"){setPage({key:listKey,value:list});if(!selectedId&&searchRef.current.trim()===query&&list.items.length)choose(list.items[0].id);}else errors.push(listResult.status==="rejected"&&listResult.reason instanceof Error?listResult.reason.message:"二发名单响应不完整。");
      if(detailResult.status==="fulfilled"&&(detailResult.value===null||opportunity(detailResult.value)&&detailResult.value.id===selectedId))setDetail(detailResult.value as SecondOpportunity|null);else{setDetail(null);errors.push(detailResult.status==="rejected"&&detailResult.reason instanceof Error?detailResult.reason.message:"所选机会响应不完整。");}
      setReadError([...new Set(errors)].join(" "));
    }catch(failure){if(!controller.signal.aborted&&generation===sequence.current)setReadError(failure instanceof Error?failure.message:"无法读取本机二发资料。");}finally{reading=false;if(!controller.signal.aborted&&generation===sequence.current)setLoading(false);}};
    void read();const timer=window.setInterval(()=>void read(),5000),visible=()=>void read();document.addEventListener("visibilitychange",visible);return()=>{controller.abort();window.clearInterval(timer);document.removeEventListener("visibilitychange",visible);};
  },[selectedId,filter,query,offset,listKey,refresh,choose]);
  const current=detail?.id===selectedId?detail:null,rows=page?.key===listKey&&search.trim()===query?page.value:null;
  const locked=commands.blocked||Boolean(readError)||!current;
  const prepare=()=>draftRef.current?.scrollIntoView({behavior:"smooth",block:"start"});

  return <div className="min-w-0"><PageHeading title="意大利二发" description="按达人归并同品机会，核对当前身份，再准备一份清楚的合作邀约。" action={<div className="flex flex-wrap items-center gap-2"><Link href="/workspace?mode=second" className="rounded-lg px-3 py-2.5 text-xs font-medium text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800">查看旧版预演</Link><Button variant="outline" disabled={commands.blocked} onClick={()=>commands.submit({type:"refresh"})}><Icon name="arrow" className="size-4"/>{commands.busy?"正在处理…":"同步本机线索"}</Button></div>}/>
    <CycleSupplyPanel/>
    {params.get("trialId")&&<TrialPanel key={params.get("trialId")!} trialId={params.get("trialId")!}/>}
    <Card className="mb-5"><div className="grid grid-cols-2 gap-5 p-5 sm:grid-cols-4">{[["达人机会",summary?.opportunities,"按人归并商品"],["当前身份已确认",summary?.identified,"已有稳定 OEC"],["身份待确认",summary?.unresolved,"保留来源线索"],["同品证据",summary?.edges,summary?`${summary.products} 个来源商品`:"读取来源商品"]].map(([label,value,note])=><div key={String(label)} className="min-w-0"><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-gray-800 dark:text-gray-100">{value===undefined?"—":Number(value).toLocaleString("zh-CN")}</p><p className="mt-1 text-[11px] text-gray-400">{note}</p></div>)}</div></Card>
    <TransportStatus value={summary}/>
    <details className="mb-5 text-sm"><summary className="cursor-pointer text-gray-500">旧版 v3 试点模板（仅历史参考）</summary><BatchTemplates count={rows?.items.length||0} disabled={true} busy={commands.busy} result={batchResult} onPrepare={templateId=>{if(rows&&summary?.sourceFingerprint)commands.submit({type:"render_batch",opportunityIds:rows.items.map(item=>item.id),templateId,expectedSourceFingerprint:summary.sourceFingerprint});}}/></details>
    {readError&&<div className="mb-5"><Notice tone="warning"><p>{readError}</p><Button className="mt-2" size="sm" variant="outline" onClick={reload}>重新读取</Button></Notice></div>}
    {commands.error&&<div className="mb-5" role="alert"><Notice tone="warning"><p>{commands.error.message}</p>{commands.pending?<Button className="mt-3" size="sm" variant="outline" disabled={commands.busy} onClick={commands.retry}>{commands.busy?"正在恢复…":"恢复原操作"}</Button>:commands.error.code!=="storage_unavailable"&&<Button className="mt-2" size="sm" variant="ghost" onClick={commands.dismiss}>知道了</Button>}</Notice></div>}
    {notice&&<p role="status" className="mb-5 text-sm text-brand-500">{notice}</p>}
    <div className="grid items-start gap-5 lg:grid-cols-[300px_minmax(0,1fr)] xl:grid-cols-[340px_minmax(0,1fr)]"><div className="min-w-0 space-y-4"><Card title="达人机会" subtitle="同一来源达人、多件商品集中处理。"><div className="space-y-3 p-4"><div className="relative"><Icon name="search" className="pointer-events-none absolute left-3 top-3.5 size-4 text-gray-400"/><Input aria-label="搜索二发达人" value={search} maxLength={100} onChange={event=>{setSearch(event.target.value);setOffset(0);choose("");}} placeholder="搜索达人名称或商品" className="!pl-9"/></div><Select aria-label="筛选收件身份" value={filter} onChange={event=>{setFilter(event.target.value as Filter);setOffset(0);choose("");}}><option value="all">全部机会</option><option value="identified">当前身份已确认</option><option value="unresolved">身份待确认</option></Select><div aria-busy={loading} className="space-y-2">{!rows?<p className="py-8 text-center text-xs text-gray-400">正在读取名单…</p>:!rows.items.length?<p className="py-8 text-center text-xs leading-6 text-gray-500">没有符合条件的线索。{!summary?.opportunities&&"可先同步本机来源。"}</p>:rows.items.map(item=><button key={item.id} type="button" aria-pressed={selectedId===item.id} onClick={()=>choose(item.id)} className={`block w-full rounded-xl border p-3 text-left transition ${selectedId===item.id?"border-brand-200 bg-brand-25 dark:border-brand-800 dark:bg-brand-500/10":"border-transparent hover:bg-gray-50 dark:hover:bg-gray-800/40"}`}><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-gray-100 text-sm font-medium text-gray-500 dark:bg-gray-800">{(item.currentRecipient?.handle||item.sourceHandle).replace(/^@/,"").slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="break-all text-sm font-medium text-gray-800 dark:text-gray-200">{handle(item.sourceHandle)}</p><p className="mt-1 text-xs text-gray-400">{item.products.length} 件商品 · {item.currentRecipient?"当前身份已确认":recipientState(item)==="ambiguous"?"身份有多项记录":"待解析身份"}</p></div>{item.control==="paused"&&<Icon name="time" className="mt-1 size-4 text-gray-400"/>}</div></button>)}</div>{rows&&rows.total>0&&<div className="flex items-center justify-between gap-2 border-t border-gray-100 pt-3 text-xs text-gray-400 dark:border-gray-800"><span>{offset+1}–{Math.min(offset+PAGE_SIZE,rows.total)} / {rows.total}</span><div className="flex gap-1"><Button size="sm" variant="ghost" className="!px-2" disabled={offset===0||loading} onClick={()=>{setOffset(value=>Math.max(0,value-PAGE_SIZE));choose("");}}>上页</Button><Button size="sm" variant="ghost" className="!px-2" disabled={loading||offset+PAGE_SIZE>=rows.total} onClick={()=>{setOffset(value=>value+PAGE_SIZE);choose("");}}>下页</Button></div></div>}</div></Card><p className="px-1 text-[11px] leading-5 text-gray-400">来源更新于 {date(summary?.updatedAt||null)}（北京时间） · 暂停 {summary?.paused??"—"} 项</p></div>
    <div className="min-w-0 space-y-5">{!current?<Card><EmptyState title={loading?"正在读取机会资料…":"选择一位达人"} description="查看当前收件身份、来源商品与已保存草稿。"/></Card>:<>
      <Card><div className="space-y-5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="break-all text-lg font-semibold text-gray-800 dark:text-gray-100">{handle(current.sourceHandle)}</h2><Pill tone={current.control==="paused"?"neutral":"brand"}>{current.control==="paused"?"当前机会已暂停":"可准备模板"}</Pill></div><p className="mt-1 text-xs text-gray-400">来源名称 · {current.products.length} 件同品机会</p></div><Button size="sm" variant="outline" disabled={locked} onClick={()=>commands.submit({type:"control",opportunityId:current.id,expectedRevision:current.revision,control:current.control==="paused"?"active":"paused"})}>{current.control==="paused"?"恢复此机会":"暂停此机会"}</Button></div>
        <div className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800/40"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-medium text-gray-500">当前平台收件身份</p><Pill tone={current.currentRecipient?"brand":"neutral"}>{current.currentRecipient?"稳定身份已记录":recipientState(current)==="ambiguous"?"身份待核对":"等待解析"}</Pill></div>{current.currentRecipient?<><p className="mt-3 break-all text-base font-semibold text-gray-800 dark:text-gray-200">{current.currentRecipient.handle?handle(current.currentRecipient.handle):"平台本次未返回名字"}</p><p className="mt-2 break-all font-mono text-xs text-gray-500">OECID {current.currentRecipient.oecId}</p><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-gray-400">核验于 {date(current.currentRecipient.observedAt)}（北京时间）</span><Link href={`/creators?market=it&creatorId=${encodeURIComponent(current.currentRecipient.creatorId)}`} className="text-xs font-medium text-brand-500">打开稳定档案 →</Link></div></>:<div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs leading-5 text-gray-500">{recipientState(current)==="ambiguous"?"此来源对应多项身份记录，暂未指定收件人。":"来源线索保留，取得精确 OEC 后可准备邀约。"}</p><Link href={`/creators?market=it${recipientState(current)==="ambiguous"?"":"&status=pending"}&q=${encodeURIComponent(current.sourceHandle.replace(/^@/,""))}`} className="text-xs font-medium text-brand-500">{recipientState(current)==="ambiguous"?"查看身份记录":"查看待解析线索"} →</Link></div>}</div>
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 pt-4 dark:border-gray-800"><p className="max-w-lg text-xs leading-5 text-gray-500">同品记录的历史归属尚未核验，邀约使用当前身份与商品资料。</p><Button size="sm" disabled={locked||!current.currentRecipient||current.control==="paused"} onClick={prepare}><Icon name="file" className="size-4"/>选择二发模板</Button></div>
      </div></Card>
      <Card title="来源同品记录" subtitle="保留原名单的商品观测与统计窗口。"><div className="grid gap-3 p-4 sm:p-5 xl:grid-cols-2">{current.products.map(product=><ProductEvidence key={product.id} product={product}/>)}</div>{Boolean((current as SourceOpportunity).omittedProducts)&&<p className="px-5 pb-4 text-xs text-gray-500">另有 {(current as SourceOpportunity).omittedProducts} 件来源商品未纳入本轮资料包。</p>}</Card>
      <section ref={draftRef} className="scroll-mt-24"><details><summary className="cursor-pointer text-sm text-gray-500">查看原试点模板记录</summary><TemplatePanel key={current.id} opportunity={current} disabled={true} busy={commands.busy} onRender={templateId=>commands.submit({type:"render_template",opportunityId:current.id,expectedRevision:current.revision,templateId})}/></details></section>
      {current.currentRecipient&&<details className="px-1 text-xs text-gray-400"><summary className="cursor-pointer py-1">早期 AI 实验记录（仅历史查看）</summary><div className="mt-3"><CreatorDraftHistory key={current.currentRecipient.creatorId} creatorId={current.currentRecipient.creatorId}/></div></details>}
      <details className="px-1 text-xs text-gray-400"><summary className="cursor-pointer py-1">机会来源与版本</summary><p className="mt-2 break-all leading-5">来源 {current.sourceNamespace} · {current.sourceExternalId}</p><p className="break-all leading-5">机会 {current.id} · v{current.revision}</p><p className="break-all leading-5">{current.fingerprint}</p></details>
    </>}</div></div>
  </div>;
}
