"use client";
import {useEffect,useMemo,useState} from "react";
import {Button,Card,Dialog,Input,Notice,Pill,TextArea} from "../bdhub/ui";
import type {SendTemplate,TemplateLibraryState} from "../../server/template-library/bridge";
import type {SendController} from "./useSendBatch";

const DEFAULT_BODY="Ciao @{creator_handle}! Per {product_name} abbiamo una commissione del {creator_commission}% per te 👏 Ti va di creare un nuovo video o LIVE?";
const renderSample=(body:string)=>body.replaceAll("{creator_handle}","creator_demo").replaceAll("{product_name}","questo prodotto").replaceAll("{creator_commission}","13");

export default function SendTemplateManager({market,controller}:{market:string;controller:SendController}){
 const {data:send,draft,setDraft,busy,reload}=controller;
 const [library,setLibrary]=useState<TemplateLibraryState|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState(send?.control.template??"standard"),[open,setOpen]=useState(false),[name,setName]=useState(""),[body,setBody]=useState(DEFAULT_BODY),[editing,setEditing]=useState<SendTemplate|null>(null),[deleting,setDeleting]=useState<SendTemplate|null>(null),[saving,setSaving]=useState(false),[translation,setTranslation]=useState(""),[translating,setTranslating]=useState(false);
 const load=async()=>{const response=await fetch(`/api/template-library?market=${encodeURIComponent(market)}`,{cache:"no-store"}).catch(()=>null);if(!response?.ok){setError("暂时无法读取模板库。");return;}setLibrary(await response.json());setError("");};
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(send?.control.template)setSelected(send.control.template);},[send?.control.template]);
 useEffect(()=>setTranslation(""),[selected]);
 const templates=library?.sendTemplates??send?.templates??[];
 const current=useMemo(()=>templates.find(item=>item.id===selected)??null,[templates,selected]);
 const currentReview=library?.review.items.find(item=>item.templateId===current?.id);
 const startCreate=()=>{setEditing(null);setName("");setBody(DEFAULT_BODY);setOpen(true);};
 const startEdit=(item:SendTemplate)=>{setEditing(item);setName(item.name);setBody(item.bodyIt);setOpen(true);};
 const saveTemplate=async()=>{setSaving(true);setError("");try{const before=new Set(templates.map(item=>item.id));const payload=editing?{action:"update_send",market,templateId:editing.id,expectedRevision:editing.revision,name,bodyIt:body}:{action:"create_send",market,requestId:`send-template-${crypto.randomUUID()}`,name,bodyIt:body};const response=await fetch(`/api/template-library?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw Error();const value:TemplateLibraryState=await response.json();setLibrary(value);const saved=editing?value.sendTemplates.find(item=>item.id===editing.id):value.sendTemplates.find(item=>!before.has(item.id));if(saved)setSelected(saved.id);await reload();setOpen(false);}catch{setError("模板没有保存：商品名称和达人佣金参数必须存在，且只能使用三个受控参数。");}finally{setSaving(false);}};
 const archive=async(item:SendTemplate)=>{setSaving(true);setError("");try{const response=await fetch(`/api/template-library?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"archive_send",market,templateId:item.id,expectedRevision:item.revision})});if(!response.ok)throw Error();const value:TemplateLibraryState=await response.json();setLibrary(value);const next=value.sendTemplates[0]?.id??"";setSelected(next);if(draft?.template===item.id&&next)setDraft({...draft,template:next});await reload();setDeleting(null);}catch{setError("当前正在使用或 revision 已变化的模板不能删除；请先选择并保存另一套模板。");}finally{setSaving(false);}};
 const translate=async()=>{if(!current)return;setTranslating(true);setError("");try{const response=await fetch(`/api/conversations?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"translate",market,target:"zh",text:current.bodyIt})});if(!response.ok)throw Error();const value=await response.json();setTranslation(value.translation);}catch{setError("模板暂时无法翻译，市场语言原文已保留。");}finally{setTranslating(false);}};
 const reviewTemplate=async(state:"approved"|"rejected")=>{if(!current||!currentReview)return;setSaving(true);setError("");try{const response=await fetch(`/api/template-library?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"review_send",market,requestId:`template-review-${crypto.randomUUID()}`,templateId:current.id,state,expectedRevision:currentReview.revision})});if(!response.ok)throw Error();setLibrary(await response.json());}catch{setError("审核状态没有保存；模板内容或 revision 可能已变化。");}finally{setSaving(false);}};
 return <>
  <Card title="二发话术模板" subtitle="16 条已审批语义按市场语言展示；最终正文在领取达人时冻结进 delivery。" action={<div className="flex items-center gap-2">{library&&<Pill tone={library.review.ready?"success":"warning"}>已审核 {library.review.approved}/{library.review.total}</Pill>}<Button size="sm" disabled={market!=="it"} onClick={startCreate}>新建模板</Button></div>}>
   {library&&<div className="px-5 pt-5"><Notice tone={library.review.ready?"success":"warning"}>{library.review.ready?"已达到发送审核门槛；系统会按达人自动轮换未使用过的话术。":`至少审核通过 ${library.review.minimumApproved} 条才允许开启真实发送。`}</Notice></div>}
   <div className="grid gap-4 p-5 lg:grid-cols-[280px_1fr]">
    <div className="max-h-[430px] space-y-2 overflow-y-auto pr-1">{templates.map(item=><button type="button" key={item.id} onClick={()=>setSelected(item.id)} className={`w-full rounded-xl border px-3 py-3 text-left ${selected===item.id?"border-brand-400 bg-brand-50 dark:bg-brand-500/10":"border-gray-200 dark:border-gray-700"}`}><div className="flex items-center justify-between gap-2"><strong className="text-sm">{item.name}</strong><Pill tone={item.builtIn?"neutral":"brand"}>{item.builtIn?`系统 v${item.revision}`:`自定义 v${item.revision}`}</Pill></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-gray-500">{item.description}</p></button>)}</div>
    <div className="space-y-3">{current?<><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-gray-800 dark:text-white">{current.name}</p><p className="mt-1 text-xs text-gray-500">可用参数：{current.parameters.map(value=>`{${value}}`).join(" · ")}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={saving||currentReview?.state==="approved"} onClick={()=>void reviewTemplate("approved")}>审核通过</Button><Button size="sm" variant="outline" disabled={saving||currentReview?.state==="rejected"} onClick={()=>void reviewTemplate("rejected")}>拒绝</Button><Button size="sm" variant="outline" disabled={market!=="it"} onClick={()=>startEdit(current)}>修改</Button><Button size="sm" variant="outline" disabled={translating} onClick={()=>void translate()}>{translating?"翻译中…":"翻译成中文"}</Button><Button size="sm" variant="ghost" disabled={market!=="it"||saving||send?.control.template===current.id} onClick={()=>setDeleting(current)}>删除</Button><Button size="sm" disabled={!draft||busy||draft.template===current.id} onClick={()=>draft&&setDraft({...draft,template:current.id})}>{draft?.template===current.id?"已选择":"选为发送模板"}</Button></div></div><div className="rounded-xl bg-gray-50 p-4 text-sm leading-6 text-gray-700 dark:bg-gray-800 dark:text-gray-200"><p className="whitespace-pre-wrap">{current.bodyIt}</p>{(translation||current.translationZh)&&<div className="mt-3 rounded-lg border border-brand-100 bg-white px-3 py-2 text-xs leading-5 text-gray-600 dark:border-brand-900 dark:bg-gray-900 dark:text-gray-300"><span className="font-medium text-brand-600 dark:text-brand-300">中文：</span>{translation||current.translationZh}</div>}<div className="my-3 border-t border-gray-200 dark:border-gray-700"/><p className="text-xs text-gray-500">参数预览</p><p className="mt-1 whitespace-pre-wrap">{renderSample(current.bodyIt)}</p></div>{current.id===send?.control.template&&send.sample&&<div className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><p className="text-xs font-medium text-gray-500">当前发送池真实例子 · @{send.sample.handle} · {send.sample.creatorCommission}%</p><p lang={library?.locale} className="mt-2 text-sm leading-6">{send.sample.messageIt}</p>{send.sample.messageZh&&<p className="mt-2 text-xs leading-5 text-gray-500">中文辅助：{send.sample.messageZh}</p>}</div>}{draft?.template===current.id&&draft.template!==send?.control.template&&<Notice tone="warning">已选择；请在下方“发送设置与操作”保存后生效。</Notice>}{send?.control.template===current.id&&<Notice tone="success">当前发送设置保留此模板用于预览；真实发送会按达人轮换全部已审核且未使用的话术。</Notice>}</>:<p className="text-sm text-gray-500">模板库为空或正在读取。</p>}</div>
   </div>{error&&<div className="px-5 pb-5"><Notice tone="warning">{error}</Notice></div>}
  </Card>
  <Dialog open={open} onClose={()=>setOpen(false)} title={editing?"修改二发模板":"新建二发模板"} description="系统模板与自定义模板都写新 revision；只允许三个参数，商品名称和达人佣金必须存在。"><div className="space-y-4"><label className="block text-sm font-medium">模板名称<Input className="mt-2" value={name} maxLength={60} onChange={event=>setName(event.target.value)}/></label><label className="block text-sm font-medium">正文<TextArea className="mt-2" value={body} maxLength={600} onChange={event=>setBody(event.target.value)}/></label><div className="flex flex-wrap gap-2">{["{creator_handle}","{product_name}","{creator_commission}"].map(value=><Button key={value} size="sm" variant="outline" onClick={()=>setBody(text=>`${text}${text.endsWith(" ")||!text?"":" "}${value}`)}>{value}</Button>)}</div><div className="rounded-lg bg-gray-50 p-3 text-sm leading-6 dark:bg-gray-800">{renderSample(body)}</div><Button disabled={saving||!name.trim()||!body.trim()} onClick={()=>void saveTemplate()}>{saving?"保存中…":"保存模板"}</Button></div></Dialog>
  <Dialog open={Boolean(deleting)} onClose={()=>setDeleting(null)} title="删除二发模板" description="删除只归档当前模板，不改变历史 delivery。"><div className="space-y-4"><Notice tone="warning">确定删除“{deleting?.name}”吗？当前发送模板必须先切换并保存。</Notice><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setDeleting(null)}>取消</Button><Button variant="danger" disabled={saving||!deleting} onClick={()=>deleting&&void archive(deleting)}>{saving?"删除中…":"确认删除"}</Button></div></div></Dialog>
 </>;
}
