"use client";
import {useRef,useState} from "react";
import {Button,Card,Dialog,EmptyState,Notice,Pill,StatTile} from "../bdhub/ui";
import {buildStatsCalendar} from "./stats-calendar";
import type {InboxController} from "./useInboxMonitor";
import type {InboxDay,InboxDayDetail,InboxDetailItem} from "../../server/inbox/bridge";

const caseReasons:Record<string,string>={catalog_request:"更多商品目录",sample_request:"样品申请",link_issue:"链接问题",refund_sample:"退款或样品费用",multiple_requests:"多个诉求",unclassified:"待人工判断",human:"待人工判断"};
const time=(value:number)=>new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,timeZone:"Asia/Shanghai"}).format(new Date(value));
function DetailItem({item}:{item:InboxDetailItem}){const creator=item.handle?`@${item.handle}`:item.creatorId?`达人 ${item.creatorId.slice(-8)}`:"达人未关联";const delivery=item.kind==="delivery",reply=item.kind==="reply";const title=delivery?(item.status==="confirmed"?"确认商品卡":"未确认商品卡"):reply?"达人回复":item.kind==="showcase"?"加橱窗通知":item.kind==="auto_reply"?"历史服务回复":"新建人工案件";return <article className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-gray-400">{time(item.occurredAt)} · {creator}</p></div><Pill tone={delivery&&item.status!=="confirmed"||item.kind==="case"?"warning":"neutral"}>{item.kind==="case"?(caseReasons[item.status??""]??"人工事项"):item.status??title}</Pill></div>{delivery&&<p className="mt-3 text-xs leading-5 text-gray-500">{item.product??"商品名称未记录"}{item.pid?` · PID ${item.pid}`:""}{item.creatorPercent?` · 达人佣金 ${item.creatorPercent}%`:""}</p>}{item.text&&<p className="mt-3 whitespace-pre-wrap rounded-lg bg-gray-50 p-3 text-sm leading-6 dark:bg-gray-800">{item.text}</p>}</article>}
function path(days:InboxDay[],key:"creators"|"replies"|"showcase",width=900,height=240){const max=Math.max(1,...days.flatMap(day=>[day.creators,day.replies,day.showcase]));return days.map((day,index)=>{const x=days.length===1?width/2:index*(width/(days.length-1));const y=height-(day[key]/max)*(height-28)-14;return `${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");}

export default function StatsCalendarPanel({controller}:{controller:InboxController}){
 const {data,loaded,range,setRange}=controller;const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<InboxDayDetail|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const request=useRef(0);
 const loadDetail=async(date:string,offset=0)=>{const sequence=++request.current;setSelected(date);setBusy(true);setError("");try{const query=new URLSearchParams({date,offset:String(offset),limit:"50"});const response=await fetch(`/api/inbox?${query}`,{cache:"no-store"});if(!response.ok)throw Error();const value=await response.json() as InboxDayDetail;if(sequence!==request.current)return;setDetail(current=>offset&&current?.date===date?{...value,items:[...current.items,...value.items]}:value);}catch{if(sequence===request.current)setError("暂时无法读取当天明细，趋势汇总仍保留。");}finally{if(sequence===request.current)setBusy(false);}};
 const close=()=>{request.current+=1;setSelected(null);setDetail(null);setError("");};
 if(!data?.available)return <Card title="结果趋势"><div className="p-5"><EmptyState title={!loaded?"正在读取趋势…":"趋势暂不可用"} description="没有可靠数据时不会用 0 代替真实结果。"/></div></Card>;
 let model;try{model=buildStatsCalendar(data);}catch{return <Card title="结果趋势"><div className="p-5"><Notice tone="warning">趋势总数与每日台账没有对平，已停止展示。</Notice></div></Card>;}
 const {days,totals}=model;
 return <Card title="结果趋势" subtitle={`最近 ${range} 个北京自然日；点击日期核对当日白名单明细。`} action={<div className="flex gap-1">{([7,14,30] as const).map(value=><Button key={value} size="sm" variant={range===value?"primary":"ghost"} onClick={()=>setRange(value)}>{value} 天</Button>)}</div>}>
  <div className="space-y-5 p-5"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatTile label="确认触达达人" value={totals.creators} hint="每日按达人去重" brand/><StatTile label="有回复达人" value={totals.replies} hint="实时回复事件"/><StatTile label="已加橱窗达人" value={totals.showcase} hint="实时橱窗通知"/><StatTile label="未确认商品卡" value={totals.unconfirmed} hint="不计入成功"/></div>
   <div className="overflow-hidden rounded-xl border border-gray-200 p-4 dark:border-gray-800"><div className="mb-3 flex flex-wrap gap-4 text-xs"><span className="text-brand-600">● 已确认触达</span><span className="text-success-600">● 有回复</span><span className="text-warning-600">● 已加橱窗</span></div><svg viewBox="0 0 900 280" className="h-72 w-full" role="img" aria-label={`${range}日触达、回复和加橱窗趋势`}><g stroke="currentColor" className="text-gray-100 dark:text-gray-800">{[40,100,160,220].map(y=><line key={y} x1="0" x2="900" y1={y} y2={y}/>)}</g><polyline fill="none" stroke="currentColor" strokeWidth="4" className="text-brand-500" points={path(days,"creators")}/><polyline fill="none" stroke="currentColor" strokeWidth="4" className="text-success-500" points={path(days,"replies")}/><polyline fill="none" stroke="currentColor" strokeWidth="4" className="text-warning-500" points={path(days,"showcase")}/></svg><div className="grid gap-1" style={{gridTemplateColumns:`repeat(${days.length},minmax(0,1fr))`}}>{days.map((day,index)=><button key={day.date} className={`truncate rounded px-1 py-2 text-[10px] ${day.isToday?"bg-brand-50 font-semibold text-brand-600":"text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-800"}`} title={`${day.date} · 触达 ${day.creators} · 回复 ${day.replies} · 橱窗 ${day.showcase}`} onClick={()=>void loadDetail(day.date)}>{range===30&&index%3!==0&&!day.isToday?"":day.date.slice(5)}</button>)}</div></div>
   <Notice>unknown、发送失败、账号级拒绝、付费/拒绝合作和人工事项保留在趋势下方异常明细，不混入三条成功曲线。当前未结人工事项 <strong>{data.openCases}</strong> 件。</Notice>
  </div>
  <Dialog open={selected!==null} onClose={close} title={`${selected??""} · 日明细`} description="只读核对确认/未确认商品卡、回复、橱窗和人工事项。" wide>{error&&<Notice tone="warning">{error}</Notice>}{!detail&&!error?<p className="py-8 text-center text-sm text-gray-500">正在读取…</p>:detail&&<div className="space-y-3"><p className="text-xs text-gray-500">共 {detail.total} 条，当前显示 {detail.items.length} 条。</p>{detail.items.map(item=><DetailItem key={`${item.kind}-${item.ref}`} item={item}/>)}{detail.nextOffset!==null&&<div className="flex justify-center"><Button variant="outline" disabled={busy} onClick={()=>void loadDetail(detail.date,detail.nextOffset??0)}>{busy?"读取中…":"继续加载"}</Button></div>}</div>}</Dialog>
 </Card>;
}
