"use client";
import {useEffect,useState} from "react";
import {Button,Card,Field,Icon,Notice,Pill,Select} from "../bdhub/ui";
import type {SecondOpportunity,SecondTemplate} from "./contracts";

function observedAt(value:string){const time=Date.parse(value);return Number.isFinite(time)?new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Shanghai"}).format(time)+"（北京时间）":"未记录";}

export default function TemplatePanel({opportunity,disabled,busy,onRender}:{opportunity:SecondOpportunity;disabled:boolean;busy:boolean;onRender:(templateId:string)=>void}){
  const [templates,setTemplates]=useState<SecondTemplate[]>([]),[chosen,setChosen]=useState(opportunity.templateDraft?.templateId||""),[error,setError]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{const controller=new AbortController();void(async()=>{try{const response=await fetch("/api/second-outreach?view=templates",{cache:"no-store",credentials:"same-origin",signal:controller.signal});const body=await response.json();if(!response.ok||!Array.isArray(body.templates)||!body.templates.every((t:SecondTemplate)=>typeof t.id==="string"&&typeof t.textIt==="string"&&typeof t.translationZh==="string"))throw Error();if(!controller.signal.aborted){setTemplates(body.templates);setChosen(value=>value||body.templates[0]?.id||"");}}catch{if(!controller.signal.aborted)setError("模板暂不可用，请重新读取页面。");}})();return()=>controller.abort();},[]);
  const template=templates.find(t=>t.id===chosen),draft=opportunity.templateDraft;
  const mismatch=Boolean(draft&&(draft.templateId!==chosen||draft.templateFingerprint!==template?.fingerprint));
  const copy=async()=>{if(!draft)return;try{await navigator.clipboard.writeText(draft.textIt);setNotice("已复制模板稿，未发送消息。");}catch{setNotice("复制未完成，可手动选择下方正文。");}};
  return <Card title="二发模板" subtitle="参考你提供的墨西哥话术：商品卡确认后，再发送固定模板。" action={<Pill tone="brand">生成 Token 0</Pill>}><div className="space-y-4 p-5">
    {error&&<Notice tone="warning">{error}</Notice>}
    <div className="flex flex-wrap items-end gap-3"><div className="min-w-56 flex-1"><Field label="选择模板"><Select value={chosen} disabled={disabled||busy||!templates.length} onChange={event=>{setChosen(event.target.value);setNotice("");}}>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.version}</option>)}</Select></Field></div><Button disabled={disabled||busy||!template||!opportunity.currentRecipient||opportunity.control==="paused"} onClick={()=>onRender(chosen)}><Icon name="file" className="size-4"/>{busy?"正在保存…":"填充并冻结模板稿"}</Button></div>
    {template&&<><p className="text-xs leading-5 text-gray-500">{template.description}</p><details className="rounded-xl bg-gray-50 p-4 text-xs text-gray-500 dark:bg-gray-800/40"><summary className="cursor-pointer">查看固定模板</summary><p lang="it" className="mt-3 whitespace-pre-wrap leading-6">{template.textIt}</p><p className="mt-3 whitespace-pre-wrap leading-6">{template.translationZh}</p></details></>}
    {draft?.promotionClaims?.length? <div className="rounded-xl bg-brand-25 p-4 text-xs text-brand-600 dark:bg-brand-500/10 dark:text-brand-300"><p className="font-medium">本批推广理由：BJN 链接佣金高于公开计划</p><p className="mt-2 leading-5">理由按商品准备，同批复用；发送前会重新核对。</p><details className="mt-2"><summary className="cursor-pointer">查看本次依据</summary>{draft.promotionClaims.map(claim=><p key={claim.pid} className="mt-2 leading-5">BJN 达人佣金 {claim.creatorPercent}% · 公开计划 {claim.publicPercent}% · 观测于 {observedAt(claim.observedAt)}</p>)}</details></div>:null}
    {draft?<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2 text-xs"><Pill tone="neutral">已冻结 · 未发送</Pill><span className="text-gray-400">{draft.templateName} · v{draft.templateVersion}</span></div>{mismatch&&<p className="text-xs text-gray-500">下方保留的是此前冻结的正文，切换模板后需重新填充保存。</p>}<div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-medium text-gray-800 dark:text-gray-200">意大利语正文</h3><Button size="sm" variant="ghost" onClick={()=>void copy()}><Icon name="copy" className="size-3.5"/>复制原文</Button></div><p lang="it" className="select-text whitespace-pre-wrap break-words text-sm leading-7 text-gray-800 dark:text-gray-200">{draft.textIt}</p></div><details className="rounded-xl bg-gray-50 p-4 text-sm dark:bg-gray-800/40"><summary className="cursor-pointer text-gray-600 dark:text-gray-300">中文辅助理解</summary><p className="mt-3 whitespace-pre-wrap leading-7 text-gray-500">{draft.translationZh}</p></details><details className="text-xs text-gray-400"><summary className="cursor-pointer">模板与冻结记录</summary><p className="mt-2 break-all">{draft.draftId}</p><p className="mt-1 leading-5">身份、商品、模板版本和正文均已冻结；变化后需准备新版本。</p></details></div>:<p className="text-xs text-gray-400">选择模板后可预览实际收件人和商品对应的正文。</p>}
    {notice&&<p role="status" className="text-xs text-brand-500">{notice}</p>}
  </div></Card>;
}
