"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button,Card,Dialog,Icon,Notice,Pill} from "../bdhub/ui";
import type {LiveComponentState,LiveItemState,LiveTrialItem,SecondLiveResponse,SecondLiveStartRequest} from "./live-contracts";
import {liveStartBlocker,readLiveTrial,validLiveResponse,validStartRequest} from "./live-read";
const API="/api/second-live";
const itemLabels:Record<LiveItemState,string>={pending:"等待批准与启动",creating_conversation:"正在准备会话",conversation_ready:"会话已准备",submitting:"正在提交组件",accepted_candidate:"已获候选回执 · 待核对",confirmed:"本项交付已确认",result_unknown:"结果未知",failed_not_sent:"未发送",partial_delivery:"已部分发送"};
const componentLabels:Record<LiveComponentState,string>={pending:"待发送",inflight:"提交中",accepted_candidate:"回执待核对",confirmed:"已确认",result_unknown:"结果未知",failed_not_sent:"未发送"};
const blockerMessages:Record<string,string>={expired:"本批有效期已过，请重新冻结当前资料后再确认。",paused:"此批次已暂停，已有记录保留。",complete:"此批次已结束，交付情况以逐项记录为准。",unknown:"存在未知结果，需要先核对原发送；不会重复提交。",partial:"已有部分发送，保留已确认卡片，后续须核对原记录。",launch_recorded:"此批次已有启动记录，下面持续显示原进程与发送状态。",already_started:"此批次已有执行记录，不能重新从头启动。",components_missing:"本批商品卡与文字依赖尚不完整。"};
function time(value:string|null){if(!value)return "尚无记录";const stamp=Date.parse(value);return Number.isFinite(stamp)?new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,timeZone:"Asia/Shanghai"}).format(stamp):"时间未记录";}
function handle(item:LiveTrialItem){return item.handle?`@${item.handle.replace(/^@/,"")}`:"名字未记录";}
function componentSummary(item:LiveTrialItem){return `${item.components.filter(component=>component.componentKind==="card").length} 张商品卡 + ${item.components.filter(component=>component.componentKind==="text").length} 条固定话术`;}
function responseMessage(value:unknown,fallback:string){const row=value as {error?:{message?:unknown}}|null;return typeof row?.error?.message==="string"?row.error.message:fallback;}
function launchLabel(value:SecondLiveResponse){return value.launch.state==="running"||value.launch.state==="started"?"执行进程已启动":value.launch.state==="finished"?value.launch.pid===null&&value.launch.requestId===null?"本批已结束 · 未启动进程":"本批执行已结束":value.launch.state==="start_unknown"?"启动结果待核对":value.launch.requestId?"本次未启动":"尚未启动";}

export default function TrialPanel({trialId}:{trialId:string}){
  const [data,setData]=useState<SecondLiveResponse|null>(null),[readError,setReadError]=useState(""),[actionError,setActionError]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[storageError,setStorageError]=useState(false),[pending,setPending]=useState<SecondLiveStartRequest|null>(null),[confirming,setConfirming]=useState<{hash:string;restore:boolean}|null>(null),[refresh,setRefresh]=useState(0),[now,setNow]=useState(Date.now());
  const mounted=useRef(false),writing=useRef(false),pendingRef=useRef<SecondLiveStartRequest|null>(null),controller=useRef<AbortController|null>(null),readSequence=useRef(0);
  const storageKey=`bdhub-second-live-start-v1:${trialId}`;
  const clearPending=useCallback(()=>{pendingRef.current=null;setPending(null);try{sessionStorage.removeItem(storageKey);}catch{}},[storageKey]);
  useEffect(()=>{mounted.current=true;try{const raw=sessionStorage.getItem(storageKey);if(raw){const saved:unknown=JSON.parse(raw);if(!validStartRequest(saved)||saved.trialId!==trialId)throw new Error();pendingRef.current=saved;setPending(saved);setActionError("上次确认启动的结果尚未确认，先读取原启动记录。");}setReady(true);}catch{setStorageError(true);setActionError("无法恢复原请求编号，请检查浏览器会话存储后刷新。");}return()=>{mounted.current=false;controller.current?.abort();};},[storageKey,trialId]);
  useEffect(()=>{
    const abort=new AbortController(),generation=++readSequence.current;let reading=false;
    const read=async()=>{if(reading||document.visibilityState!=="visible")return;reading=true;try{const result=await readLiveTrial(trialId,async url=>{const response=await fetch(url,{credentials:"same-origin",cache:"no-store",signal:abort.signal});let body:unknown;try{body=await response.json();}catch{throw new Error("暂时无法读取实测批次。");}if(!response.ok)throw new Error(responseMessage(body,"暂时无法读取实测批次。"));return body;});if(abort.signal.aborted||generation!==readSequence.current)return;setData(result);setReadError("");setNow(Date.now());if(result&&pendingRef.current&&result.launch.requestId===pendingRef.current.requestId){clearPending();setActionError("");}}catch(failure){if(!abort.signal.aborted&&generation===readSequence.current)setReadError(failure instanceof Error?failure.message:"暂时无法读取实测批次。");}finally{reading=false;}};
    void read();const timer=window.setInterval(()=>void read(),3000),visible=()=>void read();document.addEventListener("visibilitychange",visible);return()=>{abort.abort();window.clearInterval(timer);document.removeEventListener("visibilitychange",visible);};
  },[trialId,refresh,clearPending]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[]);
  const current=data?.trial.trialId===trialId?data:null,blocker=liveStartBlocker(current,now);
  const canBegin=ready&&!storageError&&!busy&&!readError&&!blocker&&!pending;
  const canRestore=ready&&!storageError&&!busy&&!readError&&!blocker&&Boolean(pending&&pending.snapshotHash===current?.trial.snapshotHash);
  const start=async(input:SecondLiveStartRequest)=>{
    if(writing.current||!mounted.current||input.trialId!==trialId||current?.trial.snapshotHash!==input.snapshotHash)return;
    try{sessionStorage.setItem(storageKey,JSON.stringify(input));}catch{setStorageError(true);setActionError("无法保存请求编号，本次没有提交。");return;}
    writing.current=true;pendingRef.current=input;setPending(input);setBusy(true);setActionError("");const abort=new AbortController();controller.current=abort;const timer=window.setTimeout(()=>abort.abort(),95000);
    try{const response=await fetch(API,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},signal:abort.signal,body:JSON.stringify(input)});let body:unknown;try{body=await response.json();}catch{throw new Error("启动结果尚未确认，请保留原请求编号。");}if(!mounted.current)return;if(!response.ok)throw new Error(responseMessage(body,"启动结果尚未确认，请读取原请求。"));if(!validLiveResponse(body,trialId)||body.trial.snapshotHash!==input.snapshotHash)throw new Error("启动响应与本次冻结内容不一致，原请求已保留。");setData(body);clearPending();setConfirming(null);}catch(failure){if(mounted.current){setActionError(failure instanceof Error&&failure.name!=="AbortError"?failure.message:"连接中断，启动结果尚未确认，请先读取原记录。");setConfirming(null);}}finally{window.clearTimeout(timer);writing.current=false;if(mounted.current){setBusy(false);setRefresh(value=>value+1);}};
  };
  const confirm=()=>{if(!confirming||!current||confirming.hash!==current.trial.snapshotHash||busy||readError||liveStartBlocker(current,Date.now()))return;const input=confirming.restore?pending:{trialId,snapshotHash:confirming.hash,confirmed:true as const,requestId:crypto.randomUUID()};if(input)void start(input);};
  if(!trialId)return null;
  return <section className="mb-6" aria-label="冻结实测批次"><Card title="已冻结的二发实测批次" subtitle="只执行本面板列明的收件人与内容，不随下方名单选择变化。" action={current&&<Pill tone={current.trial.paused||current.trial.complete||current.trial.expired?"neutral":current.trial.approved?"brand":"warning"}>{current.trial.paused?"已暂停 · 原版留存":current.trial.expired?"已过期":current.trial.complete?"本批已结束":current.trial.approved?"已批准":"待你确认"}</Pill>}><div className="space-y-5 p-4 sm:p-5">
    {readError&&<Notice tone="warning"><p>{readError}</p><Button size="sm" variant="outline" className="mt-2" onClick={()=>setRefresh(value=>value+1)}>重新读取本批</Button></Notice>}
    {!current&&!readError&&<p role="status" className="text-sm text-gray-400">正在读取这份冻结批次…</p>}
    {current&&<><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-gray-50 px-4 py-3 text-xs text-gray-500 dark:bg-gray-800/40"><div className="flex flex-wrap gap-x-5 gap-y-2"><span>意大利 · ACC6</span><span>{current.trial.items.length} 位达人</span><span>有效至 {time(current.trial.expiresAt)}（北京时间）</span></div><span>{launchLabel(current)}</span></div>
      <div className="space-y-4">{current.trial.items.map(item=><article key={item.itemId} className="space-y-4 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="break-all text-base font-semibold text-gray-800 dark:text-gray-200">{handle(item)}</h3><p className="mt-1 text-xs text-gray-500">{componentSummary(item)}</p></div><Pill tone={item.state==="result_unknown"||item.partialDelivery?"warning":item.state==="confirmed"?"success":"neutral"}>{item.partialDelivery?"已部分发送":itemLabels[item.state]}</Pill></div>
        <ol className="space-y-2">{[...item.components].sort((a,b)=>a.position-b.position).map((component,index)=><li key={component.componentId} className="flex items-center justify-between gap-3 rounded-lg bg-gray-50 px-3 py-2.5 text-xs dark:bg-gray-800/40"><span className="flex items-center gap-2 text-gray-600 dark:text-gray-300"><span className="flex size-5 items-center justify-center rounded-full border border-gray-200 text-[10px] dark:border-gray-700">{index+1}</span><Icon name={component.componentKind==="card"?"box":"chat"} className="size-3.5"/>{component.componentKind==="card"?"商品卡":"固定意语话术"}</span><span className={component.state==="result_unknown"?"text-warning-600":"text-gray-500"}>{componentLabels[component.state]}</span></li>)}</ol>
        <p className="text-xs leading-5 text-gray-500">商品卡逐张确认后才发送文字；卡片结果不明则停止。已确认卡片不会重复发送。</p>
        <details className="text-xs text-gray-500"><summary className="cursor-pointer py-1">核对商品卡 PID 与列表</summary><div className="mt-2 space-y-3">{item.components.filter(component=>component.componentKind==="card").map(component=><div key={component.componentId} className="space-y-1 break-all rounded-lg border border-gray-100 p-3 leading-5 dark:border-gray-800"><p>PID {component.productId}</p><p>列表 {component.listName||"未命名"}</p><p className="font-mono text-[11px] text-gray-400">List ID {component.listId}</p>{component.campaignName&&<p>活动 {component.campaignName}</p>}</div>)}<p className="break-all text-gray-400">收件 OECID {item.oecId}</p></div></details>
        <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><p className="mb-2 text-xs font-medium text-gray-500">冻结的意大利语正文</p><p lang="it" className="select-text whitespace-pre-wrap break-words text-sm leading-7 text-gray-800 dark:text-gray-200">{item.textIt}</p></div>
        <details className="text-xs text-gray-500"><summary className="cursor-pointer py-1">中文辅助理解</summary><p lang="zh-CN" className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-gray-600 dark:text-gray-400">{item.translationZh}</p></details>
        {(item.state==="result_unknown"||item.requiresReconciliation||item.partialDelivery)&&<p className="text-xs leading-5 text-warning-600">{item.partialDelivery?"已有组件完成交付，剩余部分保持原状态。":"原结果需要核对，不会从头重发本项。"}{item.unknownStage?.startsWith("send_card:")&&` 第 ${Number(item.unknownStage.split(":")[1])+1} 张卡片结果尚未明确。`}</p>}
        {item.errorCode&&<details className="text-xs text-gray-400"><summary className="cursor-pointer">执行记录</summary><p className="mt-2 break-all leading-5">{item.errorCode}</p>{item.attempts.map(attempt=><p key={attempt.attemptId} className="mt-1 leading-5">{attempt.stage} · {attempt.state} · {time(attempt.finishedAt||attempt.startedAt)}{attempt.errorCode?` · ${attempt.errorCode}`:""}</p>)}</details>}
      </article>)}</div>
      {blocker&&blockerMessages[blocker]&&<p role="status" className={`text-sm leading-6 ${blocker==="unknown"||blocker==="partial"?"text-warning-600":"text-gray-500"}`}>{blockerMessages[blocker]}</p>}
      {current.launch.state==="start_unknown"&&<Notice tone="warning">启动结果尚未确认，先核对原进程和发送记录；本页不会另起进程重发。</Notice>}
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 pt-4 dark:border-gray-800"><p className="max-w-xl text-xs leading-5 text-gray-500">点击确认后会通过 ACC6 联系以上真实达人，按已冻结顺序发卡与发送固定文字。</p><Button disabled={!canBegin} onClick={()=>setConfirming({hash:current.trial.snapshotHash,restore:false})}><Icon name="send" className="size-4"/>{busy?"正在确认并启动…":"确认并开始此批实测"}</Button></div>
      <details className="text-xs text-gray-400"><summary className="cursor-pointer py-1">冻结与启动记录</summary><div className="mt-2 space-y-1 break-all leading-5"><p>批次 {current.trial.trialId}</p><p>快照 {current.trial.snapshotHash}</p><p>冻结于 {time(current.trial.createdAt)} · 批准于 {time(current.trial.approvedAt)}</p><p>执行状态 {launchLabel(current)}{current.launch.pid!==null?` · PID ${current.launch.pid}`:""}</p>{current.launch.requestId&&<p>启动请求 {current.launch.requestId}</p>}</div></details>
    </>}
    {actionError&&<Notice tone="warning"><p>{actionError}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>setRefresh(value=>value+1)}>读取原启动记录</Button>{canRestore&&current&&<Button size="sm" variant="outline" onClick={()=>setConfirming({hash:current.trial.snapshotHash,restore:true})}>恢复原确认请求</Button>}</div></Notice>}
  </div></Card>
  <Dialog open={Boolean(confirming)} onClose={()=>{if(!busy)setConfirming(null);}} title="开始真实发卡和发信？" description="这会联系真实达人，不是本地预演。" wide>{current&&confirming&&<div className="space-y-5"><div className="rounded-xl bg-gray-50 p-4 text-sm leading-7 text-gray-700 dark:bg-gray-800/40 dark:text-gray-300"><p>发送账号：ACC6 · 意大利</p>{current.trial.items.map(item=><p key={item.itemId}>{handle(item)} · {componentSummary(item)}</p>)}<p>先确认商品卡，再发送本批冻结的意大利语正文。</p></div>{current.trial.items.map(item=><details key={item.itemId} className="text-xs text-gray-500"><summary className="cursor-pointer py-1">再次查看 {handle(item)} 的固定正文</summary><p lang="it" className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-gray-700 dark:text-gray-300">{item.textIt}</p></details>)}<p className="break-all text-xs leading-5 text-gray-400">快照 {confirming.hash} · 有效至 {time(current.trial.expiresAt)}（北京时间）</p>{blocker&&<Notice tone="warning">{blockerMessages[blocker]||"当前批次尚不能启动。"}</Notice>}<div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={()=>setConfirming(null)}>返回查看</Button><Button disabled={busy||Boolean(readError)||Boolean(blocker)||confirming.hash!==current.trial.snapshotHash} onClick={confirm}>{busy?"正在确认并启动…":confirming.restore?"按原请求确认启动":"确认，开始真实实测"}</Button></div></div>}</Dialog>
  </section>;
}
