import {execFile} from "node:child_process";import {join} from "node:path";
import {projectRoot} from "../runtime/project-root.ts";import {isLocalRequest} from "../runtime/validation.ts";
import {enabledMarket} from "../markets/registry.ts";
const id=(value:unknown)=>{if(typeof value!=="string"||!/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/.test(value))throw Error("invalid_workflow_request");return value;};
const revision=(value:unknown)=>{if(typeof value!=="number"||!Number.isSafeInteger(value)||value<0)throw Error("invalid_workflow_request");return value;};
const market=(value:unknown)=>{if(typeof value!=="string"||!enabledMarket(value))throw Error("invalid_workflow_request");return value;};
function invoke(action:string,body:Record<string,unknown>={}){const root=projectRoot();return new Promise<Record<string,unknown>>((resolve,reject)=>execFile(join(root,".venv/bin/python"),[join(root,"scripts/operations-workflow.py"),action,"--json",JSON.stringify(body)],{cwd:root,timeout:60_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error(String(value?.error||"workflow_unavailable"));resolve(value);}catch(error){reject(error);}}));}
const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
export const handlers={GET:async(request:Request)=>{if(!isLocalRequest(request,false))return Response.json({error:"local_origin_required"},{status:403,headers});const url=new URL(request.url);let selected:string;try{if([...url.searchParams.keys()].some(key=>key!=="market")||url.searchParams.getAll("market").length!==1)throw Error();selected=market(url.searchParams.get("market"));}catch{return Response.json({error:"invalid_query"},{status:400,headers});}try{return Response.json(await invoke("status",{market:selected}),{headers});}catch{return Response.json({error:"workflow_unavailable"},{status:503,headers});}},POST:async(request:Request)=>{if(!isLocalRequest(request,true))return Response.json({error:"local_origin_required"},{status:403,headers});let action:string,body:Record<string,unknown>,urlMarket:string;try{const url=new URL(request.url);if([...url.searchParams.keys()].some(key=>key!=="market")||url.searchParams.getAll("market").length!==1)throw Error();urlMarket=market(url.searchParams.get("market"));body=await request.json();action=String(body.action);const selected=market(body.market);if(action==="run"){if(Object.keys(body).some(key=>!["action","market","requestId","jobId"].includes(key)))throw Error();const jobId=body.jobId==null?undefined:String(body.jobId);if(jobId&&!['taplink_clean','full_catalog_update','campaign_catalog_update','taplink_prepare','kalodata_leads','oecid','send_pool_publish'].includes(jobId))throw Error();body={market:selected,requestId:id(body.requestId),...(jobId?{jobId}:{})};}else if(action==="stop"){if(Object.keys(body).sort().join(",")!=="action,expectedState,market,runId")throw Error();body={market:selected,runId:id(body.runId),expectedState:body.expectedState==="queued"?"queued":"running"};}else throw Error();}catch{return Response.json({error:"invalid_workflow_request"},{status:400,headers});}if(body.market!==urlMarket)return Response.json({error:"market_mismatch"},{status:409,headers});try{return Response.json(await invoke(action,body),{headers});}catch(error){const code=error instanceof Error?error.message:"workflow_unavailable";return Response.json({error:code},{status:code.includes("active")||code.includes("stoppable")||code.includes("market_mismatch")?409:503,headers});}}};
