"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button,Card,Notice,PageHeading,Pill,Toggle} from "../bdhub/ui";
import type {OperationsHome as State,OperationsStage} from "../../server/operations-home/bridge";

const stateLabel:Record<string,string>={disabled:"未启用",waiting_upstream:"等待上游",queued:"排队",running:"运行中",completed:"已完成",quota_exhausted:"额度耗尽",needs_human:"需人工",failed:"失败",skipped:"本轮跳过",off:"关闭",waiting_window:"等待窗口",sending:"发送中",waiting_capacity:"当日额度用尽",waiting_reconciliation:"待核验",paused:"暂停",idle:"空闲"};
const tone=(state:string)=>state==="completed"||state==="sending"?"success":state==="failed"||state==="needs_human"||state==="waiting_reconciliation"?"warning":state==="running"||state==="queued"?"brand":"neutral";
const stamp=(value:number|null)=>value?new Date(value*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"—";
function StageCard({stage,index}:{stage:OperationsStage;index:number}){const total=Object.values(stage.counts).filter(value=>typeof value==="number").reduce((sum,value)=>sum+Number(value),0);return <article className="relative min-w-0 rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.025]"><div className="flex items-start justify-between gap-2"><div><p className="text-[11px] font-medium text-gray-400">{String(index+1).padStart(2,"0")}</p><h3 className="mt-1 text-sm font-semibold text-gray-800 dark:text-white">{stage.label}</h3></div><Pill tone={tone(stage.state)}>{stateLabel[stage.state]??stage.state}</Pill></div><p className="mt-4 text-2xl font-semibold tabular-nums">{stage.processed.toLocaleString()}</p><p className="mt-1 text-xs text-gray-400">本轮处理 · 平台写入 {stage.platformWrites}</p><div className="mt-4 space-y-1 text-[11px] leading-5 text-gray-500"><p>上次成功 {stamp(stage.lastSuccessAt)}</p><p className="truncate" title={stage.stopReason??undefined}>断点/原因 {stage.stopReason??(total?`${total.toLocaleString()} 项已记账`:"无异常")}</p></div>{index<6&&<span aria-hidden className="absolute -right-3 top-1/2 z-10 hidden size-6 -translate-y-1/2 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-300 xl:flex dark:border-gray-700 dark:bg-gray-900">→</span>}</article>}

export default function OperationsHome({market,marketLabel,fullManagedCatalog}:{market:string;marketLabel:string;fullManagedCatalog:boolean}){
 const [data,setData]=useState<State|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");const requestIds=useRef(new Map<string,string>());
 const load=useCallback(async()=>{const response=await fetch(`/api/operations-home?market=${encodeURIComponent(market)}`,{cache:"no-store"});if(!response.ok)throw Error();setData(await response.json());},[market]);
 useEffect(()=>{void load().catch(()=>{});const timer=setInterval(()=>void load().catch(()=>{}),15000);return()=>clearInterval(timer);},[load]);
 const toggle=async(key:"automaticOperationsEnabled"|"fullCatalogWeeklyEnabled"|"continuousSendEnabled",value:boolean)=>{if(!data)return;setBusy(key);setMessage("");const requestId=requestIds.current.get(key)??`home-${crypto.randomUUID()}`;requestIds.current.set(key,requestId);try{const response=await fetch("/api/operations-home",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",market,requestId,expectedRevision:data.setting.revision,changes:{[key]:value}})});if(!response.ok){if(response.status===409)await load();throw Error();}setData(await response.json());requestIds.current.delete(key);setMessage("设置已保存；不会恢复旧任务或结果未知意图。");}catch{setMessage("设置未保存，状态可能已在另一窗口变化。");}finally{setBusy(null);}};
 const workflow=async(action:"run"|"stop")=>{if(!data)return;setBusy(action);setMessage("");try{const body=action==="run"?{action,market,requestId:`workflow-${crypto.randomUUID()}`}:{action,market,runId:data.workflow.runId,expectedState:data.workflow.state};const response=await fetch("/api/workflow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw Error();setMessage(action==="run"?"已创建一次人工主链；后台只执行已启用的真实作业。":"已请求安全停止；在途请求先收口。 ");await load();}catch{setMessage("主链状态已变化，请刷新后核对。");}finally{setBusy(null);}};
 if(!data)return <div className="space-y-5"><PageHeading title="运营首页" description="正在读取自动运营台账…"/><Card><div className="p-8 text-sm text-gray-500">数据暂不可用时不会显示成业务 0。</div></Card></div>;
 const active=["queued","running","stop_requested"].includes(data.workflow.state);
 const activationPending=data.issues.some(issue=>issue.kind==="activation");
 const templatePending=!data.templateReview.ready;
 return <div className="space-y-5"><PageHeading title="运营首页" description="每天只看这一页：主链、持续发送和 Agent 回复都来自同一份可恢复台账。" action={<div className="flex gap-2"><Pill tone="brand">{marketLabel}</Pill><Pill tone={data.issues.length?"warning":"success"}>{data.issues.length?`${data.issues.length} 项需处理`:"运行正常"}</Pill></div>}/>
 <Card title="自动运营控制" subtitle="正常主链只需开启总开关；打开不会恢复历史批次、旧授权或 unknown 意图。" action={active?<Button size="sm" variant="outline" disabled={busy!==null} onClick={()=>void workflow("stop")}>安全停止</Button>:undefined}><div className="grid gap-x-8 px-5 py-2 lg:grid-cols-3"><Toggle label="自动运营总开关" description={activationPending?"完成当前市场全部能力 canary 后才可开启。":"统一运行 Campaign、TapLink、Kalodata、OECID、发送池与收信。Campaign 每两天刷新一次。"} checked={data.setting.automaticOperationsEnabled} disabled={busy!==null||activationPending} onChange={value=>void toggle("automaticOperationsEnabled",value)}/>{fullManagedCatalog?<Toggle label="全托货盘周更新" description="每周普通刷新；首次接入和每 30 天按一级类目刷新。" checked={data.setting.fullCatalogWeeklyEnabled} disabled={busy!==null} onChange={value=>void toggle("fullCatalogWeeklyEnabled",value)}/>:<div className="border-b border-gray-100 py-5 dark:border-gray-800"><p className="text-sm font-medium">全托货盘周更新</p><p className="mt-1 text-xs leading-5 text-gray-400">该市场没有全托货盘，不参与此作业。</p></div>}<Toggle label="持续自动发送" description={templatePending?`先审核至少 ${data.templateReview.minimumApproved} 条二发话术（当前 ${data.templateReview.approved}/${data.templateReview.total}）。`:"独立开关：只在 16:30–24:00 窗口消费发送池。"} checked={data.setting.continuousSendEnabled} disabled={busy!==null||activationPending||templatePending} onChange={value=>void toggle("continuousSendEnabled",value)}/></div></Card>
 {message&&<Notice tone={message.includes("已")?"success":"warning"}>{message}</Notice>}
 <Card title="今日经营主链" subtitle={`workflow ${data.workflow.runId??"尚未建立"} · ${stateLabel[data.workflow.state]??data.workflow.state}`} action={<Link href={`/${market}/ops/jobs`} className="text-sm font-medium text-brand-500">查看作业与时间 →</Link>}><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-7">{data.stages.map((stage,index)=><StageCard key={stage.id} stage={stage} index={index}/>)}</div></Card>
 <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Card title="需要处理" subtitle="只收拢异常、身份维护和人工会话；正常日志不铺在首页。"><div className="space-y-3 p-5">{data.issues.map(issue=><div key={issue.id} className="flex items-start justify-between gap-4 rounded-xl border border-warning-200 bg-warning-50 p-4 dark:border-warning-900 dark:bg-warning-900/10"><div><p className="text-sm font-medium text-gray-800 dark:text-gray-200">{issue.title}</p><p className="mt-1 text-xs leading-5 text-gray-500">{issue.reason}</p></div><Pill tone="warning">{issue.kind==="conversation"?"会话":"异常"}</Pill></div>)}{!data.issues.length&&<div className="py-10 text-center"><p className="text-sm font-medium text-gray-700 dark:text-gray-200">当前没有需要人工处理的事项</p><p className="mt-2 text-xs text-gray-400">完整阶段状态与平台写入数仍保留在台账。</p></div>}</div></Card><Card title="运行边界"><div className="space-y-3 p-5 text-sm leading-6 text-gray-500"><p>真实发送：<strong className="text-gray-800 dark:text-gray-200">{data.setting.continuousSendEnabled?"已配置，仍受窗口和进程控制":"关闭"}</strong></p><p>Agent 回复：<strong className="text-gray-800 dark:text-gray-200">{data.agent.enabled?"已配置":"关闭"}</strong> · {data.agent.replyWindow.join("–")}</p><p>当前代码发布不会启动清洗、建链、发送、回复或账号重登。</p><div className="flex flex-wrap gap-2 pt-2"><Link href={`/${market}/conversations`} className="text-sm font-medium text-brand-500">处理会话</Link><Link href={`/${market}/ops/accounts`} className="text-sm font-medium text-brand-500">账号状态</Link></div></div></Card></div>
 </div>;
}
