"use client";
import Link from "next/link";
import MarketOverview from "./MarketOverview";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button,Card,Notice,PageHeading,Pill,Toggle} from "../bdhub/ui";
import type {OperationsHome as State,OperationsStage,SaveCommit} from "../../server/operations-home/bridge";

const stateLabel:Record<string,string>={disabled:"未启用",waiting_upstream:"等待上游",queued:"排队",running:"运行中",completed:"已完成",quota_exhausted:"额度耗尽",needs_human:"需人工",failed:"失败",skipped:"本轮跳过",off:"关闭",waiting_window:"等待窗口",sending:"发送中",waiting_capacity:"当日额度用尽",waiting_reconciliation:"待核验",paused:"暂停",stopped:"已停止",waiting_pool:"等待发送池",idle:"空闲"};
const tone=(state:string)=>state==="completed"||state==="sending"?"success":state==="failed"||state==="needs_human"||state==="waiting_reconciliation"?"warning":state==="running"||state==="queued"?"brand":"neutral";
const stamp=(value:number|null)=>value?new Date(value*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"—";
function StageCard({stage,index}:{stage:OperationsStage;index:number}){const total=stage.processed;return <article className="relative min-w-0 rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-800 dark:bg-white/[0.025]"><div className="flex items-start justify-between gap-2"><div><p className="text-[11px] font-medium text-gray-400">{String(index+1).padStart(2,"0")}</p><h3 className="mt-1 text-sm font-semibold text-gray-800 dark:text-white">{stage.label}</h3></div><Pill tone={tone(stage.state)}>{stateLabel[stage.state]??stage.state}</Pill></div><p className="mt-4 text-2xl font-semibold tabular-nums">{["continuous_send","agent_reply"].includes(stage.id)||typeof stage.counts.items==="number"?stage.processed.toLocaleString():"—"}</p><p className="mt-1 text-xs text-gray-400">{typeof stage.counts.items==="number"||["continuous_send","agent_reply"].includes(stage.id)?"本轮处理":"处理数未记录"} · 平台写入 {stage.platformWrites}</p><div className="mt-4 space-y-1 text-[11px] leading-5 text-gray-500"><p>上次成功 {stamp(stage.lastSuccessAt)}</p><p className="truncate" title={stage.stopReason??undefined}>断点/原因 {stage.stopReason??(total?`${total.toLocaleString()} 项已记账`:"无异常")}</p></div>{index<6&&<span aria-hidden className="absolute -right-3 top-1/2 z-10 hidden size-6 -translate-y-1/2 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-300 2xl:flex dark:border-gray-700 dark:bg-gray-900">→</span>}</article>}

export default function OperationsHome({market,marketLabel,fullManagedCatalog,runtimeAvailable}:{market:string;marketLabel:string;fullManagedCatalog:boolean|null;runtimeAvailable:boolean}){
 const [data,setData]=useState<State|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");const requestIds=useRef(new Map<string,string>());
 // Freshness of what is shown: a failed read never leaves an unconditional "normal" on screen.
 const [readAt,setReadAt]=useState<number|null>(null),[readError,setReadError]=useState(false);
 const load=useCallback(async()=>{if(!runtimeAvailable)return;try{const response=await fetch(`/api/operations-home?market=${encodeURIComponent(market)}`,{cache:"no-store"});if(!response.ok)throw Error();setData(await response.json());setReadAt(Date.now()/1000);setReadError(false);}catch(error){setReadError(true);throw error;}},[market,runtimeAvailable]);
 useEffect(()=>{if(!runtimeAvailable)return;let timer:ReturnType<typeof setTimeout>|undefined,inFlight=false,stopped=false;const poll=async()=>{if(stopped)return;if(document.visibilityState!=="visible"){timer=setTimeout(poll,60000);return;}if(inFlight){timer=setTimeout(poll,15000);return;}inFlight=true;try{await load();}catch{}finally{inFlight=false;if(!stopped)timer=setTimeout(poll,15000);}};const visible=()=>{if(document.visibilityState==="visible"&&!inFlight){if(timer)clearTimeout(timer);void poll();}};document.addEventListener("visibilitychange",visible);void poll();return()=>{stopped=true;if(timer)clearTimeout(timer);document.removeEventListener("visibilitychange",visible);};},[load,runtimeAvailable]);
 const toggle=async(key:"automaticOperationsEnabled"|"fullCatalogWeeklyEnabled"|"continuousSendEnabled",value:boolean)=>{if(!data)return;setBusy(key);setMessage("");const requestId=requestIds.current.get(key)??`home-${crypto.randomUUID()}`;requestIds.current.set(key,requestId);
  let response:Response;
  try{response=await fetch(`/api/operations-home?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",market,requestId,expectedRevision:data.setting.revision,changes:{[key]:value}})});}
  catch{setBusy(null);setMessage("保存结果未确认（网络中断）；正在重新读取实际设置，重试会沿用同一请求，不会重复变更。");void load().catch(()=>{});return;}
  try{
   if(response.status===409){requestIds.current.delete(key);setMessage("设置未保存：版本已在另一窗口变化，已重新读取当前设置。");await load().catch(()=>{});return;}
   if(response.status===400||response.status===415){requestIds.current.delete(key);setMessage("设置未保存：请求不符合要求。");return;}
   if(!response.ok&&response.status!==202){setMessage("保存结果未确认；正在重新读取实际设置，重试会沿用同一请求，不会重复变更。");await load().catch(()=>{});return;}
   const value=await response.json() as (State&{commit:SaveCommit})|{committed:true;commit:SaveCommit};
   requestIds.current.delete(key);
   const commit=value.commit;
   if("schemaVersion" in value){setData(value);setReadAt(Date.now()/1000);setReadError(false);}
   else setData(current=>current?{...current,setting:commit.setting}:current);
   const notes=[commit.refreshFailed?"页面数据暂未刷新，稍后自动重读":commit.projectionStale?"概览缓存稍后刷新":"",
    ...commit.launchErrors.map(row=>`${row.worker} 未能启动（${row.error}），调度器会按已保存的开关继续尝试`)].filter(Boolean);
   setMessage(`设置已保存（修订 ${commit.setting.revision}）${notes.length?`；${notes.join("；")}`:""}。不会恢复旧任务或结果未知意图。`);
   if(commit.refreshFailed)void load().catch(()=>{});
  }finally{setBusy(null);}};
 const workflow=async(action:"run"|"stop")=>{if(!data)return;setBusy(action);setMessage("");try{const body=action==="run"?{action,market,requestId:`workflow-${crypto.randomUUID()}`}:{action,market,runId:data.workflow.runId,expectedState:data.workflow.state};const response=await fetch(`/api/workflow?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw Error();setMessage(action==="run"?"已创建一次人工主链；后台只执行已启用的真实作业。":"已请求安全停止；在途请求先收口。 ");await load();}catch{setMessage("主链状态已变化，请刷新后核对。");}finally{setBusy(null);}};
 if(!runtimeAvailable)return <div className="space-y-5"><PageHeading title="运营首页" description="自动经营主链、异常与三个高频开关使用统一页面结构。" action={<Pill tone="warning">{marketLabel}</Pill>}/><Card title="自动运营控制"><div className="grid gap-5 p-5 lg:grid-cols-3">{["自动运营总开关","全托商品发现","持续自动发送"].map(label=><div key={label}><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs leading-5 text-gray-400">当前市场运行事实尚未验收，不可操作。</p></div>)}</div></Card><Card title="今日经营主链"><div className="p-8 text-sm text-gray-500">账号、locale 和能力确认前不创建 workflow，也不读取其它市场台账。</div></Card></div>;
 if(!data)return <div className="space-y-5"><PageHeading title="运营首页" description="正在读取自动运营台账…"/><MarketOverview key={market} market={market}/><Card title="自动运营控制"><div className="p-8 text-sm text-gray-500">控制台账暂不可用，设置操作等待读取成功；经营概览独立读取。</div></Card></div>;
 const active=["queued","running","stop_requested"].includes(data.workflow.state);
 const activationPending=data.issues.some(issue=>issue.kind==="activation");
 const templatePending=!data.templateReview.ready;
 return <div className="space-y-5"><PageHeading title="运营首页" description="每天只看这一页：主链、持续发送和 Agent 回复都来自同一份可恢复台账。" action={<div className="flex gap-2"><Pill tone="brand">{marketLabel}</Pill>{readError?<Pill tone="warning">状态不可确认 · 上次读取 {stamp(readAt)}</Pill>:<Pill tone={data.issues.length?"warning":"success"}>{data.issues.length?`${data.issues.length} 项运行观察`:"运行正常"}</Pill>}</div>}/>
 <MarketOverview key={market} market={market}/>
 <Card title="自动运营控制" subtitle="正常主链只需开启总开关；打开不会恢复历史批次、旧授权或 unknown 意图。" action={active?<Button size="sm" variant="outline" disabled={busy!==null} onClick={()=>void workflow("stop")}>安全停止</Button>:undefined}><div className="grid gap-x-8 px-5 py-2 lg:grid-cols-3"><Toggle label="自动运营总开关" description={activationPending?"完成当前市场全部能力 canary 后才可开启。":"统一运行 Campaign、TapLink、Kalodata、OECID、发送池与收信。Campaign 每两天刷新一次。"} checked={data.setting.automaticOperationsEnabled} disabled={busy!==null||activationPending&&!data.setting.automaticOperationsEnabled} onChange={value=>void toggle("automaticOperationsEnabled",value)}/>{fullManagedCatalog===true?<Toggle label="全托商品发现" description="首次及每 15 天按类目探查，只累积新合格商品；链接仍按原周期维护。" checked={data.setting.fullCatalogWeeklyEnabled} disabled={busy!==null} onChange={value=>void toggle("fullCatalogWeeklyEnabled",value)}/>:<div className="border-b border-gray-100 py-5 dark:border-gray-800"><p className="text-sm font-medium">全托商品发现</p><p className="mt-1 text-xs leading-5 text-gray-400">{fullManagedCatalog===false?"该市场已确认不支持全托，本作业不适用。":"该市场全托能力尚未验收，本作业不可用。"}</p></div>}<Toggle label="持续自动发送" description={templatePending?`先审核至少 ${data.templateReview.minimumApproved} 条二发话术（当前 ${data.templateReview.approved}/${data.templateReview.total}）。`:"独立开关：只在 16:30–24:00 窗口消费发送池。"} checked={data.setting.continuousSendEnabled} disabled={busy!==null||(activationPending||templatePending)&&!data.setting.continuousSendEnabled} onChange={value=>void toggle("continuousSendEnabled",value)}/></div></Card>
 {message&&<Notice tone={message.includes("已")?"success":"warning"}>{message}</Notice>}
 <Card title="今日经营主链" subtitle={`workflow ${data.workflow.runId??"尚未建立"} · ${stateLabel[data.workflow.state]??data.workflow.state}`} action={<Link href={`/${market}/ops/jobs`} className="text-sm font-medium text-brand-500">查看作业与时间 →</Link>}><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">{data.stages.map((stage,index)=><StageCard key={stage.id} stage={stage} index={index}/>)}</div></Card>
 <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Card title="运行观察" subtitle="兼容现有主链提示；不等同于人工待办，处理分类见上方经营概览。"><div className="space-y-3 p-5">{data.issues.map(issue=><div key={issue.id} className="flex items-start justify-between gap-4 rounded-xl border border-warning-200 bg-warning-50 p-4 dark:border-warning-900 dark:bg-warning-900/10"><div><p className="text-sm font-medium text-gray-800 dark:text-gray-200">{issue.title}</p><p className="mt-1 text-xs leading-5 text-gray-500">{issue.reason}</p></div><Pill tone="warning">{issue.kind==="conversation"?"会话":"异常"}</Pill></div>)}{!data.issues.length&&<div className="py-10 text-center"><p className="text-sm font-medium text-gray-700 dark:text-gray-200">当前未记录额外运行提示</p><p className="mt-2 text-xs text-gray-400">完整阶段状态与平台写入数仍保留在台账。</p></div>}</div></Card><Card title="运行边界"><div className="space-y-3 p-5 text-sm leading-6 text-gray-500"><p>真实发送：<strong className="text-gray-800 dark:text-gray-200">{data.setting.continuousSendEnabled?"已配置，仍受窗口和进程控制":"关闭"}</strong></p><p>Agent 回复：<strong className="text-gray-800 dark:text-gray-200">{data.agent.enabled?"已配置":"关闭"}</strong> · {data.agent.replyWindow.join("–")}</p><p>当前代码发布不会启动清洗、建链、发送、回复或账号重登。</p><div className="flex flex-wrap gap-2 pt-2"><Link href={`/${market}/conversations`} className="text-sm font-medium text-brand-500">处理会话</Link><Link href={`/${market}/ops/accounts`} className="text-sm font-medium text-brand-500">账号状态</Link></div></div></Card></div>
 </div>;
}
