import {execFile} from "node:child_process";import {join} from "node:path";
import {projectRoot} from "../creator-identities/refresh.ts";
import type {ContinuousSendState,SendTemplateOption} from "../../features/second-outreach/send-contracts.ts";
import {enabledMarket,operationalMarket} from "../markets/registry.ts";

const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw Error("invalid_send");return value as Record<string,unknown>;};
const text=(value:unknown,max=160)=>{if(typeof value!=="string"||!value||value.length>max)throw Error("invalid_send");return value;};
const count=(value:unknown,max=Number.MAX_SAFE_INTEGER)=>typeof value==="number"&&Number.isSafeInteger(value)&&value>=0&&value<=max?value:(()=>{throw Error("invalid_send")})();
const number=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)&&value>=0?value:(()=>{throw Error("invalid_send")})();
const nullable=(value:unknown)=>value==null?null:number(value);
const time=(value:unknown)=>{const result=text(value,5);if(!/^([01]\d|2[0-3]):[0-5]\d$|^24:00$/.test(result))throw Error("invalid_send");return result;};
const requestId=(value:unknown)=>{const result=text(value,120);if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/.test(result))throw Error("invalid_send_request");return result;};
function templates(raw:unknown):SendTemplateOption[]{if(!Array.isArray(raw)||!raw.length||raw.length>200)throw Error("invalid_send");return raw.map(value=>{const row=object(value);if(typeof row.builtIn!=="boolean"||(row.state!=="active"&&row.state!=="archived")||!Array.isArray(row.parameters))throw Error("invalid_send");return {id:text(row.id,40),name:text(row.name,60),description:text(row.description,180),bodyIt:text(row.bodyIt,600),revision:count(row.revision),builtIn:row.builtIn,state:row.state,parameters:row.parameters.map(item=>text(item,40))};});}
export function validateContinuousSend(raw:unknown,expectedMarket?:string):ContinuousSendState{
 const value=object(raw),market=text(value.market,2),definition=operationalMarket(market);if(value.schemaVersion!=="bdhub.continuous-send.v1"||!definition||expectedMarket&&market!==expectedMarket||value.account!==definition.accounts.communications||value.legacyBatchRetired!==true||value.platformWrites!==0||value.realSends!==0)throw Error("invalid_send");
 const c=object(value.control),r=object(value.runtime),w=object(value.window);if(typeof c.automaticEnabled!=="boolean"||typeof c.runRequested!=="boolean"||typeof c.stopRequested!=="boolean"||!Array.isArray(c.window)||c.window.length!==2||typeof w.enabled!=="boolean"||typeof w.open!=="boolean")throw Error("invalid_send");
 const control={planId:text(c.planId,120),automaticEnabled:c.automaticEnabled,runRequested:c.runRequested,stopRequested:c.stopRequested,window:[time(c.window[0]),time(c.window[1])] as [string,string],template:text(c.template,40),revision:count(c.revision),updatedAt:number(c.updatedAt)};
 const runtime={state:text(r.state,48),currentDeliveryId:r.currentDeliveryId==null?null:text(r.currentDeliveryId,120),currentCreatorId:r.currentCreatorId==null?null:text(r.currentCreatorId,120),currentPid:r.currentPid==null?null:text(r.currentPid,32),confirmedToday:count(r.confirmedToday),failedKnown:count(r.failedKnown),unknown:count(r.unknown),startedAt:nullable(r.startedAt),seenAt:nullable(r.seenAt),lastSuccessAt:nullable(r.lastSuccessAt),stoppedAt:nullable(r.stoppedAt),stopReason:r.stopReason==null?null:text(r.stopReason,160),workerPid:r.workerPid==null?null:count(r.workerPid,2**31-1),speedPerMinute:number(r.speedPerMinute)};
 let capacity:null|{windowSeconds:number;limit:number;used:number;remaining:number}=null;if(value.capacity!=null){const cap=object(value.capacity);capacity={windowSeconds:count(cap.windowSeconds),limit:count(cap.limit),used:count(cap.used),remaining:count(cap.remaining)};}
 let sample:ContinuousSendState["sample"]=null;if(value.sample!=null){const row=object(value.sample);sample={handle:text(row.handle,64),pid:text(row.pid,32),productName:text(row.productName,160),creatorCommission:text(row.creatorCommission,16),listId:text(row.listId,64),messageIt:text(row.messageIt,600),messageZh:typeof row.messageZh==="string"?row.messageZh.slice(0,600):"",templateRevision:count(row.templateRevision)};}
 if(!Array.isArray(value.unknownDeliveries)||value.unknownDeliveries.length>100)throw Error("invalid_send");const unknownDeliveries=value.unknownDeliveries.map(item=>{const row=object(item);if(Object.keys(row).sort().join(",")!=="creatorId,deliveryId,pid")throw Error("invalid_send");return {deliveryId:requestId(row.deliveryId),creatorId:text(row.creatorId,120),pid:text(row.pid,32)};});
 const result:ContinuousSendState={schemaVersion:"bdhub.continuous-send.v1",market,account:text(value.account,20),control,runtime,window:{enabled:w.enabled,open:w.open,start:w.start==null?null:time(w.start),end:w.end==null?null:time(w.end)},capacity,poolRemaining:value.poolRemaining==null?null:count(value.poolRemaining),sample,unknownDeliveries,templates:templates(value.templates),legacyBatchRetired:true,platformWrites:0,realSends:0};if(value.workerPid!==undefined)result.workerPid=count(value.workerPid,2**31-1);if(!result.templates.some(item=>item.id===control.template&&item.state==="active"))throw Error("invalid_send");return result;
}
function run(action:"status"|"save"|"start"|"stop"|"reconcile",market:string,body?:Record<string,unknown>):Promise<ContinuousSendState>{const root=projectRoot();const args=[join(root,"scripts/continuous-send.py"),action,"--market",market];if(body)args.push("--json",JSON.stringify(body));return new Promise((resolve,reject)=>execFile(join(root,".venv/bin/python"),args,{cwd:root,timeout:60_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error(String(value?.error||"continuous_send_unavailable"));resolve(validateContinuousSend(value,market));}catch(error){reject(error);}}));}
export const readSendBatch=(market:string)=>run("status",market);
export type SendRequest={action:"save"|"start"|"stop"|"reconcile";market:string;requestId?:string;expectedRevision?:number;changes?:Record<string,unknown>};
export function validateSendRequest(raw:unknown):SendRequest{const value=object(raw),action=value.action,market=text(value.market,2);if(!enabledMarket(market))throw Error("invalid_send_request");if(action==="reconcile"){if(Object.keys(value).sort().join(",")!=="action,market")throw Error("invalid_send_request");return {action,market};}if(action!=="save"&&action!=="start"&&action!=="stop")throw Error("invalid_send_request");const allowed=action==="save"?["action","market","requestId","expectedRevision","changes"]:["action","market","requestId","expectedRevision"];if(Object.keys(value).some(key=>!allowed.includes(key)))throw Error("invalid_send_request");const expectedRevision=count(value.expectedRevision);if(action!=="save")return {action,market,requestId:requestId(value.requestId),expectedRevision};const changes=object(value.changes);if(!Object.keys(changes).length||Object.keys(changes).some(key=>!["automaticEnabled","window","template"].includes(key)))throw Error("invalid_send_request");if(changes.automaticEnabled!==undefined&&typeof changes.automaticEnabled!=="boolean")throw Error("invalid_send_request");if(changes.window!==undefined&&(!Array.isArray(changes.window)||changes.window.length!==2))throw Error("invalid_send_request");return {action,market,requestId:requestId(value.requestId),expectedRevision,changes:{...(changes.automaticEnabled===undefined?{}:{automaticEnabled:changes.automaticEnabled}),...(changes.template===undefined?{}:{template:text(changes.template,40)}),...(changes.window===undefined?{}:{window:[time(changes.window[0]),time(changes.window[1])]})}};}
export const invokeSend=(request:SendRequest)=>run(request.action,request.market,request.action==="reconcile"?{market:request.market}:request as Record<string,unknown>);
