import {test} from 'node:test';import assert from 'node:assert/strict';
import {createConversationHandlers,validateConversationCommand,validateConversationDetail,validateConversationList} from '../src/server/conversations/bridge.ts';
const listPayload={available:true,view:'human',query:'',counts:{human:1,agent:0,waiting:0,completed:0,all:1},total:1,offset:0,limit:30,nextOffset:null,items:[{conversationId:'123',creatorId:'creator-1',oec:'456',handle:'alice',state:'human',queueStatusLabel:'待人工处理',humanReason:'link_issue',humanReasonLabel:'链接打不开',latestText:'non funziona',latestMeaningZh:'链接打不开',latestAt:1,waitingSeconds:2,unread:true,action:'human',caseId:'case-1'}],platformWrites:0,realSends:0};
const noop=async()=>listPayload;
const operations=(overrides={})=>({list:noop,detail:noop,saveDraft:noop,sendText:noop,sendCard:noop,reconcileManual:noop,translate:noop,completeHuman:noop,confirmManual:noop,resolveManual:noop,rejectCreator:noop,setCollaboration:noop,...overrides});
test('human conversations expose reason, source text and wait time',()=>{const value=validateConversationList(listPayload);assert.equal(value.items[0].humanReasonLabel,'链接打不开');});
test('conversation detail combines timeline, creator metrics and collaboration state',()=>{const value=validateConversationDetail({available:true,conversationId:'123',latestTurnId:'turn-'+'a'.repeat(24),creator:{creatorId:'creator-1',oec:'456',handle:'alice',mode:'human',rejected:false,unlocked:true,revision:2,collaboration:{status:'collaborated',source:'auto',revision:1,updatedAt:2}},timeline:[{id:'turn-1',direction:'inbound',kind:'text',text:'ciao',occurredAt:1,status:'received',source:'creator'}],episodes:[],case:null,agentDecisions:[],metrics:{gmv:'€100',videoGmv:'€80',liveGmv:null,followers:20,unitsSold:3,avgVideoViews:50,observedAt:'2026-09-20T00:00:00Z',replyCount:2,showcaseCount:1},manualReply:null,pendingManualReplies:[],draft:{text:'',revision:0,updatedAt:0},manualTemplates:[],platformWrites:0,realSends:0});assert.equal(value.creator.collaboration.status,'collaborated');assert.equal(value.timeline[0].direction,'inbound');assert.equal(value.metrics.gmv,'€100');});
test('conversation commands have exact bounded fields',()=>{assert.equal(validateConversationCommand({action:'send_text',market:'it',cid:'123',text:'Ciao',expectedControlRevision:2,requestId:'manual-0001'}).action,'send_text');assert.equal(validateConversationCommand({action:'confirm_manual_reply',market:'it',cid:'123',caseId:'case-'+'a'.repeat(24),turnId:null,virtual:false,expectedControlRevision:2,expectedPendingRevision:1}).action,'confirm_manual_reply');assert.equal(validateConversationCommand({action:'set_collaboration',market:'it',cid:'123',status:'paid',expectedStatusRevision:1,expectedControlRevision:2,requestId:'status-0001'}).status,'paid');assert.throws(()=>validateConversationCommand({action:'set_collaboration',market:'it',cid:'123',status:'other',expectedStatusRevision:1,expectedControlRevision:2,requestId:'status-0001'}),/invalid_conversation_request/);});
test('conversation API rejects foreign origins and mutation-shaped extras',async()=>{let calls=0;const called=async()=>{calls++;return listPayload;};const api=createConversationHandlers(operations({list:called}));const base='http://127.0.0.1:5198/api/conversations?market=it',local={host:'127.0.0.1:5198',origin:'http://127.0.0.1:5198','content-type':'application/json'};assert.equal((await api.GET(new Request(base,{headers:{...local,origin:'https://other.test'}}))).status,403);assert.equal((await api.GET(new Request(base+'&view=human&view=all',{headers:local}))).status,400);assert.equal((await api.POST(new Request(base,{method:'POST',headers:local,body:JSON.stringify({action:'save_draft',cid:'123',text:'x',expectedRevision:0,send:true})}))).status,400);assert.equal(calls,0);});
test('conversation API forwards the exact safe command',async()=>{const calls=[];const api=createConversationHandlers(operations({setCollaboration:async(...args)=>{calls.push(args);return {ok:true};}}));const url='http://127.0.0.1:5198/api/conversations?market=it',headers={host:'127.0.0.1:5198',origin:'http://127.0.0.1:5198','content-type':'application/json'};const response=await api.POST(new Request(url,{method:'POST',headers,body:JSON.stringify({action:'set_collaboration',market:'it',cid:'123',status:'rejected',expectedStatusRevision:0,expectedControlRevision:2,requestId:'status-0001'})}));assert.equal(response.status,200);assert.deepEqual(calls,[['it','123','rejected',0,2,'status-0001']]);});
test('conversation POST rejects a valid cross-market body before a mutation',async()=>{let calls=0;const api=createConversationHandlers(operations({saveDraft:async()=>{calls++;return {};}}));const response=await api.POST(new Request('http://127.0.0.1:5198/api/conversations?market=br',{method:'POST',headers:{host:'127.0.0.1:5198',origin:'http://127.0.0.1:5198','content-type':'application/json'},body:JSON.stringify({action:'save_draft',market:'it',cid:'123',text:'x',expectedRevision:0})}));assert.equal(response.status,409);assert.equal(calls,0);});

test('manual reconciliation accepts only the original market, conversation and request ID',async()=>{
 const calls=[];
 const api=createConversationHandlers(operations({reconcileManual:async(...args)=>{calls.push(args);return {state:'unknown',requestRef:args[2],replyId:'manual-reply-'+'a'.repeat(24),platformWrites:0,realSends:0};}}));
 const headers={host:'127.0.0.1:5198',origin:'http://127.0.0.1:5198','content-type':'application/json'};
 const input={action:'reconcile_manual',market:'it',cid:'123',requestId:'original-request-1'};
 const request=(value,urlMarket='it')=>new Request(`http://127.0.0.1:5198/api/conversations?market=${urlMarket}`,{method:'POST',headers,body:JSON.stringify(value)});
 const result=await api.POST(request(input));assert.equal(result.status,200);assert.equal((await result.json()).state,'unknown');
 assert.deepEqual(calls,[['it','123','original-request-1']]);
 for(const extra of [{text:'different text'},{episodeId:'different episode'},{expectedControlRevision:1}])assert.equal((await api.POST(request({...input,...extra}))).status,400);
 assert.equal((await api.POST(request(input,'br'))).status,409);assert.equal(calls.length,1);
});

test('manual result decoder keeps unknown separate and refuses any write in a reconciliation',async()=>{
 const {validateManualReplyResult}=await import('../src/server/conversations/bridge.ts');
 const result={state:'unknown',replyId:'manual-reply-'+'a'.repeat(24),requestRef:'original-request-1',platformWrites:0,realSends:0};
 assert.deepEqual(validateManualReplyResult({...result,rawSecret:'not returned'},result.requestRef,true),result);
 for(const patch of [{requestRef:'replacement-request-1'},{platformWrites:1},{realSends:1},{state:'success'}])assert.throws(()=>validateManualReplyResult({...result,...patch},result.requestRef,true));
});
