"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Button,Card,Input,Notice,PageHeading,Pill} from "../bdhub/ui";
import type {GlobalStatus} from "../../server/global-source/bridge";
const states:Record<string,string>={collecting:"采集中",completed:"查询范围已采完",partial:"覆盖尚不完整",blocked:"等待处理"};
const pct=(value:unknown)=>(typeof value==="string"&&value!==""||typeof value==="number")&&Number.isFinite(Number(value))?`${Number(value)/100}%`:"未返回";
export default function CatalogWorkspace(){
 const [syncing,setSyncing]=useState(false);const syncId=useRef<string|null>(null);const [revision,setRevision]=useState(0);
 async function sync(){setSyncing(true);try{syncId.current??=crypto.randomUUID();const r=await fetch("/api/global-source",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"sync",requestId:syncId.current})});if(!r.ok)throw Error();syncId.current=null;setRevision(v=>v+1);}catch{setError(true);}finally{setSyncing(false);}}
 const [data,setData]=useState<GlobalStatus|null>(null),[query,setQuery]=useState(""),[text,setText]=useState(""),[offset,setOffset]=useState(0),[error,setError]=useState(false);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await fetch(`/api/global-source?offset=${offset}&q=${encodeURIComponent(query)}`,{signal:controller.signal,cache:"no-store"});if(!r.ok)throw Error();const v=await r.json();if(!controller.signal.aborted){setData(v);setError(false);}}catch{if(!controller.signal.aborted)setError(true);}finally{if(!controller.signal.aborted)timer=setTimeout(poll,10000);}};void poll();return()=>{controller.abort();clearTimeout(timer);};},[offset,query,revision]);
 return <div className="space-y-5"><PageHeading title="货盘" description="高机会商品 · 仅全球销售商品。先发现商品，再核验可推广方案。" action={<Button onClick={()=>void sync()} disabled={syncing}>{syncing?"提交中…":data?.state==="collecting"?"检查并续采":"同步全托来源"}</Button>}/>
 {error&&<Notice tone="warning">暂时无法读取最新货盘状态，已有记录保留。</Notice>}
 <Card title="意大利 · 全托主力来源" action={<Pill tone={data?.published?"success":data?.state==="blocked"?"warning":"brand"}>{data?.state?states[data.state]:"读取中"}</Pill>}><div className="space-y-4 p-5"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["已采集去重商品",data?.products],["本查询报告数量",data?.reportedTotal],["列表显示未选",data?.listedUnselectedProducts],["已核对活动详情",data?.detailProducts]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value==null?"—":Number(value).toLocaleString()}</p></div>)}</div>
 <p className="text-sm leading-6 text-gray-500">采集进度逐页保存。只有平台返回末页、数量核对一致并确认账号身份未变，才标记本查询完成。列表数据不直接计入可发 PID。</p>
 {data?.reason&&data.state!=="completed"&&<Notice tone="warning">{{source_remote_rejected:"平台暂未接受查询，已保留采集进度。",repeated_page:"平台返回重复分页，需要核对后续采。",endpoint_end_total_mismatch:"已到接口末页，但数量尚未核对一致。",source_maintenance_due:"账号正在维护，等待恢复后续采。"}[data.reason]||"采集需进一步核对，已保存原始进度。"}</Notice>}
 {data?.updatedAt&&<p className="text-xs text-gray-400">最近写入 {new Date(data.updatedAt*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false})} · 北京时间</p>}
 </div></Card>
 {data?.selectionBatch&&<Card title="全托商品批量选入" subtitle="累计销量 ≥300 件，评分 ≥4.0，佣金差 ≥2 个百分点；本批无暂无评分商品。"><div className="space-y-3 p-5"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["本批待选总数",data.selectionBatch.total],["新选入已回查",data.selectionBatch.states.confirmed??0],["当前已选，已跳过",data.selectionBatch.states.already_selected??0],["尚未提交",data.selectionBatch.states.pending??0]].map(([label,value])=><div key={String(label)}><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold">{Number(value).toLocaleString()}</p></div>)}</div><p className="text-sm text-gray-500">条件变化已过滤 {data.selectionBatch.states.filtered??0} 个；结果待核验 {(data.selectionBatch.states.result_unknown??0)+(data.selectionBatch.states.submitting??0)} 个；选入状态需人工核对 {data.selectionBatch.states.needs_review??0} 个。选入完成后，TapLink 仍需独立准备。</p></div></Card>}
 <Card title="已发现商品" subtitle="全托商品不要求库存数量；按任务需要核对活动、佣金及平台可用状态。"><div className="p-5"><form className="mb-4 flex gap-2" onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(text.trim());}}><Input aria-label="搜索货盘商品" placeholder="搜索 PID 或商品标题" value={text} onChange={e=>setText(e.target.value)} maxLength={100}/><Button type="submit" variant="outline" className="shrink-0 whitespace-nowrap">搜索</Button></form>
 {data?.displayRunId&&data.displayRunId!==data.id&&<p className="mb-4 text-xs text-gray-500">当前新一轮仍在采集，商品列表继续展示上次完整快照；新快照完整核对后再切换。</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-gray-200 text-xs text-gray-500 dark:border-gray-700"><tr>{["商品","公开佣金","平台展示总佣金","选入观察","进一步核验"].map(label=><th key={label} className="whitespace-nowrap px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{data?.items.map(p=><tr key={p.pid} className="border-b border-gray-100 dark:border-gray-800"><td className="min-w-64 max-w-md px-3 py-4"><p className="line-clamp-2" title={p.title}>{p.title}</p><p className="mt-1 font-mono text-xs text-gray-400">{p.pid}</p></td><td className="px-3 py-4">{pct(p.publicCommissionRaw)}</td><td className="px-3 py-4">{pct(p.totalCommissionRaw)}</td><td className="whitespace-nowrap px-3 py-4">{p.selectionObservation&&["confirmed","already_selected"].includes(p.selectionObservation.state)?"已选入（已回查）":p.listedSelected===true?"采集时已选":p.listedSelected===false?"采集时未选":"待确认"}</td><td className="min-w-48 px-3 py-4">{p.stockChecked&&p.selectedOffers.length?p.selectedOffers.map((o,i)=><p key={i} className="text-xs leading-6">拟给达人 {o.creatorPercent??"未确定"}% · {o.assessment.eligible?"符合本地准备条件":"条件不满足"}</p>):<Pill tone="neutral">{p.detailsChecked?"待选入／方案核验":"待核验活动与佣金"}</Pill>}</td></tr>)}</tbody></table></div>
 {!data?.items.length&&<p className="py-8 text-center text-sm text-gray-500">{data?.available?"当前没有匹配的商品":"等待采集记录"}</p>}
 <div className="mt-4 flex items-center justify-between text-xs text-gray-500"><span>{data?.totalMatches?`${offset+1}–${Math.min(offset+30,data.totalMatches)} / ${data.totalMatches.toLocaleString()}`:"0 条"}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-30))}>上一页</Button><Button size="sm" variant="outline" disabled={!data||offset+30>=data.totalMatches} onClick={()=>setOffset(v=>v+30)}>下一页</Button></div></div>
 </div></Card>
 <Notice>商品选入、TapLink 创建和发送分别记录结果。这里展示来源与只读核验，不会因同步货盘自动发消息。平台展示总佣金不能当作达人实际可得佣金。</Notice>
 <Link href="/workspace?mode=second-live" className="inline-block text-sm text-brand-500">进入二发批次准备 →</Link>
 </div>;
}
