"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {Button,Card,Notice,PageHeading,Pill} from "../bdhub/ui";
import type {MarketCatalogState} from "../../server/market-catalog/bridge";
import LinkNamingPanel from "./LinkNamingPanel";
import LeadPool from "./LeadPool";
import {useLeadPool} from "./useLeadPool";

const number=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value.toLocaleString():"—";
const object=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
export default function MarketCatalogWorkspace({market}:{market:string}){
 const [data,setData]=useState<MarketCatalogState|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const leadPool=useLeadPool(market);
 const load=useCallback(async()=>{const response=await fetch(`/api/market-catalog?market=${encodeURIComponent(market)}`,{cache:"no-store"});if(!response.ok)throw Error();setData(await response.json());},[market]);
 useEffect(()=>{void load().catch(()=>setMessage("暂时无法读取货盘状态。"));},[load]);
 const refresh=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/api/market-catalog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"preview_campaign",market})});if(!response.ok)throw Error();setData(await response.json());setMessage("Campaign 可加入与已加入列表已只读刷新。");}catch{setMessage("Campaign 列表暂未刷新，请到账号设置检查货盘账号身份。");}finally{setBusy(false);}};
 if(!data)return <div className="space-y-5"><PageHeading title="货盘" description="正在读取市场货盘…"/>{message&&<Notice tone="warning">{message}</Notice>}</div>;
 const campaign=data.campaign,counts=object(campaign.counts),screen=data.screen,full=data.fullManaged,acceptedPartial=full.coverage==="operator_accepted_partial",completedCategories=typeof full.categoriesCompleted==="number"?full.categoriesCompleted:null,totalCategories=typeof full.categoryCount==="number"?full.categoryCount:null;
 return <div className="space-y-5"><PageHeading title="货盘" description={`${data.label}市场按“采集筛选 → TapLink → 线索身份 → 发送池”展示同一条闭环。`} action={<Button size="sm" variant="outline" disabled={busy} onClick={()=>void refresh()}>{busy?"读取中…":"刷新 Campaign 列表"}</Button>}/>
 {message&&<Notice tone={message.includes("已")?"success":"warning"}>{message}</Notice>}
 <section className="space-y-3"><div className="flex items-center gap-2"><Pill tone="brand">01</Pill><h2 className="font-semibold">采集与筛选</h2></div><div className={`grid gap-5 ${data.capabilities.fullManagedCatalog?"xl:grid-cols-2":""}`}><Card title="Campaign 货盘" subtitle="每两天完整刷新一次；每次都重新判断有效性、库存、佣金和剩余期限。"><div className="space-y-4 p-5"><div className="grid grid-cols-3 gap-3"><div><p className="text-xs text-gray-400">平台已加入</p><p className="mt-2 text-2xl font-semibold">{number(campaign.joinedCount)}</p></div><div><p className="text-xs text-gray-400">当前可加入</p><p className="mt-2 text-2xl font-semibold">{number(counts.eligible)}</p></div><div><p className="text-xs text-gray-400">本地入池</p><p className="mt-2 text-2xl font-semibold">{number(object(screen.pool).counts?object(object(screen.pool).counts).chosen:undefined)}</p></div></div><div className="flex flex-wrap gap-2"><Pill tone={data.accountCapabilities.campaign==="verified"?"success":"warning"}>Campaign 读取 · {data.accountCapabilities.campaign==="verified"?"已验证":"待验证"}</Pill><Pill tone={data.accountCapabilities.campaign_join==="verified"?"success":"warning"}>自动加入 · {data.accountCapabilities.campaign_join==="verified"?"已验证":"待验证"}</Pill></div><p className="text-xs leading-5 text-gray-500">旧商品一旦不再合格会立即退出发送池；平台仍有效但只是不符合内部门槛的 TapLink 不自动删除。</p></div></Card>
 {data.capabilities.fullManagedCatalog&&<Card title="全托货盘" subtitle="新市场首次/月度按一级类目；每周普通查询。"><div className="space-y-4 p-5"><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><div><p className="text-xs text-gray-400">已读取商品</p><p className="mt-2 text-2xl font-semibold">{number(full.products)}</p></div><div><p className="text-xs text-gray-400">已读页数</p><p className="mt-2 text-2xl font-semibold">{number(full.pages)}</p></div><div><p className="text-xs text-gray-400">筛选合格</p><p className="mt-2 text-2xl font-semibold">{number(object(full.screen).eligible)}</p></div><div><p className="text-xs text-gray-400">已选入商品</p><p className="mt-2 text-2xl font-semibold">{number(object(full.selection).selected)}</p></div><div><p className="text-xs text-gray-400">采集状态</p><p className="mt-2 text-sm font-medium">{acceptedPartial?"用户接受的部分快照":String(full.state??full.reason??"尚未运行")}</p></div></div>{acceptedPartial&&<Notice tone="warning">用户接受的部分快照：已完整读取 {completedCategories??"—"}/{totalCategories??"—"} 个一级类目；冻结商品继续筛选和选入，下一次周更使用普通查询。</Notice>}</div></Card>}</div></section>
 <section className="space-y-3"><div className="flex items-center gap-2"><Pill tone="brand">02</Pill><h2 className="font-semibold">TapLink 准备</h2></div><Card title="当前标准 TapLink" subtitle="只认当前 Offer 指纹与当前市场命名规则。"><div className="grid gap-4 p-5 sm:grid-cols-3"><div><p className="text-xs text-gray-400">可发送标准链接</p><p className="mt-2 text-2xl font-semibold">{data.downstream.activeTapLinks.toLocaleString()}</p></div><div><p className="text-xs text-gray-400">语言与短名</p><p className="mt-2 font-semibold">市场本地化</p></div><div><p className="text-xs text-gray-400">失效处理</p><p className="mt-2 font-semibold">先停用，删除需单条验证</p></div></div></Card><LinkNamingPanel market={market}/></section>
 <section className="space-y-3"><div className="flex items-center gap-2"><Pill tone="brand">03</Pill><h2 className="font-semibold">Kalodata 与 OECID</h2></div><Card title="线索与身份"><div className="grid gap-4 p-5 sm:grid-cols-3"><div><p className="text-xs text-gray-400">线索证据</p><p className="mt-2 text-2xl font-semibold">{data.downstream.leadEdges.toLocaleString()}</p></div><div><p className="text-xs text-gray-400">已解析身份</p><p className="mt-2 text-2xl font-semibold">{data.downstream.identityResolved.toLocaleString()}</p></div><div><p className="text-xs text-gray-400">并发策略</p><p className="mt-2 font-semibold">最多 2 个市场</p></div></div></Card></section>
 <section className="space-y-3"><div className="flex items-center gap-2"><Pill tone="brand">04</Pill><h2 className="font-semibold">发送池</h2></div><LeadPool data={leadPool.data} loaded={leadPool.loaded}/></section>
 <Card title="市场隔离"><div className="flex flex-wrap items-center justify-between gap-4 p-5 text-sm text-gray-500"><p>当前市场使用独立账号、plan、Campaign、全托与线索台账；空数据不会回退显示意大利市场。</p><div className="flex gap-4"><Link href={`/${market}`} className="font-medium text-brand-500">运营首页</Link><Link href={`/${market}/workspace/send`} className="font-medium text-brand-500">合作工作台</Link><Link href={`/${market}/ops/accounts`} className="font-medium text-brand-500">机构账号设置</Link></div></div></Card>
 </div>;
}
