import {execFile} from "node:child_process";
import {join} from "node:path";
import {InputError,isLocalRequest} from "../runtime/validation.ts";
import {projectRoot} from "../creator-identities/refresh.ts";
import type {LiveTrialAttempt,LiveTrialComponent,LiveTrialItem,SecondLiveResponse,SecondLiveStartRequest} from "../../features/second-outreach/live-contracts.ts";

type ObjectValue=Record<string,unknown>;
export type SecondLiveCommand="show"|"start";
const TRIAL=/^second_live_trial_[a-f0-9]{32}$/,ITEM=/^second_live_item_[a-f0-9]{32}$/,CREATOR=/^creator_[a-f0-9]{32}$/,HASH=/^[a-f0-9]{64}$/,TOKEN=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$/;
const errors:Record<string,[number,string]>={invalid_request:[400,"实测请求格式不正确。"],trial_scope_not_found:[404,"没有找到此批次的冻结范围，请使用完整的实测批次链接。"],trial_not_found:[404,"没有找到此实测批次。"],scope_conflict:[409,"批次范围与冻结记录不一致，请重新核对。"],snapshot_mismatch:[409,"冻结内容与本次确认不一致，请重新读取。"],request_conflict:[409,"此批次已有另一项启动请求，原请求记录保持不变。"],launch_busy:[409,"此批次正在处理启动请求，请读取原记录。"],trial_complete:[409,"此批次已结束，请查看逐项结果。"],trial_expired:[409,"本批有效期已过，请重新冻结当前资料后再确认。"],trial_paused:[409,"此批次已暂停，不能从此入口启动。"],campaign_result_unknown:[409,"已有结果未知的发送，须先核对原结果。"],readback_required:[409,"此批次需要先核对已有发送记录。"],trial_already_started:[409,"此批次已有执行记录，不能重复启动。"],approval_failed:[409,"本次批准未通过，请核对批次状态。"],campaign_recipient_conflict:[409,"本活动中已有该收件人的发送意图，不能另开批次重复发送。"],unsafe_local_file:[503,"本机批次文件状态异常，请检查保存记录。"],local_file_too_large:[503,"本机批次文件超出读取范围。"],invalid_local_state:[503,"本机批次状态不完整，原记录已保留。"],unsupported_schema:[503,"本机实测库格式尚未就绪。"],trial_store_unavailable:[503,"本机实测库暂不可用。"],invalid_launch_state:[503,"启动记录尚未确认，请保留原请求编号。"],clock_invalid:[503,"暂时无法核对批次有效期。"],approval_result_unknown:[503,"批准结果尚未确认，请保留原请求编号后读取。"],approval_not_started:[503,"批准过程未能启动，原请求编号已保留。"],approval_not_applied:[503,"尚未查到批准结果，请保留原请求编号。"],launch_log_unavailable:[503,"执行记录暂不可用，尚未启动此批次。"],second_live_api_failed:[503,"实测服务暂不可用，请保留原请求编号。"],source_changed:[409,"来源资料已变化，请重新冻结后确认。"],sender_binding_changed:[409,"发送账号状态已有变化，请重新核对批次。"],scope_stale:[409,"冻结依据已有变化，请重新核对批次。"]};
export class SecondLiveApiError extends Error {readonly code:string;readonly status:number;constructor(code:string,status:number,message:string){super(message);this.code=code;this.status=status;}}
const unavailable=()=>new SecondLiveApiError("second_live_unavailable",503,"尚未确认实测服务结果，请保留原请求编号。");
function object(value:unknown):ObjectValue {if(!value||typeof value!=="object"||Array.isArray(value))throw new InputError("请求必须为对象。");return value as ObjectValue;}
function exact(value:ObjectValue,keys:string[]){if(Object.keys(value).length!==keys.length||Object.keys(value).some(key=>!keys.includes(key)))throw new InputError("请求包含缺失或不支持的字段。");}
function match(value:unknown,pattern:RegExp,label:string){if(typeof value!=="string"||!pattern.test(value))throw new InputError(`${label}格式不正确。`);return value;}
export function parseSecondLiveQuery(url:string):{trialId:string}{if(url.length>2048)throw new InputError("查询过长。");const query=new URL(url).searchParams;if([...query.keys()].length!==1||query.getAll("trialId").length!==1)throw new InputError("请提供一个具体的实测批次编号。");return {trialId:match(query.get("trialId"),TRIAL,"批次编号")};}
export function parseSecondLiveStart(value:unknown):SecondLiveStartRequest {const body=object(value);exact(body,["trialId","snapshotHash","confirmed","requestId"]);if(body.confirmed!==true)throw new InputError("请先确认本批收件人与完整发送内容。");return {trialId:match(body.trialId,TRIAL,"批次编号"),snapshotHash:match(body.snapshotHash,HASH,"冻结快照"),confirmed:true,requestId:match(body.requestId,TOKEN,"请求编号")};}
function outObject(value:unknown):ObjectValue{if(!value||typeof value!=="object"||Array.isArray(value))throw unavailable();return value as ObjectValue;}
function text(value:unknown,max=10000):string{if(typeof value!=="string"||Array.from(value).length>max)throw unavailable();return value;}
function outMatch(value:unknown,pattern:RegExp){const result=text(value,200);if(!pattern.test(result))throw unavailable();return result;}
function nullableText(value:unknown,max=500){return value===null?null:text(value,max);}
function bool(value:unknown){if(typeof value!=="boolean")throw unavailable();return value;}
function integer(value:unknown,max=1_000_000){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<0||value>max)throw unavailable();return value;}
function choice<T extends string>(value:unknown,values:readonly T[]):T{if(typeof value!=="string"||!values.includes(value as T))throw unavailable();return value as T;}
function timestamp(value:unknown){const result=text(value,50);if(!/^\d{4}-\d{2}-\d{2}T.+(?:Z|[+-]\d{2}:\d{2})$/.test(result)||!Number.isFinite(Date.parse(result)))throw unavailable();return result;}
function nullableTimestamp(value:unknown){return value===null?null:timestamp(value);}
function unknownStage(value:unknown){return value===null?null:outMatch(value,/^(?:create_conversation|send_message|send_card(?::[0-3])?)$/);}
function safeCode(value:unknown){return value===null?null:typeof value==="string"&&/^[a-z][a-z0-9_]{0,99}$/.test(value)?value:"unknown_error";}
function array(value:unknown,max:number):unknown[]{if(!Array.isArray(value)||Array.from(value).length>max)throw unavailable();return value;}
function component(value:unknown):LiveTrialComponent{const row=outObject(value);const state=choice(row.state,["pending","inflight","accepted_candidate","confirmed","result_unknown","failed_not_sent"] as const),confirmed=bool(row.confirmed);if(confirmed!==(state==="confirmed"))throw unavailable();return {componentId:outMatch(row.componentId,TOKEN),componentKind:choice(row.componentKind,["card","text"]),position:integer(row.position,5),state,productId:row.productId===null?null:outMatch(row.productId,/^[0-9]{1,64}$/),listId:row.listId===null?null:outMatch(row.listId,/^[0-9]{1,64}$/),listName:nullableText(row.listName,1000),campaignName:nullableText(row.campaignName,1000),confirmed,errorCode:safeCode(row.errorCode)};}
function attempt(value:unknown):LiveTrialAttempt{const row=outObject(value);return {attemptId:outMatch(row.attemptId,TOKEN),stage:choice(row.stage,["create_conversation","send_card","send_message"]),state:choice(row.state,["inflight","completed","failed_not_sent","result_unknown"]),startedAt:timestamp(row.startedAt),finishedAt:nullableTimestamp(row.finishedAt),errorCode:safeCode(row.errorCode)};}
function item(value:unknown):LiveTrialItem{const row=outObject(value);return {itemId:outMatch(row.itemId,ITEM),opportunityId:outMatch(row.opportunityId,TOKEN),creatorId:outMatch(row.creatorId,CREATOR),oecId:outMatch(row.oecId,/^[1-9][0-9]{0,63}$/),handle:nullableText(row.handle,65),draftId:outMatch(row.draftId,TOKEN),textIt:text(row.textIt),translationZh:text(row.translationZh),textSha256:outMatch(row.textSha256,HASH),state:choice(row.state,["pending","creating_conversation","conversation_ready","submitting","accepted_candidate","confirmed","result_unknown","failed_not_sent","partial_delivery"]),partialDelivery:bool(row.partialDelivery),requiresReconciliation:bool(row.requiresReconciliation),unknownStage:unknownStage(row.unknownStage),errorCode:safeCode(row.errorCode),components:array(row.components,5).map(component),attempts:array(row.attempts,12).map(attempt)};}
export function decodeSecondLiveOutput(output:string):SecondLiveResponse {
  let value:unknown;try{value=JSON.parse(output);}catch{throw unavailable();}const body=outObject(value);
  if("error" in body){const row=outObject(body.error),code=typeof row.code==="string"?row.code:"",definition=errors[code];throw definition?new SecondLiveApiError(code,...definition):unavailable();}
  const row=outObject(body.trial),launch=outObject(body.launch),items=array(row.items,3).map(item);if(!items.length||new Set(items.map(item=>item.itemId)).size!==items.length)throw unavailable();
  return {trial:{trialId:outMatch(row.trialId,TRIAL),snapshotHash:outMatch(row.snapshotHash,HASH),market:choice(row.market,["it"]),account:choice(row.account,["acc6"]),campaignId:choice(row.campaignId,["italy-second-pilot"]),createdAt:timestamp(row.createdAt),expiresAt:timestamp(row.expiresAt),approved:bool(row.approved),approvedAt:nullableTimestamp(row.approvedAt),paused:bool(row.paused),expired:bool(row.expired),complete:bool(row.complete),blockedByUnknown:array(row.blockedByUnknown,100).map(value=>{const blocker=outObject(value);return {trialId:outMatch(blocker.trialId,TRIAL),itemId:outMatch(blocker.itemId,ITEM)};}),items},launch:{state:choice(launch.state,["not_started","started","running","finished","start_unknown"]),pid:launch.pid===null?null:integer(launch.pid,2_147_483_647),requestId:launch.requestId===null?null:outMatch(launch.requestId,TOKEN)}};
}
export function callSecondLiveCommand(command:SecondLiveCommand,input:{trialId:string}|SecondLiveStartRequest,options:{root?:string;run?:typeof execFile}={}):Promise<SecondLiveResponse>{
  if(command!=="show"&&command!=="start")throw new InputError("不支持此实测操作。");const clean=command==="start"?parseSecondLiveStart(input):(()=>{const body=object(input);exact(body,["trialId"]);return {trialId:match(body.trialId,TRIAL,"批次编号")};})();
  const root=options.root??projectRoot(),run=options.run??execFile;
  return new Promise((resolve,reject)=>{const child=run(join(root,".venv/bin/python"),[join(root,"scripts/second-live-api.py"),command],{cwd:root,timeout:command==="start"?90000:15000,maxBuffer:512*1024,shell:false,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const result=decodeSecondLiveOutput(String(stdout));if(error||result.trial.trialId!==clean.trialId||command==="start"&&result.trial.snapshotHash!==(clean as SecondLiveStartRequest).snapshotHash)throw unavailable();resolve(result);}catch(failure){reject(failure instanceof SecondLiveApiError?failure:unavailable());}});child.stdin?.on("error",()=>{});child.stdin?.end(JSON.stringify(clean));});
}
const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
function failure(error:unknown){if(error instanceof InputError||error instanceof SecondLiveApiError)return Response.json({error:{code:error.code,message:error.message}},{status:error.status,headers});const safe=unavailable();return Response.json({error:{code:safe.code,message:safe.message}},{status:safe.status,headers});}
async function readBody(request:Request){const reader=request.body?.getReader();if(!reader)throw new InputError("请求内容为空。");const pieces:Uint8Array[]=[];let size=0;try{for(;;){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>4096){await reader.cancel();throw new InputError("请求内容过长。");}pieces.push(value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const piece of pieces){bytes.set(piece,offset);offset+=piece.byteLength;}try{return JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(bytes));}catch{throw new InputError("请求不是有效 JSON。");}}
export function createSecondLiveHandlers(invoke:(command:SecondLiveCommand,input:{trialId:string}|SecondLiveStartRequest)=>Promise<SecondLiveResponse>=callSecondLiveCommand){
  const reject=()=>Response.json({error:{code:"local_origin_required",message:"实测接口仅接受本机工作台的请求。"}},{status:403,headers});
  return {GET:async(request:Request)=>{if(!isLocalRequest(request,false))return reject();try{return Response.json(await invoke("show",parseSecondLiveQuery(request.url)),{headers});}catch(error){return failure(error);}},POST:async(request:Request)=>{if(!isLocalRequest(request,true))return reject();if(request.headers.get("content-type")?.split(";")[0].trim()!=="application/json")return Response.json({error:{code:"json_required",message:"请使用 JSON 请求。"}},{status:415,headers});try{if(new URL(request.url).search)throw new InputError("启动参数只接受请求正文。");return Response.json(await invoke("start",parseSecondLiveStart(await readBody(request))),{headers});}catch(error){return failure(error);}}};
}
