"use client";
import {useEffect,useState} from "react";
import {useDemo} from "./store";
import {MARKETS,type Goal,type Market} from "./model";
import {Button,Card,Dialog,EmptyState,Field,Icon,Input,Notice,PageHeading,Pill,Select,Tabs,TextArea} from "./ui";
export default function GoalsPage({create=false,goalId}:{create?:boolean;goalId?:string}){
 const {state,dispatch,notify,go}=useDemo();const [filter,setFilter]=useState("all");const [query,setQuery]=useState("");const [editor,setEditor]=useState<Goal|"new"|null>(null);const [pause,setPause]=useState<Goal|null>(null);const [scope,setScope]=useState<"all_outbound"|"new_acquisition">("new_acquisition");
 useEffect(()=>{if(create)setEditor("new");else if(goalId){const g=state.goals.find(x=>x.id===goalId);if(g)setEditor(g);}},[create,goalId]);
 const rows=state.goals.filter(g=>(filter==="all"||g.status===filter)&&(state.marketFilter==="all"||g.markets.includes(state.marketFilter))&&(g.name+g.description).toLowerCase().includes(query.toLowerCase()));
 return <><PageHeading title="经营目标" description="设定一次目标和范围，让系统持续安排机会与合作。" action={<Button onClick={()=>setEditor("new")}><Icon name="plus"/>新建目标</Button>}/><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Tabs value={filter} onChange={setFilter} items={[{value:"all",label:"全部目标",count:state.goals.length},{value:"active",label:"进行中"},{value:"paused",label:"已暂停"},{value:"draft",label:"草稿"}]}/><div className="w-full sm:w-64"><Input aria-label="搜索经营目标" placeholder="搜索目标名称或说明" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="grid gap-5 xl:grid-cols-2">{rows.map(g=><Card key={g.id}><div className="p-5"><div className="mb-4 flex items-start justify-between gap-3"><div className="rounded-xl bg-brand-50 p-3 text-brand-500 dark:bg-brand-500/10"><Icon name="goal" className="size-6"/></div><Pill tone={g.status==="active"?"success":g.status==="paused"?"warning":"neutral"}>{g.status==="active"?"进行中":g.status==="paused"?"已暂停":"草稿"}</Pill></div><h2 className="text-lg font-semibold text-gray-800 dark:text-white">{g.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-gray-500">{g.description}</p><div className="mt-5 grid grid-cols-3 gap-3 rounded-xl bg-gray-50 p-4 text-xs dark:bg-gray-800"><div><p className="text-gray-400">市场</p><p className="mt-1.5 font-medium text-gray-700 dark:text-gray-200">{g.markets.map(m=>m.toUpperCase()).join(" / ")}</p></div><div><p className="text-gray-400">推进方式</p><p className="mt-1.5 font-medium text-gray-700 dark:text-gray-200">{g.priority==="second"?"二发优先":g.priority==="first"?"一发匹配":"均衡探索"}</p></div><div><p className="text-gray-400">费用预算 · 示例</p><p className="mt-1.5 font-medium text-gray-700 dark:text-gray-200">${g.dailyBudget} / 日</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-gray-400">策略 v{g.version} · {state.cases.filter(c=>c.goalId===g.id).length} 项关联合作</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setEditor(g)}>查看策略</Button><Button size="sm" variant={g.status==="active"?"ghost":"primary"} onClick={()=>{if(g.status==="active")setPause(g);else{dispatch({type:"update_goal",id:g.id,patch:{status:"active"}});notify("目标已开启（演示），不会触发真实发送。");}}}>{g.status==="active"?"暂停":g.status==="paused"?"恢复":"开启"}</Button></div></div></div></Card>)}</div>{!rows.length&&<Card><EmptyState title="没有符合筛选的目标" action={<Button onClick={()=>setEditor("new")}>创建经营目标</Button>}/></Card>}<div className="mt-6"><Notice>日触达不设置固定业务上限。实际执行依赖可用机会、账号容量、联系频次和服务承载能力。</Notice></div>
 {editor&&<GoalEditor item={editor} onClose={()=>setEditor(null)} onSave={(goal,status)=>{if(editor==="new")dispatch({type:"create_goal",goal:{...goal,status}});else dispatch({type:"update_goal",id:editor.id,patch:{...goal,status}});notify(status==="active"?"目标已开启（演示），可继续查看机会。":"策略草稿已保存。");setEditor(null);}}/>}
 <Dialog open={!!pause} onClose={()=>setPause(null)} title="暂停哪些工作？" description={pause?.name}><div className="space-y-3">{[{value:"new_acquisition",label:"暂停新获客",text:"停止安排新的营销机会，已有主动咨询仍可继续处理。"},{value:"all_outbound",label:"暂停本目标全部自动外联",text:"本目标未提交的自动消息不再推进，已提交结果仍需核验。"}].map(x=><label key={x.value} className={`flex cursor-pointer gap-3 rounded-xl border p-4 ${scope===x.value?"border-brand-300 bg-brand-50 dark:bg-brand-900/10":"border-gray-200 dark:border-gray-700"}`}><input type="radio" name="pause-scope" checked={scope===x.value} onChange={()=>setScope(x.value as typeof scope)} className="mt-1 accent-brand-500"/><span><span className="block text-sm font-medium">{x.label}</span><span className="mt-1 block text-xs leading-5 text-gray-500">{x.text}</span></span></label>)}</div><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={()=>setPause(null)}>取消</Button><Button onClick={()=>{if(pause)dispatch({type:"update_goal",id:pause.id,patch:{status:"paused",pauseScope:scope}});notify("已按所选范围暂停演示目标。");setPause(null);}}>确认暂停</Button></div></Dialog></>;
}
function GoalEditor({item,onClose,onSave}:{item:Goal|"new";onClose:()=>void;onSave:(goal:Omit<Goal,"id"|"version"|"status">,status:Goal["status"])=>void}){
 const [name,setName]=useState(item==="new"?"":item.name);const [description,setDescription]=useState(item==="new"?"":item.description);const [markets,setMarkets]=useState<Market[]>(item==="new"?["mx","br","it"]:item.markets);const [priority,setPriority]=useState<Goal["priority"]>(item==="new"?"second":item.priority);const [budget,setBudget]=useState(item==="new"?20:item.dailyBudget);const [preview,setPreview]=useState(false);const [error,setError]=useState("");
 const validate=()=>{if(!name.trim()||!description.trim()){setError("请填写目标名称和经营说明。");return false;}if(!markets.length){setError("至少选择一个市场。");return false;}if(!Number.isFinite(budget)||budget<1||budget>10000){setError("费用预算应在 1–10,000 USD 之间。");return false;}setError("");return true;};
 const save=(status:Goal["status"])=>{if(validate())onSave({name:name.trim(),description:description.trim(),markets,priority,dailyBudget:budget},status);};
 return <Dialog open onClose={onClose} wide title={item==="new"?"新建经营目标":"经营策略详情"} description="示例配置仅保存到当前浏览器，不调用真实模型或平台。"><div className="grid gap-7 md:grid-cols-[1.15fr_1fr]"><div className="space-y-5"><Field label="目标名称"><Input value={name} onChange={e=>{setName(e.target.value);setPreview(false);}} placeholder="例如：三市场二发持续经营"/></Field><Field label="本次希望实现什么"><TextArea value={description} onChange={e=>{setDescription(e.target.value);setPreview(false);}} placeholder="描述目标、人群和需要优先处理的事项…"/></Field><Button variant="ghost" size="sm" onClick={()=>{setName("数码好物二发合作");setDescription("优先寻找已带过同款商品的达人，合并重复机会，先处理已有回复，再安排新邀约。");}}>填入示例目标</Button><fieldset><legend className="mb-3 text-sm font-medium">适用市场</legend><div className="flex flex-wrap gap-3">{(Object.keys(MARKETS) as Market[]).map(m=><label key={m} className="flex cursor-pointer items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-sm dark:border-gray-700"><input type="checkbox" checked={markets.includes(m)} onChange={e=>{setMarkets(e.target.checked?[...markets,m]:markets.filter(x=>x!==m));setPreview(false);}} className="accent-brand-500"/>{MARKETS[m].name}</label>)}</div></fieldset><div className="grid gap-4 sm:grid-cols-2"><Field label="推进方式"><Select value={priority} onChange={e=>{setPriority(e.target.value as Goal["priority"]);setPreview(false);}}><option value="second">二发优先</option><option value="first">一发精准匹配</option><option value="balanced">均衡探索</option></Select></Field><Field label="每日模型费用预算 · USD"><Input type="number" min={1} max={10000} value={budget} onChange={e=>{setBudget(Number(e.target.value));setPreview(false);}}/></Field></div></div><div className="rounded-xl bg-gray-50 p-5 dark:bg-gray-800/60"><h3 className="text-base font-semibold">计划预览</h3><p className="mt-2 text-sm leading-6 text-gray-500">经营目标不设固定触达人数上限；商业条件沿用各市场规则，额外费用或让佣需要具体决定。</p><ol className="mt-6 space-y-5">{["核对商品、身份和当前条件","持续发现机会，合并同人重复命中","关系 Agent 组织个性化消息","根据回复、业务变化和约定接续"].map((x,i)=><li key={x} className="flex gap-3 text-sm"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-brand-50 text-brand-500 dark:bg-brand-500/10">{i+1}</span><span className="leading-6">{x}</span></li>)}</ol>{preview&&<div className="mt-6"><Notice tone="success">范围已检查：{markets.map(m=>MARKETS[m].name).join("、")}。当前仅预览，不会生成真实发送任务。</Notice></div>}</div></div>{error&&<p role="alert" className="mt-4 text-sm text-error-500">{error}</p>}<div className="mt-6 flex flex-wrap justify-end gap-3 border-t border-gray-100 pt-5 dark:border-gray-800"><Button variant="outline" onClick={()=>save("draft")}>保存草稿</Button>{!preview?<Button onClick={()=>{if(validate())setPreview(true);}}>预览影响<Icon name="arrow"/></Button>:<Button onClick={()=>save(item!=="new"&&item.status==="paused"?"paused":"active")}>{item==="new"?"开启目标（演示）":"保存策略（演示）"}</Button>}</div></Dialog>;
}
