"use client";
import {useEffect,useRef,useState} from "react";
import type {ApexOptions} from "apexcharts";
import type ApexCharts from "apexcharts";
import {useDemo} from "./store";
import {creatorFor,productFor,matchesMarket,MARKETS,type Market} from "./model";
import {Avatar,Button,Card,EmptyState,Icon,MarketPill,PageHeading,Pill,StatusPill,Tabs} from "./ui";
export function TrendChart({height=270,period="week"}:{height?:number;period?:string}){
 const chartRef=useRef<HTMLDivElement>(null);
 const [failed,setFailed]=useState(false);
 useEffect(()=>{
 let cancelled=false;
 let chart:ApexCharts|undefined;
 const options:ApexOptions={chart:{fontFamily:'Outfit, "PingFang SC", sans-serif',toolbar:{show:false},zoom:{enabled:false},animations:{enabled:false}},colors:["#465fff"],stroke:{curve:"smooth",width:3},dataLabels:{enabled:false},fill:{type:"gradient",gradient:{opacityFrom:0.25,opacityTo:0.01}},grid:{borderColor:"#e4e7ec",strokeDashArray:4,xaxis:{lines:{show:false}}},xaxis:{categories:period==="week"?["9/5","9/6","9/7","9/8","9/9","9/10","9/11"]:["8/13","8/18","8/23","8/28","9/2","9/7","9/11"],axisBorder:{show:false},axisTicks:{show:false},labels:{style:{colors:"#98a2b3",fontSize:"12px"}}},yaxis:{min:0,tickAmount:4,labels:{style:{colors:"#98a2b3",fontSize:"12px"}}},tooltip:{x:{show:true}},legend:{show:false}};
 void import("apexcharts").then(async({default:ApexCharts})=>{
   if(cancelled||!chartRef.current)return;
   chart=new ApexCharts(chartRef.current,{...options,chart:{...options.chart,type:"area",height},series:[{name:"合作进展（历史示例）",data:period==="week"?[8,12,10,18,16,22,28]:[30,42,38,60,76,83,108]}]});
   await chart.render();
 }).catch(()=>{if(!cancelled)setFailed(true);});
 return()=>{cancelled=true;chart?.destroy();};
 },[height,period]);
 return <div style={{minHeight:height}} role="img" aria-label={`合作进展历史示例，${period==="week"?"本周从 8 项增至 28 项":"近 30 天从 30 项增至 108 项"}`}><div ref={chartRef}/>{failed&&<p className="p-8 text-center text-sm text-gray-500">趋势图暂未加载，请刷新重试。</p>}</div>;
}
export default function OverviewPage(){
 const {state,go,openCase}=useDemo();const [period,setPeriod]=useState("week");
 const cases=state.cases.filter(c=>matchesMarket(state,creatorFor(state,c.creatorId).market));const opps=state.opportunities.filter(o=>matchesMarket(state,creatorFor(state,o.creatorId).market)&&o.readiness!=="excluded");const decisions=cases.filter(c=>c.status==="needs_operator");const working=cases.filter(c=>c.status!=="closed");
 const stats=[{label:"可准备机会",value:opps.filter(o=>o.readiness==="ready").length,detail:`${opps.length} 条线索，按达人统一协调`,icon:"bolt" as const,click:()=>go("opportunities")},{label:"正在推进的合作",value:working.length,detail:`${cases.filter(c=>c.delivered).length} 项已演示交付方案`,icon:"users" as const,click:()=>go("workspace")},{label:"需要你决定",value:decisions.length,detail:"日常查询与正常等待由系统处理",icon:"task" as const,click:()=>decisions[0]?openCase(decisions[0].id):go("workspace")}];
 return <><PageHeading title="今日经营" description="Agent 推进日常合作，你专注于关键决定。" action={<Button onClick={()=>go("goals",{new:"1"})}><Icon name="plus"/>新建经营目标</Button>}/>
 <div className="mb-6 grid gap-5 md:grid-cols-3">{stats.map((x,i)=><button key={x.label} onClick={x.click} className="group rounded-2xl border border-gray-200 bg-white p-5 text-left transition hover:border-brand-300 dark:border-gray-800 dark:bg-white/[0.025]"><div className="mb-4 flex items-center justify-between"><div className="rounded-xl bg-gray-100 p-3 text-gray-800 dark:bg-gray-800 dark:text-gray-200"><Icon name={i===2?"goal":x.icon==="task"?"goal":x.icon} className="size-6"/></div><Icon name="arrow" className="size-4 text-gray-400 group-hover:text-brand-500"/></div><p className="text-sm text-gray-500">{x.label}</p><p className="mt-1 text-3xl font-semibold text-gray-800 dark:text-white">{x.value}<span className="ml-2 text-sm font-normal text-gray-400">项</span></p><p className="mt-3 text-xs leading-5 text-gray-400">{x.detail}</p></button>)}</div>
 <div className="mb-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><Card title="合作推进趋势" subtitle="最近一段时间的历史示例汇总" action={<div className="w-44"><Tabs items={[{value:"week",label:"本周"},{value:"month",label:"近30天"}]} value={period} onChange={setPeriod}/></div>}><div className="px-3 pt-3"><TrendChart period={period}/></div></Card>
 <Card title="需要你决定" subtitle="已整理事实，只处理具体的商业选择" action={<Pill tone="warning">{decisions.length} 项</Pill>}>{decisions.length?decisions.map(c=>{const creator=creatorFor(state,c.creatorId);return <div key={c.id} className="p-5"><div className="flex items-center gap-3"><Avatar src={creator.avatar} name={creator.name}/><div><p className="font-medium text-gray-800 dark:text-white">{creator.name}</p><MarketPill market={creator.market}/></div></div><h3 className="mt-5 text-base font-semibold text-gray-800 dark:text-gray-200">{c.title}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{c.reason}</p><div className="my-4 rounded-lg bg-gray-50 px-3 py-2 text-xs leading-5 text-gray-500 dark:bg-gray-800">建议：沿用当前合作条件；新的费用或佣金另作决定。</div><Button className="w-full" onClick={()=>openCase(c.id)}>查看事实并决定<Icon name="arrow"/></Button></div>}):<EmptyState title="当前无需你决定" description="常规工作继续推进，你可以查看合作进展。"/>}</Card></div>
 <div className="mb-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><Card title="正在推进的合作" action={<Button variant="ghost" size="sm" onClick={()=>go("workspace")}>全部合作<Icon name="arrow" className="size-4"/></Button>}><div className="divide-y divide-gray-100 dark:divide-gray-800">{cases.slice(0,5).map(c=>{const creator=creatorFor(state,c.creatorId);const product=productFor(state,c.productId);return <button key={c.id} onClick={()=>openCase(c.id)} className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-gray-50 dark:hover:bg-white/[0.025]"><Avatar src={creator.avatar} name={creator.name}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-gray-800 dark:text-white">{creator.name}<span className="ml-2 text-xs font-normal text-gray-400">{creator.market.toUpperCase()}</span></p><p className="mt-1 truncate text-xs text-gray-500">{product.name} · {c.title}</p></div><StatusPill item={c}/><Icon name="arrow" className="size-4 shrink-0 text-gray-400"/></button>})}{cases.length===0&&<EmptyState title="这个市场还没有合作事项" action={<Button onClick={()=>go("opportunities")}>查看机会</Button>}/>}</div></Card>
 <Card title="经营目标" action={<Button variant="ghost" size="sm" onClick={()=>go("goals")}>管理目标</Button>}><div className="divide-y divide-gray-100 dark:divide-gray-800">{state.goals.filter(g=>state.marketFilter==="all"||g.markets.includes(state.marketFilter)).slice(0,3).map(g=><button key={g.id} onClick={()=>go("goals",{goal:g.id})} className="block w-full px-5 py-4 text-left hover:bg-gray-50 dark:hover:bg-white/[0.025]"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-gray-800 dark:text-white">{g.name}</p><Pill tone={g.status==="active"?"success":"neutral"}>{g.status==="active"?"进行中":g.status==="paused"?"已暂停":"草稿"}</Pill></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-gray-500">{g.description}</p><p className="mt-2 text-xs text-gray-400">{g.markets.map(m=>m.toUpperCase()).join(" · ")}<span className="mx-2">/</span>v{g.version}</p></button>)}</div></Card></div>
 <Card title="最近动态" action={<Button variant="ghost" size="sm" onClick={()=>go("agents",{tab:"history"})}>接续历史回复<Icon name="arrow" className="size-4"/></Button>}><div className="grid divide-y divide-gray-100 px-5 md:grid-cols-3 md:divide-y-0 dark:divide-gray-800">{state.activities.slice(0,3).map(a=><div key={a.id} className="py-4 md:pr-5"><p className="text-xs text-gray-400">{a.at}</p><p className="mt-2 text-sm font-medium text-gray-700 dark:text-gray-200">{a.title}</p><p className="mt-1 text-xs leading-5 text-gray-500">{a.detail}</p></div>)}</div></Card></>;
}
export function ResultsPage(){const {state,go}=useDemo();const [period,setPeriod]=useState("week");const cases=state.cases.filter(c=>matchesMarket(state,creatorFor(state,c.creatorId).market));const adopted=cases.filter(c=>c.adopted).length;return <><PageHeading title="效果与质量" description="消息接收、方案采用和机构收益，分别依据证据记录。" action={<Button variant="outline" onClick={()=>go("workspace")}>查看对应合作<Icon name="arrow"/></Button>}/><div className="mb-6 grid gap-5 md:grid-cols-3">{[["已演示交付方案",cases.filter(c=>c.delivered).length],["已模拟核实采用",adopted],["结果待核验",cases.filter(c=>c.sendState==="unknown").length]].map(([l,n])=><Card key={l} className="p-5"><p className="text-sm text-gray-500">{l}</p><p className="mt-2 text-3xl font-semibold text-gray-800 dark:text-white">{n}</p><p className="mt-3 text-xs text-gray-400">随当前演示操作更新</p></Card>)}</div><Card title="合作进展 · 历史示例" action={<div className="w-44"><Tabs value={period} onChange={setPeriod} items={[{value:"week",label:"本周"},{value:"month",label:"近30天"}]}/></div>}><div className="p-4"><TrendChart period={period} height={310}/></div></Card><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card title="按市场核对结果"><div className="overflow-auto p-5"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-gray-400"><th className="pb-3 font-normal">市场</th><th className="pb-3 font-normal">合作事项</th><th className="pb-3 font-normal">已交付</th><th className="pb-3 font-normal">已采用</th></tr></thead><tbody>{(Object.keys(MARKETS) as Market[]).filter(m=>matchesMarket(state,m)).map(m=>{const rows=state.cases.filter(c=>creatorFor(state,c.creatorId).market===m);return <tr key={m} className="border-b border-gray-100 last:border-0 dark:border-gray-800"><td className="py-4"><MarketPill market={m}/></td><td>{rows.length}</td><td>{rows.filter(c=>c.delivered).length}</td><td>{rows.filter(c=>c.adopted).length}</td></tr>})}</tbody></table></div></Card><Card title="费用与效果边界"><div className="space-y-4 p-5 text-sm"><div className="flex justify-between border-b border-gray-100 pb-4 dark:border-gray-800"><span className="text-gray-500">模型费用预算</span><span className="font-medium">USD {state.settings.modelBudget} / 日</span></div><div className="flex justify-between border-b border-gray-100 pb-4 dark:border-gray-800"><span className="text-gray-500">当前实际模型调用</span><span className="font-medium">0 · 前端演示</span></div><div className="flex justify-between"><span className="text-gray-500">机构收益</span><Pill>等待归属证据</Pill></div><p className="rounded-lg bg-gray-50 p-3 text-xs leading-6 text-gray-500 dark:bg-gray-800">采用商品方案不自动产生收入。正式效果将按市场、观察窗口和实际归属核算。</p></div></Card></div></>;}
