"use client";
import {useEffect,useId,useRef,useState,type ReactNode,type ButtonHTMLAttributes,type InputHTMLAttributes,type SelectHTMLAttributes,type TextareaHTMLAttributes} from "react";
import {createPortal} from "react-dom";
import * as Icons from "@/icons";
import TemplateBadge from "@/components/ui/badge/Badge";
import {type CooperationCase,type Market,MARKETS,STATUS} from "./model";

const iconMap={grid:Icons.GridIcon,goal:Icons.TaskIcon,bolt:Icons.BoltIcon,chat:Icons.ChatIcon,chart:Icons.PieChartIcon,agent:Icons.ShootingStarIcon,settings:Icons.PlugInIcon,search:Icons.SearchIcon,plus:Icons.PlusIcon,close:Icons.CloseIcon,arrow:Icons.ArrowRightIcon,check:Icons.CheckCircleIcon,time:Icons.TimeIcon,info:Icons.InfoIcon,bell:Icons.BellIcon,file:Icons.FileIcon,down:Icons.ChevronDownIcon,edit:Icons.PencilIcon,send:Icons.PaperPlaneIcon,users:Icons.GroupIcon,lock:Icons.LockIcon,eye:Icons.EyeIcon,menu:Icons.ListIcon,box:Icons.BoxIconLine,copy:Icons.CopyIcon};
export type IconName=keyof typeof iconMap;
export function Icon({name,className="size-5"}:{name:IconName;className?:string}){const C=iconMap[name];return <C className={className} aria-hidden="true"/>;}
// Button anatomy and token classes derived from TailAdmin Free Button.tsx (MIT).
export function Button({variant="primary",size="md",className="",children,type="button",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"outline"|"ghost"|"danger";size?:"sm"|"md"}){
 const styles={primary:"bg-brand-500 text-white shadow-theme-xs hover:bg-brand-600 disabled:bg-brand-300",outline:"bg-white text-gray-700 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 dark:bg-gray-800 dark:text-gray-300 dark:ring-gray-700 dark:hover:bg-white/5",ghost:"text-gray-500 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/5",danger:"bg-error-500 text-white hover:bg-error-600"};
 return <button type={type} {...props} className={`inline-flex items-center justify-center gap-2 rounded-lg font-medium transition disabled:cursor-not-allowed disabled:opacity-50 ${size==="sm"?"px-3.5 py-2.5 text-[13px]":"px-5 py-3 text-sm"} ${styles[variant]} ${className}`}>{children}</button>;
}
export function Card({children,className="",title,subtitle,action}:{children:ReactNode;className?:string;title?:string;subtitle?:string;action?:ReactNode}){return <section className={`rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.025] ${className}`}>{title&&<div className="flex flex-wrap items-start justify-between gap-3 border-b border-gray-100 px-5 py-4 dark:border-gray-800"><div><h2 className="text-base font-semibold text-gray-800 dark:text-white/90">{title}</h2>{subtitle&&<p className="mt-1 text-xs leading-5 text-gray-500">{subtitle}</p>}</div>{action}</div>}{children}</section>;}
export function PageHeading({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight text-gray-800 dark:text-white/90">{title}</h1>{description&&<p className="mt-1.5 text-sm leading-6 text-gray-500 dark:text-gray-400">{description}</p>}</div>{action}</div>;}
export type Tone="brand"|"success"|"warning"|"error"|"neutral"|"info";
export function Pill({children,tone="neutral"}:{children:ReactNode;tone?:Tone}){return <TemplateBadge color={tone==="brand"?"primary":tone==="neutral"?"light":tone} size="sm">{children}</TemplateBadge>;}
export function StatusPill({item}:{item:CooperationCase}){return <Pill tone={item.sendState==="unknown"?"warning":item.status==="closed"?(item.adopted?"success":"neutral"):item.status==="needs_operator"?"warning":item.status==="processing"?"brand":"neutral"}>{item.sendState==="unknown"?"结果待核验":STATUS[item.status]}</Pill>;}
export function MarketPill({market}:{market:Market}){return <span className="inline-flex items-center gap-1.5 whitespace-nowrap text-xs text-gray-500"><span className="rounded border border-gray-200 bg-gray-50 px-1.5 py-0.5 font-medium dark:border-gray-700 dark:bg-gray-800">{market.toUpperCase()}</span>{MARKETS[market].name}</span>;}
export function Avatar({src,name,size=40}:{src:string;name:string;size?:number}){return <img src={src} alt={name} width={size} height={size} className="shrink-0 rounded-full object-cover" style={{width:size,height:size}}/>;}
export const inputClass="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3.5 text-sm text-gray-800 shadow-theme-xs outline-none transition placeholder:text-gray-400 focus:border-brand-300 focus:ring-3 focus:ring-brand-500/10 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90 dark:focus:border-brand-800";
export function Input(props:InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={`${inputClass} ${props.className||""}`}/>;}
export function Select({children,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className={`${inputClass} pr-8 ${props.className||""}`}>{children}</select>;}
export function TextArea(props:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea {...props} className={`${inputClass} min-h-28 resize-y py-3 leading-6 ${props.className||""}`}/>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="block"><span className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">{label}</span>{children}{hint&&<span className="mt-1.5 block text-xs leading-5 text-gray-500">{hint}</span>}</label>;}
export function Tabs<T extends string>({items,value,onChange}:{items:{value:T;label:string;count?:number}[];value:T;onChange:(value:T)=>void}){return <div className="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-gray-100 p-1 dark:bg-gray-800" role="tablist">{items.map(item=><button type="button" key={item.value} role="tab" aria-selected={value===item.value} onClick={()=>onChange(item.value)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-medium transition ${value===item.value?"bg-white text-gray-800 shadow-theme-xs dark:bg-gray-700 dark:text-white":"text-gray-500 hover:text-gray-800 dark:hover:text-gray-200"}`}>{item.label}{item.count!==undefined&&<span className="rounded bg-gray-100 px-1.5 text-xs dark:bg-gray-600">{item.count}</span>}</button>)}</div>;}
export function EmptyState({title="暂无匹配结果",description="调整筛选条件，或查看其他市场。",action}:{title?:string;description?:string;action?:ReactNode}){return <div className="flex min-h-56 flex-col items-center justify-center px-6 py-10 text-center"><div className="mb-3 rounded-2xl bg-gray-100 p-4 text-gray-400 dark:bg-gray-800"><Icon name="file" className="size-7"/></div><h3 className="font-medium text-gray-800 dark:text-gray-200">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-gray-500">{description}</p>{action&&<div className="mt-5">{action}</div>}</div>;}
export function Dialog({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){
 const id=useId();const ref=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{if(!open)return;const prev=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";const shell=document.getElementById("bdhub-shell");shell?.setAttribute("inert","");const focus=()=>(ref.current?.querySelector<HTMLElement>('input:not([type="hidden"]),textarea,select')||ref.current?.querySelector<HTMLElement>('button,[tabindex="0"]'))?.focus();const timer=setTimeout(focus,20);
  const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();close.current();}if(e.key==="Tab"){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex="0"]')||[]).filter(el=>el.offsetParent!==null);if(!els.length){e.preventDefault();return;}const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener("keydown",key);return()=>{clearTimeout(timer);document.body.style.overflow=overflow;shell?.removeAttribute("inert");document.removeEventListener("keydown",key);prev?.focus();};
 },[open]);
 if(!open)return null;
 return createPortal(<div className="fixed inset-0 z-[99999] flex items-center justify-center bg-gray-900/45 p-3 backdrop-blur-sm sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby={id} className={`max-h-[92dvh] w-full overflow-y-auto rounded-2xl bg-white shadow-theme-xl dark:bg-gray-900 ${wide?"max-w-4xl":"max-w-xl"}`}><div className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-gray-100 bg-white px-6 py-5 dark:border-gray-800 dark:bg-gray-900"><div><h2 id={id} className="text-lg font-semibold text-gray-800 dark:text-white">{title}</h2>{description&&<p className="mt-1 text-sm leading-6 text-gray-500">{description}</p>}</div><Button variant="ghost" size="sm" onClick={onClose} aria-label="关闭对话框" className="!p-2"><Icon name="close" className="size-5 fill-current"/></Button></div><div className="p-6">{children}</div></div></div>,document.body);
}
export function Notice({children,tone="info"}:{children:ReactNode;tone?:"info"|"warning"|"success"}){return <div className={`flex items-start gap-3 rounded-xl border px-4 py-3 text-sm leading-6 ${tone==="warning"?"border-warning-200 bg-warning-50 text-warning-700 dark:border-warning-900 dark:bg-warning-900/10 dark:text-warning-400":tone==="success"?"border-success-200 bg-success-50 text-success-700 dark:border-success-900 dark:bg-success-900/10 dark:text-success-400":"border-brand-100 bg-brand-50 text-brand-600 dark:border-brand-900 dark:bg-brand-500/10 dark:text-brand-300"}`}><Icon name={tone==="success"?"check":"info"} className="mt-0.5 size-5 shrink-0"/><div>{children}</div></div>;}
export function Toggle({checked,onChange,label,description,disabled=false}:{checked:boolean;onChange:(value:boolean)=>void;label:string;description?:string;disabled?:boolean}){return <label className="flex cursor-pointer items-center justify-between gap-4 py-3"><span><span className="block text-sm font-medium text-gray-700 dark:text-gray-200">{label}</span>{description&&<span className="mt-1 block text-xs leading-5 text-gray-500">{description}</span>}</span><input className="sr-only peer" type="checkbox" role="switch" checked={checked} onChange={e=>onChange(e.target.checked)} disabled={disabled}/><span className={`relative h-6 w-11 shrink-0 rounded-full transition peer-focus-visible:ring-3 peer-focus-visible:ring-brand-300 ${checked?"bg-brand-500":"bg-gray-300 dark:bg-gray-700"} ${disabled?"opacity-50":""}`}><span className={`absolute top-0.5 size-5 rounded-full bg-white shadow transition ${checked?"left-5.5":"left-0.5"}`}/></span></label>;}
// One horizontal bar for work that reports how much of it is done. A job with nothing to do shows
// a full bar rather than an empty one, because "finished" and "did nothing" look the same otherwise.
export function Progress({done,total,label}:{done:number;total:number;label?:string}){
 const safeTotal=Math.max(0,total),safeDone=Math.max(0,Math.min(done,safeTotal));
 const percent=safeTotal===0?100:Math.round((safeDone/safeTotal)*100);
 return <div><div className="mb-1.5 flex items-center justify-between text-xs text-gray-500"><span>{label}</span><span className="tabular-nums">{safeDone.toLocaleString()} / {safeTotal.toLocaleString()}</span></div><div className="h-2 w-full overflow-hidden rounded-full bg-gray-100 dark:bg-gray-800" role="progressbar" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-brand-500 transition-all" style={{width:`${percent}%`}}/></div></div>;
}
// One number with a caption and a one-line explanation. Every queue card on the catalogue page is
// read as a row of these, so the shape lives here instead of being retyped per card. ``brand`` marks
// the single number the operator acts on.
export function StatTile({label,value,hint,brand}:{label:string;value:number;hint:string;brand?:boolean}){
 return <div className={`rounded-xl p-4 ${brand?"bg-brand-50 dark:bg-brand-500/10":"bg-gray-50 dark:bg-gray-800"}`}><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value.toLocaleString()}</p><p className="mt-1 text-xs leading-5 text-gray-400">{hint}</p></div>;
}
// A named stage of a workflow. The index and summary line let a long page be read as a sequence
// of steps rather than a pile of equally weighted cards.
export function Section({id,index,title,summary,children}:{id:string;index?:string;title:string;summary?:ReactNode;children:ReactNode}){
 return <section id={id} className="scroll-mt-6 space-y-4"><div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 border-l-4 border-brand-500 pl-3"><h2 className="text-lg font-semibold text-gray-800 dark:text-white/90">{index&&<span className="mr-2 text-brand-500">{index}</span>}{title}</h2>{summary&&<p className="text-sm text-gray-500">{summary}</p>}</div>{children}</section>;
}
// Long tables are folded by default so a page stays readable; the row count stays visible in the
// header, so folding never hides how much data there is.
export function Collapsible({label,count,defaultOpen=false,children}:{label:string;count?:number;defaultOpen?:boolean;children:ReactNode}){
 const [open,setOpen]=useState(defaultOpen);
 return <div><button type="button" aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-gray-200 px-4 py-3 text-sm font-medium text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:text-gray-200 dark:hover:bg-gray-800"><span className="flex flex-wrap items-center gap-2">{open?"收起":"展开"}{label}{count!==undefined&&<span className="rounded bg-gray-100 px-1.5 py-0.5 text-xs text-gray-500 dark:bg-gray-700 dark:text-gray-400">{count.toLocaleString()} 条</span>}</span><Icon name="down" className={`size-4 shrink-0 transition ${open?"rotate-180":""}`}/></button>{open&&<div className="mt-4">{children}</div>}</div>;
}
