"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {Button,Card,Notice,TextArea} from "../bdhub/ui";

type Entry={direction:"inbound"|"outbound";text:string};
type Status={guide:{revision:number;body:string;hash:string};connection:{provider:string;model:string;endpoint:string;credentialConfigured:boolean;locale:string;enabled:boolean;runtimeState:string;rolloutStage:"transport_pending"|"pilot_required"|"pilot_running"|"pilot_complete"|"full";replyWindow:string[]};compiledPrompt:string};
type Decision={route:"reply"|"no_reply"|"request_detail"|"handoff";replyText:string|null;meaningZh:string;reasonSummaryZh:string;handoffReason:string|null};
type Simulation={decisionId:string;decision:Decision;input:{context:{messages:Entry[]}};cached:boolean};
const labels={reply:"AI 回复",no_reply:"无需回复",request_detail:"等待达人补充",handoff:"转人工"};

export default function AgentReplySettings({market}:{market:string}){
 const [status,setStatus]=useState<Status|null>(null),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [history,setHistory]=useState<Entry[]>([]),[next,setNext]=useState(""),[outbound,setOutbound]=useState("");
 const [trial,setTrial]=useState<Simulation|null>(null);
 const load=useCallback(async()=>{const response=await fetch(`/api/agent-replies?market=${market}`,{cache:"no-store"});if(!response.ok){setNotice("暂时无法读取 Agent 设置。");return;}const value=await response.json() as Status;setStatus(value);setBody(value.guide.body);},[market]);
 useEffect(()=>{void load();},[load]);
 const post=async(value:Record<string,unknown>)=>{const response=await fetch(`/api/agent-replies?market=${market}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...value,market})});if(!response.ok)throw Error();return response.json();};
 const save=async()=>{if(!status)return;setBusy(true);setNotice("");try{await post({action:"save-guide",expectedRevision:status.guide.revision,body});await load();setNotice("回复指南已保存为新版本；历史回复保留当时版本。");}catch{setNotice("未保存指南；版本可能已更新，请刷新后检查。");}finally{setBusy(false);}};
 const startRollout=async(action:"start-first"|"resume-full")=>{setBusy(true);setNotice("");try{await post({action,requestId:`agent-v2-${crypto.randomUUID()}`});await load();setNotice(action==="start-first"?"首条真实回复验证已在页面启动；将在回复窗口处理一条，之后等待你查看结果。":"持续自动回复已恢复；仍按回复窗口和发送门禁执行。");}catch{setNotice("启动状态没有更新，请刷新后核对当前阶段。");}finally{setBusy(false);}};
 const simulate=async()=>{const text=next.trim();if(!text)return;setBusy(true);setNotice("");const input:Entry[]=[...history,{direction:"inbound",text}];try{const value=await post({action:"simulate",history:input}) as Simulation;setTrial(value);setHistory(value.decision.replyText?[...input,{direction:"outbound",text:value.decision.replyText}]:input);setNext("");}catch{setNotice("试聊没有得到有效结果；未发送给达人，也没有改变真实队列。");}finally{setBusy(false);}};
 return <div className="space-y-5">
  <Notice>这里展示实际模型接入、回复指南和模型输入。试聊不会发送消息；正式开关和回复窗口在<Link className="font-medium underline" href={`/${market}/ops/jobs`}>运行与设置 → 作业与定时</Link>。</Notice>
  <Card title="模型接入与运行状态"><div className="grid gap-2 p-5 text-sm md:grid-cols-2">{status?<><p>服务商：{status.connection.provider}</p><p>模型：{status.connection.model}</p><p className="break-all md:col-span-2">API：{status.connection.endpoint}</p><p>密钥：{status.connection.credentialConfigured?"本机已配置":"本机未配置"}</p><p>语言：{status.connection.locale}</p><p>自动回复：{status.connection.enabled?"已开启":"已关闭"}</p><p>执行状态：{status.connection.runtimeState==="market_agent_transport_pending"?"当前市场真实回复尚未验收":status.connection.runtimeState==="disabled"?"已暂停":status.connection.runtimeState==="outside_reply_window"?"等待回复窗口":status.connection.runtimeState==="failed"?"运行异常":status.connection.runtimeState}</p><p>北京时间：{status.connection.replyWindow.join("–")}</p></>:<p>读取中…</p>}</div></Card>
  {status?.connection.enabled&&status.connection.rolloutStage==="pilot_required"&&<Card title="首条真实回复验证"><div className="space-y-3 p-5 text-sm"><p>点击后，系统会在回复窗口处理首条合格消息；首条送达后暂停，等待你查看结果。历史试聊和保存指南不会触发此动作。</p><Button disabled={busy} onClick={()=>void startRollout("start-first")}>开始首条真实回复验证</Button></div></Card>}
  {status?.connection.enabled&&status.connection.rolloutStage==="pilot_running"&&<Notice>首条真实回复验证已启动；完成首条送达后会暂停，等待你查看结果。</Notice>}
  {status?.connection.enabled&&status.connection.rolloutStage==="pilot_complete"&&<Card title="首条回复已送达"><div className="space-y-3 p-5 text-sm"><p>首条真实回复已确认送达。查看会话中的实际输入、回复和回执后，可继续按窗口自动回复。</p><Button disabled={busy} onClick={()=>void startRollout("resume-full")}>继续自动回复</Button></div></Card>}
  <Card title="回复指南" subtitle={status?`当前生效版本 ${status.guide.revision} · ${status.guide.hash.slice(0,10)}`:"读取中…"}><div className="space-y-3 p-5"><p className="text-sm text-gray-500">参考处理方式进入模型提示词。保存新版本后，历史处理记录仍保留当时版本。</p><TextArea className="min-h-[360px] font-mono text-xs leading-5" value={body} onChange={event=>setBody(event.target.value)}/><Button disabled={busy||!status||body===status.guide.body||body.trim().length<500} onClick={()=>void save()}>保存新版本</Button><details className="rounded-lg border border-gray-200 p-3 text-xs dark:border-gray-700"><summary className="cursor-pointer font-medium">查看当前实际传给模型的完整提示词</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-gray-500">{status?.compiledPrompt??""}</pre></details></div></Card>
  <Card title="多轮试聊" subtitle="可以先加入我们已发的邀请，再连续输入达人的追问。"><div className="space-y-3 p-5">{history.length>0&&<div className="max-h-80 space-y-2 overflow-auto rounded-lg bg-gray-50 p-3 text-sm dark:bg-gray-800">{history.map((entry,index)=><p key={index} className="whitespace-pre-wrap"><strong>{entry.direction==="inbound"?"达人":"我们"}：</strong>{entry.text}</p>)}</div>}<div className="flex flex-wrap gap-2"><input className="min-w-0 flex-1 rounded-lg border border-gray-300 bg-transparent px-3 py-2 text-sm dark:border-gray-700" placeholder="可选：加入我们此前已发的消息" value={outbound} onChange={event=>setOutbound(event.target.value)}/><Button size="sm" variant="outline" disabled={busy||!outbound.trim()||history.length>=19} onClick={()=>{setHistory(current=>[...current,{direction:"outbound",text:outbound.trim()}]);setOutbound("");setTrial(null);}}>加入已发消息</Button></div><TextArea className="min-h-24" placeholder="输入一条达人消息" value={next} onChange={event=>setNext(event.target.value)}/><div className="flex gap-2"><Button disabled={busy||!next.trim()||history.length>=19} onClick={()=>void simulate()}>{busy?"试答中…":"生成试答"}</Button><Button variant="outline" disabled={busy||history.length===0} onClick={()=>{setHistory([]);setTrial(null);setNext("");}}>清空试聊</Button></div>{trial&&<div className="space-y-2 rounded-lg border border-gray-200 p-4 text-sm dark:border-gray-700"><p className="font-semibold">结果：{labels[trial.decision.route]}</p><p>中文理解：{trial.decision.meaningZh}</p><p>判断依据：{trial.decision.reasonSummaryZh}</p>{trial.decision.handoffReason&&<p>转人工原因：{trial.decision.handoffReason}</p>}{trial.decision.replyText&&<p className="whitespace-pre-wrap rounded-lg bg-gray-50 p-3 dark:bg-gray-800">回复：{trial.decision.replyText}</p>}<details className="text-xs text-gray-500"><summary className="cursor-pointer">查看此次模型输入与记录号</summary><p className="mt-2">{trial.decisionId}</p><pre className="max-h-72 overflow-auto whitespace-pre-wrap">{JSON.stringify(trial.input.context,null,2)}</pre></details></div>}</div></Card>
  {notice&&<Notice tone="warning">{notice}</Notice>}{market==="it"&&<details id="reply-evaluation" className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><summary className="cursor-pointer text-sm">历史五动作评测</summary><p className="mt-3 text-sm text-gray-500">旧分类评测保留在历史文档；其真值和固定模板不再作为新版自动回复的运行依据。</p></details>}
 </div>;
}
