"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button,Card,Field,Input,Notice,PageHeading,Pill,Select,TextArea} from "../bdhub/ui";
import type {CollaborationStatus,ConversationDetail,ConversationList,ConversationView} from "../../server/conversations/bridge";
import type {AgentTemplate,TemplateLibraryState} from "../../server/template-library/bridge";
import ReplyReviewPanel from "../second-outreach/ReplyReviewPanel";
import MarketContentPanel from "../markets/MarketContentPanel";

export type ConversationSection="conversations"|"templates"|"agent";
const nav=[{id:"conversations",label:"会话"},{id:"templates",label:"人工回复模板"},{id:"agent",label:"Agent AI 回复设置"}] as const;
const views:{id:ConversationView;label:string}[]=[{id:"human",label:"需人工"},{id:"agent",label:"Agent 回复"},{id:"completed",label:"已完成"},{id:"all",label:"全部"}];
const collaboration:{value:CollaborationStatus;label:string}[]=[{value:"normal",label:"正常"},{value:"collaborated",label:"达成过"},{value:"paid",label:"付费"},{value:"rejected",label:"拒绝"}];
const fmt=(stamp:number)=>stamp?new Date(stamp*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"—";
const metric=(value:string|number|null)=>value==null?"—":typeof value==="number"?value.toLocaleString("zh-CN"):value;

function ConversationDesk({market}:{market:string}){
 const [view,setView]=useState<ConversationView>("human"),[query,setQuery]=useState(""),[list,setList]=useState<ConversationList|null>(null),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<ConversationDetail|null>(null),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[translations,setTranslations]=useState<Record<string,string>>({}),[translationBusy,setTranslationBusy]=useState<string|null>(null);
 const textIds=useRef(new Map<string,string>()),cardIds=useRef(new Map<string,string>()),statusIds=useRef(new Map<string,string>());
 const loadList=useCallback(async()=>{const response=await fetch(`/api/conversations?market=${encodeURIComponent(market)}&view=${view}&query=${encodeURIComponent(query)}`,{cache:"no-store"});if(!response.ok){setError("暂时无法读取会话队列。");return;}const value:ConversationList=await response.json();setList(value);setError("");if(!selected&&value.items[0]?.conversationId)setSelected(value.items[0].conversationId);else if(selected&&!value.items.some(item=>item.conversationId===selected))setSelected(value.items[0]?.conversationId??null);},[market,view,query,selected]);
 const loadDetail=useCallback(async(cid:string)=>{const response=await fetch(`/api/conversations?market=${encodeURIComponent(market)}&cid=${cid}`,{cache:"no-store"});if(!response.ok){setError("暂时无法读取会话内容。");return;}const value:ConversationDetail=await response.json();setDetail(value);setDraft(value.draft.text);setTranslations({});},[market]);
 useEffect(()=>{void loadList();},[loadList]);useEffect(()=>{if(selected)void loadDetail(selected);else setDetail(null);},[selected,loadDetail]);
 const post=async(body:Record<string,unknown>)=>{const response=await fetch(`/api/conversations?market=${encodeURIComponent(market)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw Error();return response.json();};
 const saveDraft=async()=>{if(!detail)return;setBusy(true);try{await post({action:"save_draft",cid:detail.conversationId,text:draft,expectedRevision:detail.draft.revision});await loadDetail(detail.conversationId);}catch{setError("草稿状态已经变化，请刷新后重试。");}finally{setBusy(false);}};
 const translate=async()=>{if(!draft.trim())return;setBusy(true);try{const value=await post({action:"translate",target:"it",text:draft});setDraft(value.translation);}catch{setError("翻译没有完成，原草稿已保留。");}finally{setBusy(false);}};
 const sendText=async()=>{if(!detail||!draft.trim())return;setBusy(true);const key=detail.conversationId,requestId=textIds.current.get(key)??`manual-${crypto.randomUUID()}`;textIds.current.set(key,requestId);try{await post({action:"send_text",cid:key,text:draft,expectedControlRevision:detail.creator.revision,requestId});textIds.current.delete(key);setDraft("");await loadDetail(key);}catch{setError("人工消息未确认发送；再次操作只核验同一意图。");}finally{setBusy(false);}};
 const sendCard=async(episodeId:string)=>{if(!detail)return;setBusy(true);const key=`${detail.conversationId}:${episodeId}`,requestId=cardIds.current.get(key)??`manual-card-${crypto.randomUUID()}`;cardIds.current.set(key,requestId);try{await post({action:"send_card",cid:detail.conversationId,episodeId,expectedControlRevision:detail.creator.revision,requestId});cardIds.current.delete(key);await loadDetail(detail.conversationId);}catch{setError("商品卡未确认发送；再次操作只核验同一意图。");}finally{setBusy(false);}};
 const translateInbound=async(id:string,text:string)=>{setTranslationBusy(id);try{const value=await post({action:"translate",target:"zh",text});setTranslations(current=>({...current,[id]:value.translation}));}catch{setError("达人消息暂时无法翻译，原文已保留。");}finally{setTranslationBusy(null);}};
 const confirmManual=async()=>{if(!detail?.case)return;setBusy(true);try{await post({action:"confirm_manual_reply",cid:detail.conversationId,caseId:detail.case.id,turnId:detail.case.turnId,virtual:detail.case.virtual,expectedControlRevision:detail.creator.revision,expectedPendingRevision:detail.case.pendingRevision});setSelected(null);await loadList();}catch{setError("事项状态已变化，请刷新后重试。");}finally{setBusy(false);}};
 const setStatus=async(status:CollaborationStatus)=>{if(!detail)return;setBusy(true);const key=detail.conversationId,requestId=statusIds.current.get(key)??`collaboration-${crypto.randomUUID()}`;statusIds.current.set(key,requestId);try{await post({action:"set_collaboration",cid:key,status,expectedStatusRevision:detail.creator.collaboration.revision,expectedControlRevision:detail.creator.revision,requestId});statusIds.current.delete(key);await loadDetail(key);}catch{setError("合作状态未保存；另一窗口可能已经更新，请刷新。");}finally{setBusy(false);}};
 return <div className="grid gap-3 xl:h-[calc(100dvh-220px)] xl:min-h-[680px] xl:grid-cols-[280px_minmax(340px,1fr)_320px]">
  <Card className="flex min-h-0 flex-col overflow-hidden" title="会话队列" action={<Pill tone="warning">默认需人工</Pill>}><div className="flex min-h-0 flex-1 flex-col gap-3 p-3"><Input placeholder="搜索达人、OECID或消息" value={query} onChange={event=>setQuery(event.target.value)}/><div className="flex flex-wrap gap-1">{views.map(item=><Button key={item.id} size="sm" variant={view===item.id?"primary":"ghost"} onClick={()=>{setView(item.id);setSelected(null);}}>{item.label} {list?.counts[item.id]??0}</Button>)}</div><div className="min-h-0 flex-1 space-y-2 overflow-y-auto">{list?.items.map(item=><button type="button" key={item.creatorId} onClick={()=>item.conversationId&&setSelected(item.conversationId)} className={`w-full rounded-xl border p-3 text-left ${selected===item.conversationId?"border-brand-400 bg-brand-50 dark:bg-brand-500/10":"border-gray-200 dark:border-gray-700"}`}><div className="flex items-center justify-between gap-2"><strong className="truncate text-sm">@{item.handle??`…${item.oec.slice(-8)}`}</strong>{item.unread&&<span className="shrink-0 rounded bg-brand-50 px-1.5 py-0.5 text-[10px] font-medium text-brand-600 dark:bg-brand-500/10">待回复</span>}</div>{item.humanReasonLabel&&<p className="mt-1 text-xs font-medium text-warning-600">{item.humanReasonLabel}</p>}<p className="mt-1 line-clamp-2 text-xs text-gray-500">{item.latestText??"暂无正文"}</p><p className="mt-1 text-[11px] text-gray-400">等待 {Math.floor(item.waitingSeconds/3600)} 小时 · {fmt(item.latestAt)}</p></button>)}{list&&!list.items.length&&<p className="py-10 text-center text-sm text-gray-500">当前没有这一类会话。</p>}</div></div></Card>
  <Card className="flex min-h-0 flex-col overflow-hidden" title={detail?`@${detail.creator.handle??detail.creator.oec}`:"选择一条会话"} subtitle={detail?`OECID ${detail.creator.oec}`:"默认从需人工队列开始"}><div className="flex min-h-0 flex-1 flex-col p-4">{detail?<><div className="min-h-0 flex-1 space-y-3 overflow-y-auto">{detail.timeline.map(item=><div key={item.id} className={`flex ${item.direction==="outbound"?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-xl px-3 py-2 text-sm leading-6 ${item.direction==="outbound"?"bg-brand-500 text-white":"bg-gray-100 dark:bg-gray-800"}`}><p className="whitespace-pre-wrap">{item.text??"[图片或暂不支持的消息]"}</p>{item.direction==="inbound"&&item.text&&<button disabled={translationBusy===item.id} onClick={()=>void translateInbound(item.id,item.text!)} className="mt-1 text-[11px] font-medium text-brand-600">{translationBusy===item.id?"翻译中…":translations[item.id]?"重新翻译":"翻译成中文"}</button>}{translations[item.id]&&<p className="mt-2 rounded-lg bg-white/70 p-2 text-xs text-gray-600 dark:bg-gray-900">中文：{translations[item.id]}</p>}<p className="mt-1 text-[10px] opacity-60">{item.source} · {fmt(item.occurredAt)} · {item.status}</p></div></div>)}</div><div className="mt-3 border-t border-gray-200 pt-3 dark:border-gray-700"><div className="mb-2 flex flex-wrap gap-2"><Select className="max-w-56" defaultValue="" onChange={event=>{const value=detail.manualTemplates.find(row=>row.id===event.target.value);if(value)setDraft(text=>text?`${text}\n${value.body}`:value.body);}}><option value="">插入人工回复模板</option>{detail.manualTemplates.map(row=><option key={row.id} value={row.id}>{row.category} · {row.name}</option>)}</Select><Button size="sm" variant="outline" disabled={busy||!detail.episodes.length} onClick={()=>detail.episodes[0]&&void sendCard(detail.episodes[0].episodeId)}>发送最近商品卡</Button><Button size="sm" variant="outline" disabled title="当前适配器没有安全图片写端点">图片</Button><Button size="sm" variant="outline" disabled={busy||!draft.trim()} onClick={()=>void translate()}>中→意翻译</Button></div><TextArea className="min-h-24" value={draft} onChange={event=>setDraft(event.target.value)}/><div className="mt-2 flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={()=>void saveDraft()}>保存草稿</Button><Button disabled={busy||!draft.trim()} onClick={()=>void sendText()}>发送文本</Button></div></div></>:<p className="m-auto text-sm text-gray-500">选择左侧会话查看时间线。</p>}</div></Card>
  <Card className="flex min-h-0 flex-col overflow-hidden" title="达人与事项"><div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-4">{detail?<>{detail.case&&<Notice tone="warning"><strong>需要人工：{detail.case.reasonLabel}</strong><br/>核对完成后可直接确认事项；确认本身不会发送消息。</Notice>}<Field label="合作状态" hint={detail.creator.collaboration.source==="manual"?"人工设置优先，自动事件不会覆盖。":"系统默认；加橱窗可自动升级为达成过。"}><Select value={detail.creator.collaboration.status} disabled={busy} onChange={event=>void setStatus(event.target.value as CollaborationStatus)}>{collaboration.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>{detail.case&&<Button size="sm" disabled={busy} onClick={()=>void confirmManual()}>确认人工回复</Button>}<div className="grid grid-cols-2 gap-2">{[["GMV",metric(detail.metrics.gmv)],["粉丝",metric(detail.metrics.followers)],["视频 GMV",metric(detail.metrics.videoGmv)],["直播 GMV",metric(detail.metrics.liveGmv)],["销量",metric(detail.metrics.unitsSold)],["视频均播",metric(detail.metrics.avgVideoViews)],["达人回复",`${detail.metrics.replyCount} 条`],["加橱窗",`${detail.metrics.showcaseCount} 次`]].map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><p className="text-[11px] text-gray-400">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><p className="text-[11px] text-gray-400">画像更新：{detail.metrics.observedAt?new Date(detail.metrics.observedAt).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"尚无画像"}</p>{detail.episodes.map(row=><div key={row.episodeId} className="rounded-lg border border-gray-200 p-3 text-xs dark:border-gray-700"><p>PID {row.pid}</p><p className="mt-1 text-gray-500">listId …{row.listId.slice(-8)} · {fmt(row.sentAt)}</p></div>)}</>:<p className="text-sm text-gray-500">选择会话后显示达人、合作状态和商品。</p>}</div></Card>
  {error&&<div className="xl:col-span-3"><Notice tone="warning">{error}</Notice></div>}
 </div>;
}

function ManualTemplates(){const [data,setData]=useState<TemplateLibraryState|null>(null),[name,setName]=useState(""),[category,setCategory]=useState("常用"),[body,setBody]=useState(""),[message,setMessage]=useState("");const load=async()=>{const response=await fetch("/api/template-library",{cache:"no-store"});if(response.ok)setData(await response.json());};useEffect(()=>{void load();},[]);const save=async()=>{const response=await fetch("/api/template-library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsert_manual",requestId:`manual-${crypto.randomUUID()}`,templateId:null,expectedRevision:null,name,category,body})});if(response.ok){setData(await response.json());setName("");setBody("");setMessage("模板已保存。");}else setMessage("模板未保存。");};return <Card title="人工回复模板" subtitle="仅供人工插入草稿；不被持续二发或 Agent 读取。"><div className="grid gap-5 p-5 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{data?.manualTemplates.map(row=><div key={row.id} className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><p className="text-xs text-gray-400">{row.category}</p><p className="mt-1 font-medium">{row.name}</p><p className="mt-2 text-sm leading-6 text-gray-500">{row.body}</p></div>)}</div><div className="space-y-3"><Field label="模板名称"><Input value={name} onChange={event=>setName(event.target.value)}/></Field><Field label="分类"><Input value={category} onChange={event=>setCategory(event.target.value)}/></Field><Field label="正文"><TextArea value={body} onChange={event=>setBody(event.target.value)}/></Field><Button disabled={!name.trim()||!body.trim()} onClick={()=>void save()}>保存人工模板</Button>{message&&<Notice>{message}</Notice>}</div></div></Card>;}

function AgentSettings(){const [data,setData]=useState<TemplateLibraryState|null>(null),[drafts,setDrafts]=useState<Record<string,string>>({}),[message,setMessage]=useState("");const load=async()=>{const response=await fetch("/api/template-library",{cache:"no-store"});if(response.ok){const value:TemplateLibraryState=await response.json();setData(value);setDrafts(Object.fromEntries(value.agentTemplates.map(row=>[row.id,row.text])));}};useEffect(()=>{void load();},[]);const save=async(row:AgentTemplate)=>{const response=await fetch("/api/template-library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update_agent",templateKey:row.id,expectedRevision:row.revision,body:drafts[row.id]})});if(response.ok){const value=await response.json();setData(value);setDrafts(Object.fromEntries(value.agentTemplates.map((item:AgentTemplate)=>[item.id,item.text])));setMessage("固定模板新 revision 已保存；历史 intent 保持原正文。");}else setMessage("模板未保存，revision 可能已变化。");};return <div className="space-y-5"><Notice>Agent 动作名固定，只有三条受控正文可以版本化编辑。开关、集中回复时间和运行状态已迁到“运行与设置 → 作业与定时”。</Notice><div className="grid gap-4 xl:grid-cols-3">{data?.agentTemplates.map(row=><Card key={row.id} title={{sample_self_service:"样品/物流自助",collaboration_ack:"合作确认",link_usage:"唯一链接用法"}[row.action]??row.action} subtitle={`${row.action} · revision ${row.revision}`}><div className="space-y-3 p-4"><TextArea value={drafts[row.id]??row.text} onChange={event=>setDrafts(current=>({...current,[row.id]:event.target.value}))}/><Button size="sm" disabled={(drafts[row.id]??row.text)===row.text} onClick={()=>void save(row)}>保存新 revision</Button></div></Card>)}</div>{message&&<Notice tone={message.includes("已保存")?"success":"warning"}>{message}</Notice>}<details id="reply-evaluation" className="rounded-xl border border-gray-200 p-4 dark:border-gray-800"><summary className="cursor-pointer text-sm font-medium">高级：回复策略评测</summary><div className="mt-5"><ReplyReviewPanel/></div></details></div>;}

export default function ConversationWorkspace({section,market="it"}:{section:ConversationSection;market?:string}){return <div className="space-y-5"><PageHeading title="会话" description="处理真实会话、人工模板与 Agent 固定场景。" action={<Pill tone="warning">默认：需人工</Pill>}/><nav className="flex gap-1 overflow-x-auto rounded-xl bg-gray-100 p-1 dark:bg-gray-800">{nav.map(item=><Link key={item.id} href={item.id==="conversations"?`/${market}/conversations`:`/${market}/conversations/${item.id}`} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-medium ${section===item.id?"bg-white shadow dark:bg-gray-700":"text-gray-500"}`}>{item.label}</Link>)}</nav>{section==="conversations"?<ConversationDesk market={market}/>:market!=="it"?<MarketContentPanel market={market}/>:section==="templates"?<ManualTemplates/>:<AgentSettings/>}</div>;}
