"use client";

import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button,Card,Dialog,Field,Input,MetricTable,Notice,PageHeading,Pill,Select,TextArea,Toggle} from "../bdhub/ui";
import type {ConversationDetail,ConversationList,ConversationView} from "../../server/conversations/bridge";
import type {AgentSetting,TemplateLibraryState} from "../../server/template-library/bridge";

export type ConversationSection="conversations"|"templates"|"agent";
const nav=[{id:"conversations",label:"会话"},{id:"templates",label:"人工回复模板"},{id:"agent",label:"Agent AI 回复设置"}] as const;
const views:{id:ConversationView;label:string}[]=[{id:"human",label:"需人工"},{id:"processing",label:"处理中"},{id:"agent",label:"Agent 已处理"},{id:"completed",label:"已完成"},{id:"all",label:"全部"}];
const fmt=(stamp:number)=>stamp?new Date(stamp*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"—";
const metric=(value:string|number|null)=>value==null?"—":typeof value==="number"?value.toLocaleString("zh-CN"):value;

function ConversationDesk(){
 const [view,setView]=useState<ConversationView>("human");
 const [query,setQuery]=useState("");
 const [list,setList]=useState<ConversationList|null>(null);
 const [selected,setSelected]=useState<string|null>(null);
 const [detail,setDetail]=useState<ConversationDetail|null>(null);
 const [draft,setDraft]=useState("");
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState("");
 const [translations,setTranslations]=useState<Record<string,string>>({});
 const [translationBusy,setTranslationBusy]=useState<string|null>(null);
 const [rejectOpen,setRejectOpen]=useState(false);
 const textRequestIds=useRef(new Map<string,string>());
 const cardRequestIds=useRef(new Map<string,string>());
 const rejectRequestIds=useRef(new Map<string,string>());

 const loadList=useCallback(async()=>{
  const response=await fetch(`/api/conversations?view=${view}&query=${encodeURIComponent(query)}`,{cache:"no-store"});
  if(!response.ok){setError("暂时无法读取会话队列。");return;}
  const value:ConversationList=await response.json();setList(value);setError("");
  if(!selected&&value.items[0]?.conversationId)setSelected(value.items[0].conversationId);
  else if(selected&&!value.items.some(item=>item.conversationId===selected))setSelected(value.items[0]?.conversationId??null);
 },[view,query,selected]);
 const loadDetail=useCallback(async(cid:string)=>{
  const response=await fetch(`/api/conversations?cid=${cid}`,{cache:"no-store"});
  if(!response.ok){setError("暂时无法读取会话内容。");return;}
  const value:ConversationDetail=await response.json();setDetail(value);setDraft(value.draft.text);setTranslations({});
 },[]);
 useEffect(()=>{void loadList();},[loadList]);
 useEffect(()=>{if(selected)void loadDetail(selected);else setDetail(null);},[selected,loadDetail]);

 const saveDraft=async()=>{if(!detail)return;setBusy(true);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_draft",cid:detail.conversationId,text:draft,expectedRevision:detail.draft.revision})});if(!response.ok)throw Error();await loadDetail(detail.conversationId);}catch{setError("草稿状态已经变化，请刷新后重试。");}finally{setBusy(false);}};
 const translate=async()=>{if(!draft.trim())return;setBusy(true);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"translate",target:"it",text:draft})});if(!response.ok)throw Error();const value=await response.json();setDraft(value.translation);}catch{setError("翻译没有完成，原草稿已保留。");}finally{setBusy(false);}};
 const sendText=async()=>{if(!detail||!draft.trim())return;setBusy(true);const key=detail.conversationId;const requestId=textRequestIds.current.get(key)??`manual-${crypto.randomUUID()}`;textRequestIds.current.set(key,requestId);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"send_text",cid:key,text:draft,expectedControlRevision:detail.creator.revision,requestId})});if(!response.ok)throw Error();setDraft("");textRequestIds.current.delete(key);await loadDetail(key);await loadList();}catch{setError("人工消息未确认发送；再次操作只会核验同一意图，不会创建新的重发意图。");}finally{setBusy(false);}};
 const sendCard=async(episodeId:string)=>{if(!detail)return;setBusy(true);const key=`${detail.conversationId}:${episodeId}`;const requestId=cardRequestIds.current.get(key)??`manual-card-${crypto.randomUUID()}`;cardRequestIds.current.set(key,requestId);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"send_card",cid:detail.conversationId,episodeId,expectedControlRevision:detail.creator.revision,requestId})});if(!response.ok)throw Error();cardRequestIds.current.delete(key);await loadDetail(detail.conversationId);}catch{setError("商品卡未确认发送；再次操作只会核验同一意图，不会创建新的重发意图。");}finally{setBusy(false);}};
 const translateInbound=async(id:string,text:string)=>{setTranslationBusy(id);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"translate",target:"zh",text})});if(!response.ok)throw Error();const value=await response.json();setTranslations(current=>({...current,[id]:value.translation}));}catch{setError("达人消息暂时无法翻译，原文已保留。");}finally{setTranslationBusy(null);}};
 const confirmManual=async()=>{if(!detail?.case||!detail.manualReply)return;setBusy(true);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"confirm_manual_reply",cid:detail.conversationId,caseId:detail.case.id,turnId:detail.case.turnId,virtual:detail.case.virtual,expectedControlRevision:detail.creator.revision,expectedPendingRevision:detail.case.pendingRevision})});if(!response.ok)throw Error();setSelected(null);await loadList();}catch{setError("尚未找到本条达人消息之后已确认送达的人工回复，或事项状态已变化。");}finally{setBusy(false);}};
 const rejectCreator=async()=>{if(!detail)return;setBusy(true);const key=detail.conversationId;const requestId=rejectRequestIds.current.get(key)??`manual-reject-${crypto.randomUUID()}`;rejectRequestIds.current.set(key,requestId);try{const response=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reject_creator",cid:key,expectedControlRevision:detail.creator.revision,requestId})});if(!response.ok)throw Error();rejectRequestIds.current.delete(key);setRejectOpen(false);setSelected(null);await loadList();}catch{setError("拒绝标签未保存；达人控制状态可能已经变化，请刷新后重试。");}finally{setBusy(false);}};

 return <>
  <div className="grid gap-3 lg:h-[calc(100dvh-220px)] lg:min-h-[680px] lg:grid-cols-[300px_minmax(0,1fr)_330px] 2xl:grid-cols-[320px_minmax(0,1fr)_360px]">
   <Card className="flex min-h-0 flex-col overflow-hidden" title="会话队列" action={<Pill tone="warning">默认需人工</Pill>}>
    <div className="flex min-h-0 flex-1 flex-col gap-3 p-3"><Input placeholder="搜索达人、OECID或消息" value={query} onChange={event=>setQuery(event.target.value)}/><div className="flex flex-wrap gap-1">{views.map(item=><Button key={item.id} size="sm" variant={view===item.id?"primary":"ghost"} onClick={()=>{setView(item.id);setSelected(null);}}>{item.label} {list?.counts[item.id]??0}</Button>)}</div><div className="min-h-0 flex-1 space-y-2 overflow-y-auto pr-1">{list?.items.map(item=><button type="button" key={item.creatorId} onClick={()=>item.conversationId&&setSelected(item.conversationId)} className={`w-full rounded-xl border p-3 text-left ${selected===item.conversationId?"border-brand-400 bg-brand-50 dark:bg-brand-500/10":"border-gray-200 dark:border-gray-700"}`}><div className="flex items-center justify-between gap-2"><strong className="truncate text-sm">@{item.handle??`…${item.oec.slice(-8)}`}</strong>{item.state==="human"&&<Pill tone="warning">需人工</Pill>}</div>{item.humanReasonLabel&&<p className="mt-1 text-xs font-medium text-warning-600">{item.humanReasonLabel}</p>}<p className="mt-1 line-clamp-2 text-xs leading-5 text-gray-500">{item.latestText??"暂无正文"}</p><p className="mt-1 text-[11px] text-gray-400">等待 {Math.floor(item.waitingSeconds/3600)} 小时 · {fmt(item.latestAt)}</p></button>)}{list&&list.items.length===0&&<p className="py-10 text-center text-sm text-gray-500">当前没有这一类会话。</p>}</div></div>
   </Card>
   <Card className="flex min-h-0 flex-col overflow-hidden" title={detail?`@${detail.creator.handle??detail.creator.oec}`:"选择一条会话"} subtitle={detail?`OECID ${detail.creator.oec}`:"默认从需人工队列开始"}>
    <div className="flex min-h-0 flex-1 flex-col p-4">{detail?<><div className="min-h-0 flex-1 space-y-3 overflow-y-auto pr-1">{detail.timeline.map(item=>{const translated=translations[item.id];return <div key={item.id} className={`flex ${item.direction==="outbound"?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-xl px-3 py-2 text-sm leading-6 ${item.direction==="outbound"?"bg-brand-500 text-white":"bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200"}`}><p className="whitespace-pre-wrap">{item.text??(item.kind==="attachment_or_unsupported"?"[图片或附件]":"[暂不支持的消息]")}</p>{item.direction==="inbound"&&item.text&&<button type="button" disabled={translationBusy===item.id} onClick={()=>void translateInbound(item.id,item.text!)} className="mt-1 text-[11px] font-medium text-brand-600 hover:text-brand-700 disabled:opacity-50 dark:text-brand-300">{translationBusy===item.id?"翻译中…":translated?"重新翻译":"翻译成中文"}</button>}{translated&&<div className="mt-2 rounded-lg border border-brand-100 bg-white/80 px-3 py-2 text-xs leading-5 text-gray-600 dark:border-brand-900 dark:bg-gray-900/60 dark:text-gray-300"><span className="font-medium text-brand-600 dark:text-brand-300">中文：</span>{translated}</div>}<p className={`mt-1 text-[10px] ${item.direction==="outbound"?"text-white/70":"text-gray-400"}`}>{item.source} · {fmt(item.occurredAt)} · {item.status}</p></div></div>;})}</div><div className="mt-3 shrink-0 border-t border-gray-200 pt-3 dark:border-gray-700"><div className="mb-2 flex flex-wrap gap-2"><Select className="max-w-56" defaultValue="" onChange={event=>{const value=detail.manualTemplates.find(row=>row.id===event.target.value);if(value)setDraft(text=>text?`${text}\n${value.body}`:value.body);}}><option value="">插入人工回复模板</option>{detail.manualTemplates.map(row=><option key={row.id} value={row.id}>{row.category} · {row.name}</option>)}</Select><Button size="sm" variant="outline" disabled={busy||!detail.episodes.length} onClick={()=>detail.episodes[0]&&void sendCard(detail.episodes[0].episodeId)}>发送最近商品卡</Button><Button size="sm" variant="outline" disabled title="当前意大利发送适配器尚未提供图片写入端点">图片</Button><Button size="sm" variant="outline" disabled={busy||!draft.trim()} onClick={()=>void translate()}>中→意翻译</Button></div><TextArea className="min-h-24" value={draft} onChange={event=>setDraft(event.target.value)} placeholder="输入人工回复；Enter 换行"/><div className="mt-2 flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={()=>void saveDraft()}>保存草稿</Button><Button disabled={busy||!draft.trim()} onClick={()=>void sendText()}>{busy?"处理中…":"发送文本"}</Button></div></div></>:<p className="m-auto text-sm text-gray-500">选择左侧会话查看时间线。</p>}</div>
   </Card>
   <Card className="flex min-h-0 flex-col overflow-hidden" title="达人与事项"><div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-4">{detail?<>{detail.case&&<Notice tone="warning"><strong>需要人工：{detail.case.reasonLabel}</strong><br/>人工回复确认后结束本事项，或由你手工标记拒绝合作。</Notice>}{detail.creator.rejected&&<Notice tone="warning"><strong>已标记拒绝合作</strong><br/>该达人后续所有商品线索都不会进入发送池。</Notice>}<div className="flex flex-wrap gap-2">{detail.case&&<Button size="sm" disabled={busy||!detail.manualReply} title={detail.manualReply?"确认本条人工回复已完成":"请先在当前会话发送并确认一条人工回复"} onClick={()=>void confirmManual()}>确认人工回复</Button>}<Button size="sm" variant="danger" disabled={busy||detail.creator.rejected} onClick={()=>setRejectOpen(true)}>{detail.creator.rejected?"已拒绝合作":"标记拒绝合作"}</Button></div>{detail.case&&!detail.manualReply&&<p className="text-xs leading-5 text-gray-500">发送文本或商品卡并完成平台回查后，“确认人工回复”按钮才会可用。</p>}<div className="grid grid-cols-2 gap-2">{[["GMV",metric(detail.metrics.gmv)],["粉丝",metric(detail.metrics.followers)],["视频 GMV",metric(detail.metrics.videoGmv)],["直播 GMV",metric(detail.metrics.liveGmv)],["销量",metric(detail.metrics.unitsSold)],["视频均播",metric(detail.metrics.avgVideoViews)],["达人回复",`${detail.metrics.replyCount} 条`],["加橱窗",`${detail.metrics.showcaseCount} 次`]].map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><p className="text-[11px] text-gray-400">{label}</p><p className="mt-1 break-words text-sm font-semibold text-gray-800 dark:text-gray-200">{value}</p></div>)}</div><p className="text-[11px] text-gray-400">画像更新：{detail.metrics.observedAt?new Date(detail.metrics.observedAt).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false}):"尚无画像"}</p><div className="space-y-2">{detail.episodes.map(row=><div key={row.episodeId} className="rounded-lg border border-gray-200 p-3 text-xs dark:border-gray-700"><p>PID {row.pid}</p><p className="mt-1 text-gray-500">listId …{row.listId.slice(-8)} · {fmt(row.sentAt)}</p><Button className="mt-2" size="sm" variant="outline" disabled={busy} onClick={()=>void sendCard(row.episodeId)}>发送此商品卡</Button></div>)}</div></>:<p className="text-sm text-gray-500">选择会话后显示达人、商品与人工原因。</p>}</div></Card>
   {error&&<div className="lg:col-span-3"><Notice tone="warning">{error}</Notice></div>}
  </div>
  <Dialog open={rejectOpen} onClose={()=>setRejectOpen(false)} title="标记达人拒绝合作" description="这是人工判断：保存后，这位达人名下所有商品线索都会退出发送池。">
   <div className="space-y-4"><Notice tone="warning">此操作不会发送消息，但会永久写入当前达人关系控制。后续如需恢复，需要由运营明确取消拒绝状态。</Notice><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setRejectOpen(false)}>取消</Button><Button variant="danger" disabled={busy} onClick={()=>void rejectCreator()}>{busy?"保存中…":"确认标记拒绝"}</Button></div></div>
  </Dialog>
 </>;
}

function ManualTemplates(){
 const [data,setData]=useState<TemplateLibraryState|null>(null),[name,setName]=useState(""),[category,setCategory]=useState("常用"),[body,setBody]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const response=await fetch("/api/template-library",{cache:"no-store"});if(response.ok)setData(await response.json());};useEffect(()=>{void load();},[]);
 const save=async()=>{const response=await fetch("/api/template-library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsert_manual",requestId:`manual-${crypto.randomUUID()}`,templateId:null,expectedRevision:null,name,category,body})});if(response.ok){setData(await response.json());setName("");setBody("");setMessage("模板已保存。");}else setMessage("模板未保存。");};
 return <Card title="人工回复模板" subtitle="仅供人工插入草稿；不被二发批次或 Agent 自动回复读取。"><div className="grid gap-5 p-5 lg:grid-cols-[1fr_360px]"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-gray-200 text-xs text-gray-500"><th className="p-3">分类</th><th className="p-3">名称</th><th className="p-3">正文</th></tr></thead><tbody>{data?.manualTemplates.map(row=><tr key={row.id} className="border-b border-gray-100 dark:border-gray-800"><td className="p-3">{row.category}</td><td className="p-3 font-medium">{row.name}</td><td className="p-3 text-gray-500">{row.body}</td></tr>)}</tbody></table>{data?.manualTemplates.length===0&&<p className="py-10 text-center text-sm text-gray-500">还没有人工回复模板。</p>}</div><div className="space-y-3"><Field label="模板名称"><Input value={name} onChange={event=>setName(event.target.value)} maxLength={60}/></Field><Field label="分类"><Input value={category} onChange={event=>setCategory(event.target.value)} maxLength={60}/></Field><Field label="正文"><TextArea value={body} onChange={event=>setBody(event.target.value)} maxLength={2000}/></Field><Button disabled={!name.trim()||!body.trim()} onClick={()=>void save()}>保存人工模板</Button>{message&&<Notice>{message}</Notice>}</div></div></Card>;
}

function AgentSettings(){
 const [data,setData]=useState<TemplateLibraryState|null>(null),[draft,setDraft]=useState<AgentSetting|null>(null),[message,setMessage]=useState("");
 const load=async()=>{const response=await fetch("/api/template-library",{cache:"no-store"});if(response.ok){const value=await response.json();setData(value);setDraft(value.agentSetting);}};useEffect(()=>{void load();},[]);
 const save=async()=>{if(!draft)return;const {revision,updatedAt,...setting}=draft;const response=await fetch("/api/template-library",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_agent",expectedRevision:revision,setting})});if(response.ok){const value=await response.json();setData(value);setDraft(value.agentSetting);setMessage("Agent 设置已保存；两个自动外发窗口没有重叠。");}else setMessage("设置未保存：回复窗口、缓冲期和二发窗口不能重叠。");};
 if(!draft)return <p className="text-sm text-gray-500">正在读取 Agent 设置…</p>;
 const labels:Record<string,string>={no_reply:"无需回复，直接结案",sample_self_service:"样品/物流自助",collaboration_ack:"合作确认",link_usage:"唯一商品链接用法",human:"人工接管"};
 return <div className="space-y-5"><Card title="Agent 集中回复时间" subtitle="收信全天持续；这里只控制自动外发。"><div className="space-y-4 p-5"><Toggle label="启用 Agent 自动处理" description="非人工场景在集中回复窗口执行；人工场景永不自动发送。" checked={draft.enabled} onChange={enabled=>setDraft({...draft,enabled})}/><div className="grid gap-4 md:grid-cols-5"><Field label="回复开始"><Input type="time" value={draft.replyStart} onChange={event=>setDraft({...draft,replyStart:event.target.value})}/></Field><Field label="回复结束"><Input type="time" value={draft.replyEnd} onChange={event=>setDraft({...draft,replyEnd:event.target.value})}/></Field><Field label="缓冲分钟"><Input type="number" min={0} max={180} value={draft.bufferMinutes} onChange={event=>setDraft({...draft,bufferMinutes:Number(event.target.value)})}/></Field><Field label="二发开始"><Input type="time" value={draft.sendStart} onChange={event=>setDraft({...draft,sendStart:event.target.value})}/></Field><Field label="二发结束"><Input type="text" value={draft.sendEnd} onChange={event=>setDraft({...draft,sendEnd:event.target.value})}/></Field></div><p className="text-xs text-gray-500">默认北京时间 15:00–16:00 集中回复，16:30–24:00 二发。</p><Button onClick={()=>void save()}>保存 Agent 设置</Button>{message&&<Notice tone={message.includes("已保存")?"success":"warning"}>{message}</Notice>}</div></Card><Card title="Agent 场景与固定回复"><div className="p-5"><MetricTable rows={Object.entries(draft.actions).map(([action,enabled])=>({label:labels[action],value:action==="human"?"人工":enabled?(draft.enabled?"自动":"启用后自动"):"关闭",detail:action==="no_reply"?"不发送消息，只推进处理水位":data?.agentTemplates.find(row=>row.action===action)?.text??"保持人工冻结",accent:action==="human"}))}/></div></Card></div>;
}

export default function ConversationWorkspace({section}:{section:ConversationSection}){
 return <div className="space-y-5"><PageHeading title="会话工作台" description="默认处理需要人工介入的真实会话；Agent 已处理与人工队列分开。" action={<Pill tone="warning">默认：需人工</Pill>}/><nav className="flex gap-1 overflow-x-auto rounded-xl bg-gray-100 p-1 dark:bg-gray-800">{nav.map(item=><Link key={item.id} href={item.id==="conversations"?"/it/conversations":`/it/conversations/${item.id}`} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-medium ${section===item.id?"bg-white shadow dark:bg-gray-700":"text-gray-500"}`}>{item.label}</Link>)}</nav>{section==="conversations"?<ConversationDesk/>:section==="templates"?<ManualTemplates/>:<AgentSettings/>}</div>;
}
