"use client";
import {useEffect,useState} from 'react';
import {Button,Card,Notice,PageHeading,Pill} from '../bdhub/ui';
import type {AccountStatus} from '../../server/market-accounts/bridge';
const date=(value:string|number|null|undefined)=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'未取得';
export default function MarketAccountsPage(){
 const [data,setData]=useState<AccountStatus|null>(null),[error,setError]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await fetch('/api/market-accounts',{cache:'no-store',signal:c.signal});if(!r.ok)throw Error();const value=await r.json();if(!c.signal.aborted){setData(value);setError(false);}}catch{if(!c.signal.aborted)setError(true);}finally{if(!c.signal.aborted)timer=setTimeout(poll,30000);}};void poll();return()=>{c.abort();clearTimeout(timer);};},[revision]);
 return <div className="space-y-5"><PageHeading title="账号管理" description="每个市场两个独立账号，统一管理业务分工与身份维护。" action={<Button variant="outline" onClick={()=>setRevision(v=>v+1)}>更新状态</Button>}/>
 {error&&<Notice tone="warning">暂时无法读取账号状态，已有分配保留。</Notice>}
 {!data&&!error&&<p className="text-sm text-gray-500">正在读取账号配置与维护状态…</p>}
 {data?.markets.map(m=><Card key={m.market} title={`${m.market==='it'?'意大利':m.market.toUpperCase()} · 双账号分工`} action={<Pill tone="brand">已登记，工作进程待迁移</Pill>}><div className="space-y-5 p-5"><div className="grid gap-4 lg:grid-cols-2">{m.accounts.map(a=><div key={a.account} className="rounded-2xl border border-gray-200 p-5 dark:border-gray-800"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold">{a.account.toUpperCase()}</h3><Pill tone={a.state==='healthy'?'success':'warning'}>{a.state==='healthy'?'维护状态正常':a.state==='due'?'维护到期':a.state==='attention'?'维护需处理':'配置待检查'}</Pill></div><p className="mt-2 text-sm font-medium text-brand-500">{a.role==='communications'?'通信主账号':'货盘与数据主账号'}</p><p className="mt-1 text-sm leading-6 text-gray-500">{a.role==='communications'?'负责收信、发送及回复；发送和自动回复当前保持暂停。':'负责货盘刷新、选入、建链及身份补全；读取已核验，写入和接管待验收。'}</p><dl className="mt-5 space-y-3 text-xs text-gray-500"><div className="flex justify-between gap-4"><dt>最近登录维护成功</dt><dd>{date(a.lastLogin)}</dd></div><div className="flex justify-between gap-4"><dt>新版计划：下次登录维护</dt><dd>{date(a.plannedLoginMaintenance)}</dd></div><div className="flex justify-between gap-4"><dt>凭证文件最近更新</dt><dd>{date(a.identityUpdatedAt)}</dd></div><div className="flex justify-between gap-4"><dt>旧版租约观察</dt><dd>{a.legacyLeaseBusy?'占用中':'未见活动租约'}</dd></div></dl><details className="mt-3 text-xs leading-6 text-gray-400"><summary className="cursor-pointer">旧服务执行状态</summary><p>旧服务当前维护到期：{date(a.nextMaintenance)}。新版周期尚未移交生效。</p></details><p className="mt-4 text-xs leading-6 text-gray-400">{a.evidence?`最近接口核验 ${date(a.evidence.checkedAt)}；机构、货盘读取、IM令牌和卡片搜索已通过。`:'等待真实接口核验。'}</p></div>)}</div>
 <Notice>{m.pairEvidence.state==='verified_readonly'?`两号同机构、同市场；${m.pairEvidence.sameSender?'共享同一个 IM 发送身份。':'发送身份需分别协调。'}并行只读核验已通过，两号可见相同商品卡 ${m.pairEvidence.sharedCardCount??0} 张（抽样）。`:'账号归属尚未完成核验。'} 每日新联系额度、去重与发送队列按机构和市场统一管理。</Notice>
 <p className="text-sm leading-6 text-gray-500">职责分配已保存。目前常驻工作进程仍主要使用 ACC6；迁移后由 ACC9 承接货盘与数据。ACC9 的真实发送、选入及建链尚未验收，自动切换未开启。</p></div></Card>)}
 {data&&<Card title="身份刷新与维护" subtitle="新版已确认计划；维护执行器移交前，旧服务仍按自身规则运行。"><div className="grid gap-4 p-5 sm:grid-cols-2">{[[`每 ${data.lifecycle.identityRefreshHours} 小时`,'无感身份更新','从本账号已登录环境更新身份资料。'],[`每 ${data.lifecycle.loginMaintenanceHours} 小时`,'登录维护','先处理在途任务，再独占账号维护。']].map(([period,title,desc])=><div key={title} className="rounded-xl bg-gray-50 p-4 dark:bg-gray-800"><p className="text-lg font-semibold">{period}</p><p className="mt-2 text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-6 text-gray-500">{desc}</p></div>)}</div><div className="space-y-2 px-5 pb-5 text-sm leading-6 text-gray-500"><p>已取消周期性的5分钟巡检和6小时深检，也不提前2小时登录维护。到期后按各自成功时间安排，同一时刻只维护一个账号。</p><p>过渡期仍由旧服务执行，新版暂不另启维护任务；新周期与旧服务实际到期时间分别展示。正常业务出现认证异常时按需恢复。</p><p>文件更新时间不代表 Cookie 剩余寿命；本轮 IM 令牌未提供明确过期字段，不能编造有效期。</p></div></Card>}
 <Card title="故障与接管规则"><div className="grid gap-4 p-5 text-sm leading-6 text-gray-500 sm:grid-cols-2"><p>一个账号故障：只有备用账号相应能力已验收，才承接未提交任务；否则保存进度等待。</p><p>已提交结果不明：留在原账号和原意图核验，不能换号补发。</p><p>登录或验证期间：先停止补入新请求，收齐在途结果；另一账号继续承担已验证的职责。</p><p>其他市场：由你分配各自的两个账号，同一账号不重复绑定到多个市场。</p></div></Card>
 {data&&<p className="text-xs text-gray-400">维护时间按北京时间显示 · 状态读取于 {date(data.checkedAt)} · 本页不启动发送或登录</p>}
 </div>;
}
