import {execFile} from "node:child_process";
import {join} from "node:path";
import {projectRoot} from "../creator-identities/refresh.ts";
import {enabledMarket} from "../markets/registry.ts";
import {isLocalRequest} from "../runtime/validation.ts";

export type MarketCatalogState={schemaVersion:"bdhub.market-catalog.v1";market:string;label:string;capabilities:{campaignCatalog:boolean;fullManagedCatalog:boolean};account:string;accountCapabilities:Record<string,string>;campaign:Record<string,unknown>;screen:Record<string,unknown>;fullManaged:Record<string,unknown>;downstream:{leadEdges:number;identityResolved:number;deliveriesConfirmed:number;activeTapLinks:number};readOnly:true;platformWrites:0;realSends:0};
const cleanMarket=(value:unknown)=>{if(typeof value!=="string"||!enabledMarket(value))throw Error("market_invalid");return value;};
function validate(raw:unknown):MarketCatalogState{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw Error("market_catalog_invalid");const v=raw as Record<string,unknown>,cap=v.capabilities as Record<string,unknown>,down=v.downstream as Record<string,unknown>;if(v.schemaVersion!=="bdhub.market-catalog.v1"||typeof v.market!=="string"||!enabledMarket(v.market)||typeof v.label!=="string"||typeof v.account!=="string"||!cap||typeof cap.campaignCatalog!=="boolean"||typeof cap.fullManagedCatalog!=="boolean"||!v.accountCapabilities||typeof v.accountCapabilities!=="object"||!v.campaign||typeof v.campaign!=="object"||!v.screen||typeof v.screen!=="object"||!v.fullManaged||typeof v.fullManaged!=="object"||!down||['leadEdges','identityResolved','deliveriesConfirmed','activeTapLinks'].some(key=>typeof down[key]!=="number"||!Number.isSafeInteger(down[key])||Number(down[key])<0)||v.readOnly!==true||v.platformWrites!==0||v.realSends!==0)throw Error("market_catalog_invalid");return v as unknown as MarketCatalogState;}
function run(action:"status"|"preview-campaign",market:string){const root=projectRoot();return new Promise<MarketCatalogState>((resolve,reject)=>execFile(join(root,".venv/bin/python"),[join(root,"scripts/market-catalog-status.py"),action,"--market",market],{cwd:root,timeout:60_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error(String(value?.error||"market_catalog_unavailable"));resolve(validate(value));}catch(error){reject(error);}}));}
const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
export const handlers={GET:async(request:Request)=>{if(!isLocalRequest(request,false))return Response.json({error:"local_origin_required"},{status:403,headers});const url=new URL(request.url);let market:string;try{if([...url.searchParams.keys()].some(key=>key!=="market")||url.searchParams.getAll("market").length!==1)throw Error();market=cleanMarket(url.searchParams.get("market"));}catch{return Response.json({error:"invalid_query"},{status:400,headers});}try{return Response.json(await run("status",market),{headers});}catch{return Response.json({error:"market_catalog_unavailable"},{status:503,headers});}},POST:async(request:Request)=>{if(!isLocalRequest(request,true))return Response.json({error:"local_origin_required"},{status:403,headers});let market:string;try{if(request.headers.get("content-type")?.split(";")[0].trim()!=="application/json")return Response.json({error:"json_required"},{status:415,headers});const raw=await request.text();if(new TextEncoder().encode(raw).length>1024)throw Error();const value=JSON.parse(raw);if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).sort().join(",")!=="action,market"||value.action!=="preview_campaign")throw Error();market=cleanMarket(value.market);}catch{return Response.json({error:"invalid_market_catalog_request"},{status:400,headers});}try{return Response.json(await run("preview-campaign",market),{headers});}catch{return Response.json({error:"market_catalog_unavailable"},{status:503,headers});}}};
