import {execFile} from "node:child_process";
import {join} from "node:path";
import {projectRoot} from "../creator-identities/refresh.ts";
import {isLocalRequest} from "../runtime/validation.ts";

export type OperationsSetting={market:"it";automaticOperationsEnabled:boolean;fullCatalogWeeklyEnabled:boolean;continuousSendEnabled:boolean;revision:number;updatedAt:number};
export type OperationsStage={id:string;label:string;state:string;counts:Record<string,unknown>;processed:number;lastSuccessAt:number|null;nextAt:number|null;checkpoint:Record<string,unknown>;stopReason:string|null;platformWrites:number;generationId:string|null};
export type OperationsHome={schemaVersion:"bdhub.operations-home.v1";market:"it";setting:OperationsSetting;workflow:{runId:string|null;state:string;startedAt:number|null;finishedAt:number|null};stages:OperationsStage[];issues:Array<{kind:string;id:string;title:string;reason:string}>;jobs:unknown;accounts:unknown;continuousSend:unknown;agent:{enabled:boolean;revision:number;replyWindow:[string,string]};readOnly:true;platformWrites:0;realSends:0};

const text=(value:unknown,max=160,empty=false)=>{if(typeof value!=="string"||(!empty&&!value)||value.length>max)throw Error("invalid_operations_home");return value;};
const stamp=(value:unknown)=>value==null?null:typeof value==="number"&&Number.isFinite(value)&&value>=0?value:(()=>{throw Error("invalid_operations_home")})();
const integer=(value:unknown,max=Number.MAX_SAFE_INTEGER)=>typeof value==="number"&&Number.isSafeInteger(value)&&value>=0&&value<=max?value:(()=>{throw Error("invalid_operations_home")})();
const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw Error("invalid_operations_home");return value as Record<string,unknown>;};
function setting(raw:unknown):OperationsSetting{const v=object(raw);if(v.market!=="it"||typeof v.automaticOperationsEnabled!=="boolean"||typeof v.fullCatalogWeeklyEnabled!=="boolean"||typeof v.continuousSendEnabled!=="boolean")throw Error("invalid_operations_home");return {market:"it",automaticOperationsEnabled:v.automaticOperationsEnabled,fullCatalogWeeklyEnabled:v.fullCatalogWeeklyEnabled,continuousSendEnabled:v.continuousSendEnabled,revision:integer(v.revision,1_000_000),updatedAt:stamp(v.updatedAt)??0};}
export function validateOperationsHome(raw:unknown):OperationsHome{const v=object(raw);if(v.schemaVersion!=="bdhub.operations-home.v1"||v.market!=="it"||v.readOnly!==true||v.platformWrites!==0||v.realSends!==0||!Array.isArray(v.stages)||v.stages.length!==7||!Array.isArray(v.issues)||v.issues.length>100)throw Error("invalid_operations_home");const workflow=object(v.workflow);const stages=v.stages.map(rawStage=>{const row=object(rawStage);return {id:text(row.id,40),label:text(row.label,40),state:text(row.state,40),counts:object(row.counts),processed:integer(row.processed),lastSuccessAt:stamp(row.lastSuccessAt),nextAt:stamp(row.nextAt),checkpoint:object(row.checkpoint),stopReason:row.stopReason==null?null:text(row.stopReason,160),platformWrites:integer(row.platformWrites),generationId:row.generationId==null?null:text(row.generationId,80)};});const issues=v.issues.map(rawIssue=>{const row=object(rawIssue);return {kind:text(row.kind,32),id:text(row.id,120),title:text(row.title,80),reason:text(row.reason,240)};});const agent=object(v.agent);if(typeof agent.enabled!=="boolean"||!Array.isArray(agent.replyWindow)||agent.replyWindow.length!==2)throw Error("invalid_operations_home");return {schemaVersion:"bdhub.operations-home.v1",market:"it",setting:setting(v.setting),workflow:{runId:workflow.runId==null?null:text(workflow.runId,120),state:text(workflow.state,40),startedAt:stamp(workflow.startedAt),finishedAt:stamp(workflow.finishedAt)},stages,issues,jobs:v.jobs,accounts:v.accounts,continuousSend:v.continuousSend,agent:{enabled:agent.enabled,revision:integer(agent.revision),replyWindow:[text(agent.replyWindow[0],5),text(agent.replyWindow[1],5)]},readOnly:true,platformWrites:0,realSends:0};}
function run(action:"status"|"save",body?:Record<string,unknown>):Promise<OperationsHome>{const root=projectRoot();const args=[join(root,"scripts/operations-home.py"),action];if(body)args.push("--json",JSON.stringify(body));return new Promise((resolve,reject)=>execFile(join(root,".venv/bin/python"),args,{cwd:root,timeout:60_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error(String(value?.error||"operations_home_unavailable"));resolve(validateOperationsHome(value));}catch(error){reject(error);}}));}
const requestId=(value:unknown)=>{const result=text(value,120);if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/.test(result))throw Error();return result;};
async function jsonBody(request:Request){if(request.headers.get("content-type")?.split(";")[0].trim()!=="application/json")throw Error("json_required");const raw=await request.text();if(new TextEncoder().encode(raw).length>4096)throw Error("too_large");return JSON.parse(raw);}
const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
export const handlers={GET:async(request:Request)=>{if(!isLocalRequest(request,false))return Response.json({error:"local_origin_required"},{status:403,headers});if(new URL(request.url).search)return Response.json({error:"invalid_query"},{status:400,headers});try{return Response.json(await run("status"),{headers});}catch{return Response.json({error:"operations_home_unavailable"},{status:503,headers});}},POST:async(request:Request)=>{if(!isLocalRequest(request,true))return Response.json({error:"local_origin_required"},{status:403,headers});let value:Record<string,unknown>;try{value=object(await jsonBody(request));if(Object.keys(value).some(key=>!["action","requestId","expectedRevision","changes"].includes(key))||value.action!=="save")throw Error();const changes=object(value.changes);if(!Object.keys(changes).length||Object.keys(changes).some(key=>!["automaticOperationsEnabled","fullCatalogWeeklyEnabled","continuousSendEnabled"].includes(key))||Object.values(changes).some(item=>typeof item!=="boolean"))throw Error();value={requestId:requestId(value.requestId),expectedRevision:integer(value.expectedRevision),changes};}catch(error){return Response.json({error:error instanceof Error&&error.message==="json_required"?"json_required":"invalid_operations_request"},{status:error instanceof Error&&error.message==="json_required"?415:400,headers});}try{return Response.json(await run("save",value),{headers});}catch(error){const code=error instanceof Error?error.message:"operations_home_unavailable";return Response.json({error:code},{status:code.includes("conflict")?409:503,headers});}}};
