import {execFile} from "node:child_process";
import {join} from "node:path";
import {projectRoot} from "../runtime/project-root.ts";
import {isLocalRequest} from "../runtime/validation.ts";
import {enabledMarket} from "../markets/registry.ts";
import {singleflight} from "../runtime/singleflight.ts";

export type OperationsSetting={market:string;automaticOperationsEnabled:boolean;fullCatalogWeeklyEnabled:boolean;continuousSendEnabled:boolean;revision:number;updatedAt:number};
export type OperationsStage={id:string;label:string;state:string;counts:Record<string,unknown>;processed:number;lastSuccessAt:number|null;nextAt:number|null;checkpoint:Record<string,unknown>;stopReason:string|null;platformWrites:number;generationId:string|null};
export type OperationsHome={schemaVersion:"bdhub.operations-home.v1";market:string;setting:OperationsSetting;workflow:{runId:string|null;state:string;startedAt:number|null;finishedAt:number|null};stages:OperationsStage[];issues:Array<{kind:string;id:string;title:string;reason:string}>;jobs:unknown;accounts:unknown;continuousSend:unknown;agent:{enabled:boolean;revision:number;replyWindow:[string,string]};templateReview:{minimumApproved:number;approved:number;total:number;ready:boolean};readOnly:true;platformWrites:0;realSends:0};

const text=(value:unknown,max=160,empty=false)=>{if(typeof value!=="string"||(!empty&&!value)||value.length>max)throw Error("invalid_operations_home");return value;};
const stamp=(value:unknown)=>value==null?null:typeof value==="number"&&Number.isFinite(value)&&value>=0?value:(()=>{throw Error("invalid_operations_home")})();
const integer=(value:unknown,max=Number.MAX_SAFE_INTEGER)=>typeof value==="number"&&Number.isSafeInteger(value)&&value>=0&&value<=max?value:(()=>{throw Error("invalid_operations_home")})();
const object=(value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw Error("invalid_operations_home");return value as Record<string,unknown>;};
function setting(raw:unknown):OperationsSetting{const v=object(raw);if(typeof v.market!=="string"||!enabledMarket(v.market)||typeof v.automaticOperationsEnabled!=="boolean"||typeof v.fullCatalogWeeklyEnabled!=="boolean"||typeof v.continuousSendEnabled!=="boolean")throw Error("invalid_operations_home");return {market:v.market,automaticOperationsEnabled:v.automaticOperationsEnabled,fullCatalogWeeklyEnabled:v.fullCatalogWeeklyEnabled,continuousSendEnabled:v.continuousSendEnabled,revision:integer(v.revision,1_000_000),updatedAt:stamp(v.updatedAt)??0};}
export function validateOperationsHome(raw:unknown,expectedMarket?:string):OperationsHome{const v=object(raw);if(v.schemaVersion!=="bdhub.operations-home.v1"||typeof v.market!=="string"||!enabledMarket(v.market)||expectedMarket!==undefined&&v.market!==expectedMarket||v.readOnly!==true||v.platformWrites!==0||v.realSends!==0||!Array.isArray(v.stages)||v.stages.length!==7||!Array.isArray(v.issues)||v.issues.length>100)throw Error("invalid_operations_home");const workflow=object(v.workflow);const stages=v.stages.map(rawStage=>{const row=object(rawStage);return {id:text(row.id,40),label:text(row.label,40),state:text(row.state,40),counts:object(row.counts),processed:integer(row.processed),lastSuccessAt:stamp(row.lastSuccessAt),nextAt:stamp(row.nextAt),checkpoint:object(row.checkpoint),stopReason:row.stopReason==null?null:text(row.stopReason,160),platformWrites:integer(row.platformWrites),generationId:row.generationId==null?null:text(row.generationId,80)};});const issues=v.issues.map(rawIssue=>{const row=object(rawIssue);return {kind:text(row.kind,32),id:text(row.id,120),title:text(row.title,80),reason:text(row.reason,240)};});const agent=object(v.agent),review=object(v.templateReview);if(typeof agent.enabled!=="boolean"||!Array.isArray(agent.replyWindow)||agent.replyWindow.length!==2||typeof review.ready!=="boolean")throw Error("invalid_operations_home");const templateReview={minimumApproved:integer(review.minimumApproved,50),approved:integer(review.approved,50),total:integer(review.total,50),ready:review.ready};if(templateReview.ready!==(templateReview.approved>=templateReview.minimumApproved))throw Error("invalid_operations_home");const saved=setting(v.setting);if(saved.market!==v.market)throw Error("invalid_operations_home");return {schemaVersion:"bdhub.operations-home.v1",market:v.market,setting:saved,workflow:{runId:workflow.runId==null?null:text(workflow.runId,120),state:text(workflow.state,40),startedAt:stamp(workflow.startedAt),finishedAt:stamp(workflow.finishedAt)},stages,issues,jobs:v.jobs,accounts:v.accounts,continuousSend:v.continuousSend,agent:{enabled:agent.enabled,revision:integer(agent.revision),replyWindow:[text(agent.replyWindow[0],5),text(agent.replyWindow[1],5)]},templateReview,readOnly:true,platformWrites:0,realSends:0};}
/** Authoritative outcome of a save: the setting that was committed, independent of any later re-read. */
export type SaveCommit={requestId:string;committed:true;duplicate:boolean;originalAvailable:boolean;setting:OperationsSetting;launchErrors:Array<{worker:string;error:string}>;projectionStale:boolean;refreshFailed:boolean};
class SaveError extends Error{commit:Record<string,unknown>|null;constructor(code:string,commit:Record<string,unknown>|null){super(code);this.commit=commit;}}
function commitReceipt(raw:unknown,requestIdValue:string,extra:{projectionStale:boolean;refreshFailed:boolean}):SaveCommit{
 const v=object(raw);if(v.committed!==true||v.requestId!==requestIdValue||!Array.isArray(v.launchErrors)||v.launchErrors.length>5)throw Error("invalid_operations_home");
 const launchErrors=v.launchErrors.map(item=>{const row=object(item);return {worker:text(row.worker,40),error:text(row.error,160)};});
 return {requestId:requestIdValue,committed:true,duplicate:v.duplicate===true,originalAvailable:v.originalAvailable!==false,setting:setting(v.setting),launchErrors,...extra};
}
function runSave(body:Record<string,unknown>):Promise<{home:OperationsHome;commit:Record<string,unknown>}>{const root=projectRoot();return new Promise((resolve,reject)=>execFile(join(root,".venv/bin/python"),[join(root,"scripts/operations-home.py"),"save","--json",JSON.stringify(body)],{cwd:root,timeout:60_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{let value:Record<string,unknown>|null=null;try{value=JSON.parse(stdout);}catch{value=null;}const commit=value&&typeof value.commit==="object"&&value.commit!==null?value.commit as Record<string,unknown>:null;if(error||!value||value.error){reject(new SaveError(String(value?.error||"operations_home_unavailable"),commit));return;}try{resolve({home:validateOperationsHome(value,String(body.market)),commit:commit??{}});}catch{reject(new SaveError("operations_home_refresh_failed",commit));}}));}
function run(action:"status"|"save",body?:Record<string,unknown>):Promise<OperationsHome>{const root=projectRoot();const args=[join(root,"scripts/operations-home.py"),action];if(body)args.push("--json",JSON.stringify(body));return new Promise((resolve,reject)=>execFile(join(root,".venv/bin/python"),args,{cwd:root,timeout:60_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error(String(value?.error||"operations_home_unavailable"));resolve(validateOperationsHome(value,String(body?.market??"")));}catch(error){reject(error);}}));}
function readModel(market:string):Promise<OperationsHome>{const root=projectRoot();return new Promise((resolve,reject)=>execFile(join(root,".venv/bin/python"),[join(root,"scripts/project-market-read-model.py"),"read","--market",market,"--view","operations","--max-age","120"],{cwd:root,timeout:10_000,maxBuffer:4*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error();resolve(validateOperationsHome(value,market));}catch{reject(Error("market_read_model_unavailable"));}}));}
function project(market:string){const root=projectRoot();return new Promise<void>((resolve,reject)=>execFile(join(root,".venv/bin/python"),[join(root,"scripts/project-market-read-model.py"),"project","--market",market,"--view","operations"],{cwd:root,timeout:60_000,maxBuffer:1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},error=>error?reject(error):resolve()));}
const requestId=(value:unknown)=>{const result=text(value,120);if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/.test(result))throw Error();return result;};
async function jsonBody(request:Request){if(request.headers.get("content-type")?.split(";")[0].trim()!=="application/json")throw Error("json_required");const raw=await request.text();if(new TextEncoder().encode(raw).length>4096)throw Error("too_large");return JSON.parse(raw);}
const market=(value:unknown)=>typeof value==="string"&&enabledMarket(value)?value:(()=>{throw Error("invalid_market")})();
const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
export const handlers={GET:async(request:Request)=>{if(!isLocalRequest(request,false))return Response.json({error:"local_origin_required"},{status:403,headers});const url=new URL(request.url);let selected:string;try{if([...url.searchParams.keys()].some(key=>key!=="market")||url.searchParams.getAll("market").length!==1)throw Error();selected=market(url.searchParams.get("market"));}catch{return Response.json({error:"invalid_query"},{status:400,headers});}try{return Response.json(await singleflight(`operations:${selected}`,()=>readModel(selected).catch(()=>run("status",{market:selected}))),{headers});}catch{return Response.json({error:"operations_home_unavailable"},{status:503,headers});}},POST:async(request:Request)=>{if(!isLocalRequest(request,true))return Response.json({error:"local_origin_required"},{status:403,headers});let urlMarket:string,value:Record<string,unknown>;try{const url=new URL(request.url);if([...url.searchParams.keys()].some(key=>key!=="market")||url.searchParams.getAll("market").length!==1)throw Error();urlMarket=market(url.searchParams.get("market"));value=object(await jsonBody(request));if(Object.keys(value).some(key=>!["action","market","requestId","expectedRevision","changes"].includes(key))||value.action!=="save")throw Error();const changes=object(value.changes);if(!Object.keys(changes).length||Object.keys(changes).some(key=>!["automaticOperationsEnabled","fullCatalogWeeklyEnabled","continuousSendEnabled"].includes(key))||Object.values(changes).some(item=>typeof item!=="boolean"))throw Error();value={market:market(value.market),requestId:requestId(value.requestId),expectedRevision:integer(value.expectedRevision),changes};}catch(error){return Response.json({error:error instanceof Error&&error.message==="json_required"?"json_required":"invalid_operations_request"},{status:error instanceof Error&&error.message==="json_required"?415:400,headers});}if(value.market!==urlMarket)return Response.json({error:"market_mismatch"},{status:409,headers});try{const {home,commit}=await runSave(value);let projectionStale=false;try{await project(String(value.market));}catch{projectionStale=true;}return Response.json({...home,commit:commitReceipt(commit,String(value.requestId),{projectionStale,refreshFailed:false})},{headers});}catch(error){
 // Committed but not re-readable: report the committed setting, never "not saved".
 if(error instanceof SaveError&&error.commit?.committed===true&&error.commit.setting){try{return Response.json({committed:true,commit:commitReceipt(error.commit,String(value.requestId),{projectionStale:true,refreshFailed:true})},{status:202,headers});}catch{return Response.json({error:"operations_commit_unconfirmed",committed:null},{status:503,headers});}}
 const code=error instanceof Error?error.message:"operations_home_unavailable";return Response.json({error:code},{status:code.includes("conflict")||code.includes("not_supported")||code.includes("approval_required")?409:503,headers});}}};
