import {execFile,spawn} from 'node:child_process';
import {join} from 'node:path';
import {projectRoot} from '../creator-identities/refresh.ts';
import {isLocalRequest} from '../runtime/validation.ts';
export type AccountRow={account:string;role:string;responsibilities:string[];state:string;enabled?:boolean;localEnabled?:boolean;localRevision?:number;legacyLeaseBusy?:boolean;legacyOperation?:string|null;lastLogin?:string|null;nextMaintenance?:string|null;plannedLoginMaintenance?:string|number|null;identityUpdatedAt?:number|null;evidence?:{checkedAt:number;capabilities:Record<string,string>;tokenHasExplicitExpiry:boolean}|null;identityGeneration?:{generationId:string;state:string;publishedAt:number;browserRef:string;httpRef:string;imRef:string;capabilities:Record<string,{state:string}>}|null;maintenanceIntent?:{intentId:string;state:string;operation:string;errorCode:string|null;checkpoint?:{stage?:string;visibleBrowser?:boolean;generationId?:string;inboxReconnected?:boolean}}|null};
export type AccountStatus={markets:Array<{market:string;state:string;linkCanary?:{state:string;pid?:string;shortName?:string;listId?:string;creatorPercent?:string;publicPercent?:string;totalPercent?:string;agencyPercent?:string;checkedAt?:number}|null;accounts:AccountRow[];pairEvidence:{state:string;sameSender?:boolean;sharedCardCount?:number;concurrentReadSeconds?:number};maintenanceExecutor:string;autoSwitchEnabled:false}>;lifecycle:{healthPollMinutes:null;deepCheckHours:null;identityRefreshHours:number;loginMaintenanceHours:number;standbyEarlyMaintenanceHours:number;globalLoginConcurrency:number;enableNewMaintenanceWorker:boolean};checkedAt:number;executionEnabled:false;realSends:0};
export function readAccounts():Promise<AccountStatus>{const root=projectRoot();return new Promise((resolve,reject)=>{
 execFile(join(root,'.venv/bin/python'),[join(root,'scripts/market-account-status.py')],{cwd:root,timeout:10000,maxBuffer:131072,env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}},(e,out)=>{
  try{if(e)throw e;const v=JSON.parse(out);if(v.executionEnabled!==false||v.realSends!==0||!Array.isArray(v.markets)||!v.markets.every((m:AccountStatus['markets'][number])=>Array.isArray(m.accounts)&&m.accounts.length===2))throw Error();resolve(v);}catch{reject(Error('account_status_unavailable'));}
 });
});}
export function createAccountsGet(read=readAccounts){return async(request:Request)=>{
 const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
 if(!isLocalRequest(request,false))return Response.json({error:'local_origin_required'},{status:403,headers});
 if(request.method!=='GET')return Response.json({error:'method_not_allowed'},{status:405,headers});
 if(new URL(request.url).search)return Response.json({error:'invalid_query'},{status:400,headers});
 try{return Response.json(await read(),{headers});}catch{return Response.json({error:'account_status_unavailable'},{status:503,headers});}
};}
export type AccountMutation={action:"set_enabled"|"refresh"|"relogin";account:"acc6"|"acc9";requestId:string;expectedRevision?:number;enabled?:boolean};
export function validateAccountMutation(raw:unknown):AccountMutation{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw Error('invalid_account_request');const value=raw as Record<string,unknown>;if(!['set_enabled','refresh','relogin'].includes(String(value.action))||!['acc6','acc9'].includes(String(value.account))||typeof value.requestId!=="string"||!/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/.test(value.requestId))throw Error('invalid_account_request');if(value.action==='set_enabled'){if(Object.keys(value).some(key=>!['action','account','requestId','expectedRevision','enabled'].includes(key))||typeof value.enabled!=="boolean"||typeof value.expectedRevision!=="number"||!Number.isSafeInteger(value.expectedRevision)||value.expectedRevision<0)throw Error('invalid_account_request');return {action:'set_enabled',account:value.account as 'acc6'|'acc9',requestId:value.requestId,expectedRevision:value.expectedRevision,enabled:value.enabled};}if(Object.keys(value).some(key=>!['action','account','requestId'].includes(key)))throw Error('invalid_account_request');return {action:value.action as 'refresh'|'relogin',account:value.account as 'acc6'|'acc9',requestId:value.requestId};}
export function mutateAccount(input:AccountMutation):Promise<void>{const root=projectRoot();const action=input.action==='set_enabled'?'set-enabled':'request';const payload=input.action==='set_enabled'?{account:input.account,enabled:input.enabled,requestId:input.requestId,expectedRevision:input.expectedRevision}:{account:input.account,operation:input.action,requestId:input.requestId};return new Promise((resolve,reject)=>execFile(join(root,'.venv/bin/python'),[join(root,'scripts/account-identity.py'),action,'--json',JSON.stringify(payload)],{cwd:root,timeout:30000,maxBuffer:512*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}},(error,stdout)=>{try{const value=JSON.parse(stdout);if(error||value?.error)throw Error(String(value?.error||'account_mutation_unavailable'));if(input.action==='refresh'||input.action==='relogin'){const worker=spawn(join(root,'.venv/bin/python'),[join(root,'scripts/account-maintenance-worker.py')],{cwd:root,detached:true,stdio:'ignore',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});worker.unref();}resolve();}catch(error){reject(error);}}));}
