import {execFile} from "node:child_process";
import {join} from "node:path";
import {projectRoot} from "../creator-identities/refresh.ts";
import {isLocalRequest} from "../runtime/validation.ts";

export type ProductMaterial={pid:string;name:null|{shortNameIt:string;shortNameZh:string;mentionIt:string};creatorPercent:string;card:{state:string;observedCreatorRates?:string[]};templates:Array<{version:number;template:string;textIt:string;translationZh:string}>};
export type ReviewBatch={id:string;snapshotHash:string;expired:boolean;executionAllowed:false;items:Array<{allowanceReview?:{lastObservedOutboundAt:string|null;elapsedDaysSinceObservedOutbound:number|null};handle:string;pid:string;name:{shortNameZh:string};offer:{creatorPercent:string};card:{listId:string};message:{textIt:string;translationZh:string};checks:{remoteHistory?:{status:string;history?:{messageCount:number;hasMore:boolean;senderCounts?:{ourMessages:number;creatorReplies:number;showcaseNotifications:number;otherOrUnknown:number}};priorObservation?:{history:{messageCount:number}}};legacy:{localOutboundCount?:number;localReplyCount?:number;manualState?:string|null};platform:{status:string;hasPermission?:boolean|null;collaborationTypes?:number[]}};blockingReasons:string[]}>};
export type SpeedStatus={targetContactsPerMinute:number;completedGroupsPerMinute:number;targetAttainmentPercent:number;lastMinuteCompletedGroups:number;nativeRejections:number;contactsPerMinute:number;messagesPerMinute:number;lastMinuteContacts:number;last15MinutesContacts:number;cardToTextMedianSeconds:number|null;preparedToCardMedianSeconds:number|null;unconfirmedAttemptPercent:number|null;optimizedSamples:number;optimizedCardToTextMedianSeconds:number|null;policy?:{send_interval:number;at:number}|null;buckets:Array<{at:number;contacts:number;messages:number;completed:number}>;stages:Array<{stage:string;averageSeconds:number|null;samples:number;failedOperations:number}>;worker?:{phase:string;fresh:boolean}|null};
export type CycleStatus={speed?:SpeedStatus|null;delivery?:{bulk?:{id:string;state:string;target:number;counts:Record<string,number>}|null;states:Record<string,number>;confirmedParts:number}|null;schedule?:Array<{stage:string;state:string;due:number;finished:number|null;failures:number}>;inbox?:{events:number;historicalEvents:number;conversations:number;gaps:number;pendingContent:number;lastCheckedAt:number|null;automaticRepliesEnabled:boolean}|null;available?:boolean;executionAllowed:false;modelCalls?:number;materials?:ProductMaterial[];reviewBatch?:ReviewBatch|null;relationships?:number;sourceEdges?:number;opportunities?:number;eligibleUniqueCreators?:number;identitySourceEdges?:number;identityResolvedEdges?:number;identityUnmatchedEdges?:number;jobs?:Record<string,number>;sourceIssues?:Array<{code:string;window_start:string;window_end:string}>;offerCount?:number;eligibleOfferCount?:number;offers?:Array<{title?:string;pid:string;offerKey?:string;catalogSource?:string;commissionState?:string;assessment:{eligible:boolean;reasons:string[]}}>};
export function validateCycle(value:unknown):CycleStatus {
  if(!value||typeof value!=="object"||!("executionAllowed" in value)||value.executionAllowed!==false)throw new Error("invalid_cycle_status");
  const v=value as CycleStatus;
  if(v.available===false)return {available:false,executionAllowed:false};
  for(const key of ["relationships","sourceEdges","opportunities","eligibleUniqueCreators"] as const)if(!Number.isSafeInteger(v[key])||Number(v[key])<0)throw new Error("invalid_cycle_count");
  if(!Array.isArray(v.offers)||v.offers.length>10000||!v.offers.every(o=>o&&typeof o.pid==="string"&&(!o.title||typeof o.title==="string")&&o.assessment&&typeof o.assessment.eligible==="boolean"&&Array.isArray(o.assessment.reasons)&&o.assessment.reasons.every(r=>typeof r==="string")))throw new Error("invalid_cycle_offers");
  return v;
}
export function readCycle():Promise<CycleStatus>{const root=projectRoot();return new Promise((resolve,reject)=>{execFile(join(root,"../01-BDSystem-V2/.venv/bin/python"),[join(root,"scripts/second-cycle.py"),"status"],{cwd:root,timeout:15000,maxBuffer:2*1024*1024,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"}},(error,stdout)=>{try{if(error)throw error;resolve(validateCycle(JSON.parse(stdout)));}catch{reject(new Error("cycle_unavailable"));}});});}
export function createCycleGet(read=readCycle){return async(request:Request)=>{
 const headers={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};
 if(!isLocalRequest(request,false))return Response.json({error:"local_origin_required"},{status:403,headers});
 if(new URL(request.url).search)return Response.json({error:"invalid_query"},{status:400,headers});
 try{return Response.json(validateCycle(await read()),{headers});}catch{return Response.json({error:"cycle_unavailable"},{status:503,headers});}
};}
